### ISSUE TITLE
Video Calling example don't work on Android Oreo

### ISSUE THREAD

**Issue by mohammedgmgn** [AgoraIO/Flutter-SDK#1]
<p align="center">
<img src="https://user-images.githubusercontent.com/17784553/53228760-d21ccb80-368a-11e9-976f-3bd11cf5e48b.png" alt="" width="200" height="400"/>
</p>

## Steps to reproduce
1-  provided App ID from the Dashboard
2- run flutter sameple on Android 8

## Expected results
Data is sent between the peer connections.

## Actual results
No data is sent between the peer connections.

**Comment by PRWrl** [comment]
Hi @mohammedgmgn , would you try allow the example demo access camera and microphone in Settings?

**Comment by PRWrl** [comment]
Hi @mohammedgmgn , can you try allow the example demo access camera and microphone in Settings?

**Comment by mohammedgmgn** [comment]
@PRWrl  it works now, but I have already allowed the permission before
