### ISSUE TITLE
RtcStats "users" always null

### ISSUE THREAD

**Issue by a-leblond** [AgoraIO/Flutter-SDK#10]
Hi,

I'm trying to get the number of viewers of a Broadcast, is "users" from RtcStats the value that i need ?

If so, it seems to be always null, on the Broadcaster side as well as on the Audience side.

Here is the code i use : 
`void _addAgoraEventHandlers() { 
   AgoraRtcEngine.onRtcStats = (RtcStats stats) { setState(() { viewers = stats.users; }); }; 
}`

Then i display the viewers number in a Text widget.

Beside that, i encountered 0 problem using Agora it's a great platform !

**Comment by PRWrl** [comment]
Thank you, a quick fix https://github.com/AgoraIO/Flutter-SDK/commit/b4b832c4d257a56b634918108d1a841f54038be1, and submitted a new version 0.9.5 to pub to fix this issue.

**Comment by a-leblond** [comment]
Great ! Thanks a lot for your quick fix !

**Comment by PRWrl** [comment]
By the way, only broadcasters and self will count in 'users'.
A broadcaster can not know how many audience in this channel throw this rtc sdk. It needs a biz/signaling server.

**Comment by a-leblond** [comment]
So if there is a Broadcaster and 3 people in the audience, everyone will see "2" viewers ?

**Comment by PRWrl** [comment]
Exactly, see the document about 'users' in RtcStats https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler_1_1_rtc_stats.html#aed1065e64c0b7e066776f14ca53c877e

**Comment by a-leblond** [comment]
Thanks for the infos !

**Comment by wheel1992** [comment]
Hi agora team, how do we get the total number of viewers?

**Comment by LichKing-2234** [comment]
@wheel1992 you can refer to https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/174
