### ISSUE TITLE
onUpdatedUserInfo throws error due to unknown 'userInfo' property

### ISSUE THREAD

**Issue by shu8** [AgoraIO/Flutter-SDK#100]
I'm trying to use the `onUpdatedUserInfo` event along with the `AgoraRtcEngine.joinChannelByUserAccount` method but an error is thrown when the event fires.

It looks like the [`AgoraRtcEngine._eventListener` method](https://github.com/AgoraIO/Flutter-SDK/blob/master/lib/agora_rtc_engine.dart#L1306) does:

https://github.com/AgoraIO/Flutter-SDK/blob/8c2c5c2a72b7091a9d065415c9f566c6a8aee68a/lib/agora_rtc_engine.dart#L1303-L1306

but I think the `map['userInfo']` should actually be `map[userAccount]` -- that is what [events like `onRegisteredUser`](https://github.com/AgoraIO/Flutter-SDK/blob/master/lib/agora_rtc_engine.dart#L1298) use.

However, it looks like there is a mismatch between the terms used in the iOS and Android code:

- iOS uses `userInfo`: https://github.com/AgoraIO/Flutter-SDK/blob/da2e1e65eac8ddc454b75f3f1e83b5e5c52df70b/ios/Classes/AgoraRtcEnginePlugin.m#L888
- Android uses `userAccount`: https://github.com/AgoraIO/Flutter-SDK/blob/bc5807877ead5dc7a8c6425ca86dcbc20fa48190/android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java#L1158

so I think just one of them needs to be updated?

It looks like both normally use `userAccount`, so am I right in thinking it's just the iOS code and `AgoraRtcEngine._eventListener` method that need updating?

Please let me know if I can provide further details!

**Comment by rgb1380** [comment]
Spot on. I was having the same problem. The map contains 'userAccount' and not 'userInfo'. Looks like a typo.

**Comment by LichKing-2234** [comment]
@rgb1380 @shu8 I have upgraded SDK, you can try again later.

**Comment by shu8** [comment]
Thanks, looks like it's working now! :)
