### ISSUE TITLE
onUpdateUserInfo not inovked on remote user rejoin

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Flutter-SDK#101]
After solving issue #100, there is an additional problem where onUpdateUserInfo is not invoked when a remote user leaves the channel and rejoins.

**Comment by LichKing-2234** [comment]
onUserInfoUpdated is not for user leaves or rejoins, you can see [this](https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler.html#aa3e9ead25f7999272d5700c427b2cb3d)
you can use `onUserOffline`

**Comment by rgb1380** [comment]
You misunderstand. 
When the user leaves the channel, there is no expectation that onUpdateUserInfo is called. However, when the user joins the channel (again), onUserJoined is invoked, this gives you the uid but not the one's own user id which was registered before. It makes sense that after every onUserJoined there is also an invocation of onUdatedUserInfo so that there is access to one's own user id.

**Comment by LichKing-2234** [comment]
you can use `getUserInfoByUid`

**Comment by shashikantdurge** [comment]
I came across this issue. 
And _getUserInfoByUid_ throws 134 error

**Comment by LichKing-2234** [comment]
@shashikantdurge maybe your username is invalid

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
