### ISSUE TITLE
Encryption not working cross platform

### ISSUE THREAD

**Issue by maerlynflagg** [AgoraIO/Flutter-SDK#102]
on app side we using the Agora Flutter SDK.

the channel opener on the other side uses Agora Web SDK or Agora Flutter SDK.

results:

Android App to Web SDK  works fine.

iOS App  to iOS App works fine.

iOS App to Web SDK  or iOS App to Android App is not working.

is there no cross platform support for ios or is this a bug?

**Comment by LichKing-2234** [comment]
Our SDK support these platform, we need more information about your issue.

**Comment by maerlynflagg** [comment]
the Web SDK is from there: https://docs.agora.io/en/Agora%20Platform/downloads?_ga=2.194720041.561163005.1586162754-1291242471.1585573196
we used the code of the given example in this web sdk download.

basically for the app we used the referenced tutorial https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart.

we added only this lines for our use case:

```
    await AgoraRtcEngine.setEncryptionMode('aes-128-xts');
    await AgoraRtcEngine.setEncryptionSecret('ourSecret');
    await AgoraRtcEngine.joinChannel(null, 'ourchannelid', null, 0);
```

**Comment by LichKing-2234** [comment]
I will check it later

**Comment by LichKing-2234** [comment]
@maerlynflagg We have upgraded the SDK to 1.0.10 to fix this problem, you can try again later.

**Comment by maerlynflagg** [comment]
Thank you for the new version. now all is working. :)
