### ISSUE TITLE
I am removing the GeneratedPluginRegistrant.registerWith(flutterEngine); ang get another issue in cloud_firestore

### ISSUE THREAD

**Issue by mahmoudatef925** [AgoraIO/Flutter-SDK#104]
i have same issue using cloud_firestore: ^0.13.4+2
get balck screen then remove GeneratedPluginRegistrant.registerWith(flutterEngine); 
after that i get another issue in transaction in cloud_firestore
please provide me with solution 
thanks in advance

_Originally posted by @mahmoudatef925 in https://github.com/AgoraIO/Flutter-SDK/issues/87#issuecomment-609891483_

**Comment by LichKing-2234** [comment]
pls show the code of your `MainActivity.java`

**Comment by mahmoudatef925** [comment]
package com.solid.firebasechatflutter

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
     GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

**Comment by LichKing-2234** [comment]
if you override `configureFlutterEngine` but forget to add `super.configureFlutterEngine`, you should not comment or remove `GeneratedPluginRegistrant.registerWith(flutterEngine);`

**Comment by LichKing-2234** [comment]
you can refer to our readme

**Comment by mahmoudatef925** [comment]
i update it with 
package com.solid.firebasechatflutter

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
     super.configureFlutterEngine(flutterEngine);
     GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}
but still have black screen

**Comment by LichKing-2234** [comment]
@mahmoudatef925 I see you add `super.configureFlutterEngine(flutterEngine);`, if you do that, the plugins will be registered auto, so you should not add `GeneratedPluginRegistrant.registerWith(flutterEngine);`, It makes all plugins register twice.

**Comment by iNima** [comment]
Hi @LichKing-2234 ,

When I remove `GeneratedPluginRegistrant.registerWith(flutterEngine);` and add `super.configureFlutterEngine(flutterEngine);`, other plugins complain. For example, `shared_preferences` plugin complains with this error:
`MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
My MainActivity code is:
```import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine);
  }
}
```

**Comment by LichKing-2234** [comment]
> Hi @LichKing-2234 ,
> 
> When I remove `GeneratedPluginRegistrant.registerWith(flutterEngine);` and add `super.configureFlutterEngine(flutterEngine);`, other plugins complain. For example, `shared_preferences` plugin complains with this error:
> `MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`
> My MainActivity code is:
> 
> ```
> import io.flutter.embedding.android.FlutterActivity
> import io.flutter.embedding.engine.FlutterEngine
> 
> class MainActivity: FlutterActivity() {
>   override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
>     super.configureFlutterEngine(flutterEngine);
>   }
> }
> ```
> 
> My flutter version is 1.12.13+Hotfix.5 on the stable channel.
> 
> I just checked the `configureFlutterEngine` function in the FlutterActivity class. It might help to fix this issue:
> 
> ```
>    * Hook for subclasses to easily configure a {@code FlutterEngine}, e.g., register
>    * plugins.
>    * <p>
>    * This method is called after {@link #provideFlutterEngine(Context)}.
>    */
>   @Override
>   public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
>     // No-op. Hook for subclasses.
>   }
> ```

I see your MainActivity can't auto-register the plugins, you can find `FlutterEngine.java` and search `registerPlugins` method, make sure engine run it by default.

By the way, after run `flutter channel xxx`, you should run `flutter build` to get the correct Flutter engine of your flutter version.

**Comment by iNima** [comment]
Hi @LichKing-2234 
The `configureFlutterEngine` function in the `FlutterActivity.java` class is a hook for subclasses. It means that any subclasses could implement `configureFlutterEngine` to be called later. So, there is no implementation for that in the superclass upfront. 
I have not seen any other code that used `super.configureFlutterEngine` in this function.
You can see it here as well: https://github.com/flutter/engine/blob/caebc93e0c4bfb8be278cf89a827229340745706/shell/platform/android/io/flutter/embedding/android/FlutterActivity.java#L883
I saw that all Agora example projects have used the old method (onCreate) and it works correctly on Android. Have you tested an example project with the new approach (subclassing FlutterActivity) and see if it works or not. For example, you can add `shared_preferences` plugin as well to the project to see how it works.
Thanks in advance.

**Comment by LichKing-2234** [comment]
@iNima let me see your `FlutterEngine.java`, I think you use the stable version Flutter, but use another version of Flutter engine.

![image](https://user-images.githubusercontent.com/9312526/78866669-69e99e80-7a72-11ea-86bc-cd9d107641ad.png)
![image](https://user-images.githubusercontent.com/9312526/78866695-7968e780-7a72-11ea-8f4a-ddea72201cf6.png)

**Comment by LichKing-2234** [comment]
@iNima Stable Flutter auto register plugins in Flutter engine.
Master Flutter auto register plugins in FlutterActivity.

**Comment by LichKing-2234** [comment]
Master Flutter auto register plugins in FlutterActivity.
![image](https://user-images.githubusercontent.com/9312526/78867025-0318b500-7a73-11ea-98bc-cdcea48e9158.png)

**Comment by iNima** [comment]
Thanks @LichKing-2234 for the explanations.
I checked my `FlutterEngine.java` It is exactly the same as the screenshots you sent me.
Also, it has this code:
```    if (automaticallyRegisterPlugins) {
      registerPlugins();
    }```
So, I'm in stable channel and used the correct version of FlutterEngine.java, right?

**Comment by LichKing-2234** [comment]
@iNima as you said, your version of FlutterEngine maybe correct, you can debug your application,  check the `GeneratedPluginRegistrant.registerWith` method has been executed.

**Comment by iNima** [comment]
@LichKing-2234, I debugged my code.
In the README of this repo you said to use this method to fix the Android black screen. 
When I use this code:
```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    super.configureFlutterEngine(flutterEngine);
  }
}
```
`GeneratedPluginRegistrant.registerWith` is called by FlutterEngine.java and then the above method is called.
After that, this error raised although `GeneratedPluginRegistrant.registerWith` has been called. 
`MissingPluginException(No implementation found for method getAll on channel plugins.flutter.io/shared_preferences)`

I'm using Kotlin by the way.

**Comment by LichKing-2234** [comment]
@iNima Has `registerWith` registered shared_preferences?

**Comment by LichKing-2234** [comment]
@iNima Could you share your  `GeneratedPluginRegistrant`?

**Comment by iNima** [comment]
@LichKing-2234, Yes it does:
```
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      io.agora.agorartcengine.AgoraRtcEnginePlugin.registerWith(shimPluginRegistry.registrarFor("io.agora.agorartcengine.AgoraRtcEnginePlugin"));
      com.example.appsettings.AppSettingsPlugin.registerWith(shimPluginRegistry.registrarFor("com.example.appsettings.AppSettingsPlugin"));
      xyz.luan.audioplayers.AudioplayersPlugin.registerWith(shimPluginRegistry.registrarFor("xyz.luan.audioplayers.AudioplayersPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.camera.CameraPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.connectivity.ConnectivityPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.deviceinfo.DeviceInfoPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.crashlytics.firebasecrashlytics.FirebaseCrashlyticsPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin());
      com.alveliu.flutterfullpdfviewer.FlutterFullPdfViewerPlugin.registerWith(shimPluginRegistry.registrarFor("com.alveliu.flutterfullpdfviewer.FlutterFullPdfViewerPlugin"));
      com.example.flutternativeimage.FlutterNativeImagePlugin.registerWith(shimPluginRegistry.registrarFor("com.example.flutternativeimage.FlutterNativeImagePlugin"));
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
      com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin.registerWith(shimPluginRegistry.registrarFor("com.isvisoft.flutter_screen_recording.FlutterScreenRecordingPlugin"));
      com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(shimPluginRegistry.registrarFor("com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin"));
      com.dooboolab.fluttersound.FlutterSoundPlugin.registerWith(shimPluginRegistry.registrarFor("com.dooboolab.fluttersound.FlutterSoundPlugin"));
      com.fuyumi.flutterstatusbarcolor.flutterstatusbarcolor.FlutterStatusbarcolorPlugin.registerWith(shimPluginRegistry.registrarFor("com.fuyumi.flutterstatusbarcolor.flutterstatusbarcolor.FlutterStatusbarcolorPlugin"));
      carnegietechnologies.gallery_saver.GallerySaverPlugin.registerWith(shimPluginRegistry.registrarFor("carnegietechnologies.gallery_saver.GallerySaverPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
      com.github.rmtmckenzie.nativedeviceorientation.NativeDeviceOrientationPlugin.registerWith(shimPluginRegistry.registrarFor("com.github.rmtmckenzie.nativedeviceorientation.NativeDeviceOrientationPlugin"));
      com.example.native_mixpanel.NativeMixpanelPlugin.registerWith(shimPluginRegistry.registrarFor("com.example.native_mixpanel.NativeMixpanelPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.packageinfo.PackageInfoPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
      com.baseflow.permissionhandler.PermissionHandlerPlugin.registerWith(shimPluginRegistry.registrarFor("com.baseflow.permissionhandler.PermissionHandlerPlugin"));
      com.assetowl.ricoh_theta_flutter_plugin.RicohThetaFlutterPlugin.registerWith(shimPluginRegistry.registrarFor("com.assetowl.ricoh_theta_flutter_plugin.RicohThetaFlutterPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.sensors.SensorsPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.sharedpreferences.SharedPreferencesPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
      fr.g123k.torch_compat.TorchCompatPlugin.registerWith(shimPluginRegistry.registrarFor("fr.g123k.torch_compat.TorchCompatPlugin"));
      name.avioli.unilinks.UniLinksPlugin.registerWith(shimPluginRegistry.registrarFor("name.avioli.unilinks.UniLinksPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
      wakelock.wakelock.WakelockPlugin.registerWith(shimPluginRegistry.registrarFor("wakelock.wakelock.WakelockPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.webviewflutter.WebViewFlutterPlugin());
  }
}
```

**Comment by LichKing-2234** [comment]
@iNima I will add this lib and test it later, can you check is only this lib not worked?

**Comment by iNima** [comment]
Thanks @LichKing-2234, I'm not sure about other libraries. I can't remove shared_preferences easily and check others since there are a lot of code depends on the shared_preferences in my project. Sorry about that.

**Comment by mahmoudatef925** [comment]
> @mahmoudatef925 I see you add `super.configureFlutterEngine(flutterEngine);`, if you do that, the plugins will be registered auto, so you should not add `GeneratedPluginRegistrant.registerWith(flutterEngine);`, It makes all plugins register twice.

i get same error in transaction in cloud_firestore

**Comment by LichKing-2234** [comment]
@iNima I add `shared_preferences: ^0.5.6+3` to our example, it works fine.
These is my flutter info:
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.4 19E266, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.5 at /Users/lxh/Library/flutter
    • Framework revision 27321ebbad (4 months ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

**Comment by LichKing-2234** [comment]
@iNima I just add this method, any I missed?
```
_incrementCounter() async {
    SharedPreferences prefs = await SharedPreferences.getInstance();
    int counter = (prefs.getInt('counter') ?? 0) + 1;
    print('Pressed $counter times.');
    await prefs.setInt('counter', counter);
  }
```

**Comment by iNima** [comment]
Hi @LichKing-2234 , 
What you added is correct but have you migrated to v2 embedded on Android?
When we migrate to v2 embedded we need to change the MainActivity class to use this method:

```
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine

class MainActivity: FlutterActivity() {
  override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
    GeneratedPluginRegistrant.registerWith(flutterEngine);
  }
}
```
By this configuration the Android shows black screen with Agora library.
In the README you said to remove
`GeneratedPluginRegistrant.registerWith(flutterEngine);`
and replace it with:
`super.configureFlutterEngine(flutterEngine);`
When we do this the shared_preferences does not work.

All these issues happen when the project has been migrated to v2 embedded.

**Comment by LichKing-2234** [comment]
@iNima I use v2 embedded, what is your shared_preferences plugin version?

**Comment by iNima** [comment]
@LichKing-2234 My shared_preferences version is 0.5.6+3
I used this guide for migrating to v2 embedded:
https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects

**Comment by LichKing-2234** [comment]
@iNima you can see our new readme, switch another channel of flutter, and try again.

**Comment by iNima** [comment]
@LichKing-2234 Could you please write here your MainActivity code of your v2 embedded project?
What is your flutter channel?

**Comment by LichKing-2234** [comment]
@iNima this is my MainActivity, suggest beta channel
```
package io.agora.agorartcengineexample;

import io.flutter.embedding.android.FlutterActivity;

public class MainActivity extends FlutterActivity {

}
```

**Comment by iNima** [comment]
@LichKing-2234 , My project was on the stable channel.
I changed it to the beta channel and it works correctly. 
By the way, I'd prefer to stay on the stable channel but it seems that at the moment we don't have any other choice and we have to use the beta channel.
We'll need to do a thorough regression test to make sure that the app would work as expected with the beta channel.
Thanks a lot for your effort on this matter, mate! :)

**Comment by mahmoudatef925** [comment]
dear @LichKing-2234 can you check my issue  
Channel version and channel 
Flutter 1.12.13+hotfix.9 • channel stable
used packages 

  google_sign_in: ^4.3.0

  shared_preferences: ^0.5.6+3

  cloud_firestore: ^0.13.4+2

  firebase_storage: ^3.1.5

  get_it: ^4.0.1

  provider: ^4.0.4

  http: ^0.12.0+4 

  url_launcher: ^5.4.2

  logger: ^0.8.3

  flutter_sound: ^3.0.0

  cached_network_image: ^2.0.0

  firebase_messaging: ^6.0.13

  path_provider: ^1.6.5

  permission_handler: ^4.4.0
  
  intl: ^0.16.0

  image_picker: ^0.6.4
  
  animated_text_kit: ^2.0.0
  
  emoji_picker: ^0.1.0
  
  agora_rtc_engine: 1.0.10
  # matrix_gesture_detector: ^0.1.0
  
  flutter_local_notifications: ^1.4.0

  firebase_analytics: ^5.0.11

  auto_size_text: ^2.1.0

when i replace  GeneratedPluginRegistrant.registerWith(flutterEngine); with super.configureFlutterEngine(flutterEngine);
i get transaction error 
when i keep   GeneratedPluginRegistrant.registerWith(flutterEngine); 
get black screen

**Comment by iNima** [comment]
@mahmoudatef925 Based on what @LichKing-2234 and I discussed and found out, you need to switch to the `beta` channel to be able to use this plugin alongside other plugins and make it working on the Android app.

**Comment by mahmoudatef925** [comment]
it works fine !
thanks @iNima and @LichKing-2234
