### ISSUE TITLE
播放半音url

### ISSUE THREAD

**Issue by davewang** [AgoraIO/Flutter-SDK#105]
播放半音 startAudioMixing
不能播放 url 的 mp3资源吗？不支持？

**Comment by LichKing-2234** [comment]
支持的，你这边有什么问题么

**Comment by davewang** [comment]
有的连接不能播放，可能是http 头信息带的不对，这个不能自定义带头信息吗？

**Comment by LichKing-2234** [comment]
目前不支持传header，选择不需要header的链接吧
