### ISSUE TITLE
Api cameras

### ISSUE THREAD

**Issue by Arcrueid** [AgoraIO/Flutter-SDK#106]
Is there a possibility to detect which is the active camera?

I need to start with the rear camera, and for now I am running await AgoraRtcEngine.switchCamera (); when starting and ending the call.

But I think it is not the best solution.

**Comment by LichKing-2234** [comment]
Our SDK uses the front camera by default, you can use `switchCamera` now.
We will upgrade the flutter SDK in Q2, then you can use [setCameraCapturerConfiguration](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ab241578c1baf67e68bcabe1a07eb3363)

**Comment by LichKing-2234** [comment]
finished
