### ISSUE TITLE
删除GeneratedPluginRegistrant.registerWith(flutterEngine)后，别的插件就不能用了。

### ISSUE THREAD

**Issue by qyxm521** [AgoraIO/Flutter-SDK#108]
flutter doctor -v
 Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.6 18G2022, locale zh-Hans-CN)
    • Flutter version 1.12.13+hotfix.9 at /Users/apple/development/flutter
    • Framework revision f139b11009 (8 天前), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

```
MainActivity 内容如下：
import io.flutter.embedding.android.FlutterActivity

class MainActivity: FlutterActivity() {
}

```

agora 版本是1.0.10
multi_image_picker:4.6.5+rc.1 不能用了。

**Comment by LichKing-2234** [comment]
断点看下plugin注册了没有，你的MainActivity没啥问题

**Comment by LichKing-2234** [comment]
不同的flutter版本注册逻辑可能不太一样

**Comment by qyxm521** [comment]
你用的是哪个版本啊?

**Comment by qyxm521** [comment]
如果不删除GeneratedPluginRegistrant.registerWith(flutterEngine)这行的话，插件是没问题的，但是视频通话会黑屏。

**Comment by LichKing-2234** [comment]
• Flutter version 1.15.21 at /Users/lxh/Library/flutter
• Framework revision e2b4edd286 (4 weeks ago), 2020-03-13 02:46:02 -0400
• Engine revision d7a00b8b09
• Dart version 2.8.0 (build 2.8.0-dev.14.0 eb9c26bd37)

**Comment by qyxm521** [comment]
好的，谢谢，经测试删除GeneratedPluginRegistrant.registerWith(flutterEngine)后，Channel： master、dev和beta 是正常的，但是stable 有的插件不生效，有什么解决办法吗？

**Comment by LichKing-2234** [comment]
@qyxm521 具体哪些插件，我用stable貌似没有遇到哪个不能用

**Comment by LichKing-2234** [comment]
Flutter新版就是设计成这样，自动加载插件，如果有问题，应该就是具体插件没适配好
![image](https://user-images.githubusercontent.com/9312526/78967226-72a2a900-7b34-11ea-9025-a67356bb80af.png)

**Comment by qyxm521** [comment]
multi_image_picker:4.6.5+rc.1不能用，能看下你的MainActivity吗？另外，我用stable重新生成的项目是带GeneratedPluginRegistrant.registerWith(flutterEngine); 这一行的，其他的channel不带。
![image](https://user-images.githubusercontent.com/9931555/78967320-b8f80800-7b34-11ea-9fd9-86398fd96688.png)

**Comment by LichKing-2234** [comment]
我是注释了`GeneratedPluginRegistrant.registerWith(flutterEngine);`
![image](https://user-images.githubusercontent.com/9312526/78967493-3459b980-7b35-11ea-84cb-eba094fbf2c7.png)

**Comment by qyxm521** [comment]
注释掉的话，视频通话不黑屏，但是插件就会出错。

**Comment by LichKing-2234** [comment]
@qyxm521 你这边是只有这个插件有问题么，我这边add测试下，可能是这个插件初始化的时候context有点问题

**Comment by qyxm521** [comment]
谢谢，是的，我这暂时只有这一个插件有问题。

**Comment by LichKing-2234** [comment]
@qyxm521 我这边下载库有点问题，你断点看看这个插件注册的时候，activity应该是没有
![image](https://user-images.githubusercontent.com/9312526/78969375-65d48400-7b39-11ea-87fc-2d5b6a25052d.png)

**Comment by qyxm521** [comment]
![image](https://user-images.githubusercontent.com/9931555/78970467-f4e29b80-7b3b-11ea-898c-3f3a261d725b.png)
在这debug吗？

**Comment by LichKing-2234** [comment]
是的

**Comment by LichKing-2234** [comment]
是的，看下registrar.acvitity()和registrar.context()

**Comment by LichKing-2234** [comment]
建议不要使用stable版本，iOS的platformview也有内存泄漏

**Comment by qyxm521** [comment]
好的，已经切换到beta频道了，感谢回复。
