### ISSUE TITLE
Screen sharing functionality

### ISSUE THREAD

**Issue by kashifzahid** [AgoraIO/Flutter-SDK#109]
Is there a way to share screen (Like in skype) ?

**Comment by LichKing-2234** [comment]
Flutter SDK doesn't support the share screen, can only receive the remote share screen.

**Comment by kashifzahid** [comment]
is there a way we can share screen on flutter during a video call?

**Comment by LichKing-2234** [comment]
@kashifzahid You can fork our SDK, And add share screen code in Android or iOS.
Flutter SDK is a community version, welcome to contribute your code.

**Comment by plutoless** [comment]
to be more specific, you need to follow this guide to support screenshare using custom capture
https://github.com/AgoraIO/Advanced-Video/tree/master/Android/sample-switch-external-video
https://github.com/AgoraIO/Advanced-Video/tree/master/iOS%26macOS/Agora-Screen-Sharing

it's not a simple API call so you have to do it yourself on native side

**Comment by faizanrafiq7** [comment]
How can we share one screen on another just to display. Using flutter

**Comment by LichKing-2234** [comment]
@faizanrafiq7 what means just to display? render remote video stream which creates by share screen?

**Comment by faizanrafiq7** [comment]
Whatever is on my phone is displaying on another android.  Kkke screen mirroring

**Comment by plutoless** [comment]
@faizanrafiq7  we have explained in above comments

**Comment by faizanrafiq7** [comment]
Ohh Thanks a lot i didn't catch that.

**Comment by abdullah951** [comment]
@plutoless does agora flutter webrtc package provides the above features?

**Comment by plutoless** [comment]
closed. reopen if you believe the issue still exists

**Comment by boucoding** [comment]
any updates?

**Comment by ismaelAbogabal** [comment]
2

**Comment by mohadel92** [comment]
> Is there a way to share screen (Like in skype) ?

did you find any info regarding this issue?

**Comment by vishalsingh17-web2** [comment]
Does anyone know how to implement this in android using flutter...

**Comment by mahboobahmed6577** [comment]
anyone implemented this screen sharing ?

**Comment by SerdarYildiz06** [comment]
Any news?

**Comment by mahboobahmed6577** [comment]
Nope

**Comment by amsyary** [comment]
anything.?

**Comment by princeflutterdev** [comment]
> to be more specific, you need to follow this guide to support screenshare using custom capture https://github.com/AgoraIO/Advanced-Video/tree/master/Android/sample-switch-external-video https://github.com/AgoraIO/Advanced-Video/tree/master/iOS%26macOS/Agora-Screen-Sharing
> 
> it's not a simple API call so you have to do it yourself on native side

i am try this nut i am getting duplicate classes errror ,
 becuase the libarary is used from both flutte and native side .

**Comment by 1AhmedYasser** [comment]
Agora now supports Screen Sharing for flutter & react native

Flutter: `https://docs.agora.io/en/Video/screensharing_flutter?platform=Flutter`
React Native: `https://docs.agora.io/en/Video/screensharing_react_native?platform=React%20Native`

Have Fun

**Comment by octavio-talent** [comment]
I am getting this error, agora_rtc_engine: ^5.3.0

[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: PlatformException(ErrorCode.NotSupported, null, null, null)
#0      RtcEngineImpl.getScreenShareHelper (package:agora_rtc_engine/src/impl/rtc_engine_impl.dart:68:7)

**Comment by devsideal** [comment]
@1AhmedYasser , I'm unable to screen share in the flutter iOS app, In the documentation, there is no guidance for iOS configuration, 
Although I have followed the same instruction as given for native iOS `https://docs.agora.io/en/video-calling/develop/product-workflow?platform=ios#handle-the-system-logic` 
But still, No luck.

**Comment by devsideal** [comment]
> @1AhmedYasser , I'm unable to screen share in the flutter iOS app, In the documentation, there is no guidance for iOS configuration, Although I have followed the same instruction as given for native iOS `https://docs.agora.io/en/video-calling/develop/product-workflow?platform=ios#handle-the-system-logic` But still, No luck.

Related to:  https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/issues/607
