### ISSUE TITLE
Audience view when broadcasting from android device.

### ISSUE THREAD

**Issue by Aliharu** [AgoraIO/Flutter-SDK#11]
When you start a Broadcast view on android the Audience views are mirrored and zoomed in.

When using Broadcast views on IOS the audience views are mirrored but not zoomed in.

This looks like a bug as the views should be the same between devices when Broadcasting to an audience.  And the views shouldn't change based on the device broadcast.

Edit: Upon further testing this bug happens when you stream from any device.  Not just IOS.

**Comment by plutoless** [comment]
@Aliharu  could you pls upload screenshots to help me understand how it's zoomed in?

**Comment by Aliharu** [comment]
![Screenshot_20190610-082512_Hallo](https://user-images.githubusercontent.com/6546285/59202512-e31a1b80-8b59-11e9-962d-f396c654e52d.jpg)
![IMG_0005](https://user-images.githubusercontent.com/6546285/59202513-e31a1b80-8b59-11e9-82ab-39554009c0ae.PNG)

**Comment by Aliharu** [comment]
The bug can be recreated on your quickstart example by setting AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
the zoom happens on the audience view.

**Comment by PRWrl** [comment]
If the broadcaster is sending video in landscape mode, and the audience is rendering video in `VideoRenderMode.hidden` in portrait, the left and right side of video will be clipped and causes 'zoom in'.

You can change `VideoRenderMode` to `Fit` for audience to avoid the content clip, or change `VideoOutputOrientationMode` to `FixedPortrait` for broadcaster  to force to sending portrait video stream.

See more detail info about `VideoOutputOrientationMode ` : https://docs.agora.io/en/Video/rotation_guide_android?platform=Android

**Comment by Aliharu** [comment]
This bug happens even if both phones are in portrait mode.

I tried to set the Video Output Orientation using

```
      var videoEncoderConfig = VideoEncoderConfiguration();
      videoEncoderConfig.orientationMode = VideoOutputOrientationMode.FixedPortrait;
      AgoraRtcEngine.setVideoEncoderConfiguration(videoEncoderConfig); 
```

The zoom bug is still there.

**Comment by plutoless** [comment]
If all your other devices work fine, there's a chance that your Galaxy S5 does not support the resolution you set. Could you pls help provide the log file for the device which is not working, so that this can be confirmed?

**Comment by rlee1990** [comment]
@Aliharu How did you get your view to look this way I can't get mine to be full screen at all

**Comment by rlee1990** [comment]
Nevermind @Aliharu

**Comment by tanapop** [comment]
> ![Screenshot_20190610-082512_Hallo](https://user-images.githubusercontent.com/6546285/59202512-e31a1b80-8b59-11e9-962d-f396c654e52d.jpg)
> ![IMG_0005](https://user-images.githubusercontent.com/6546285/59202513-e31a1b80-8b59-11e9-82ab-39554009c0ae.PNG)
> 
> The top is the audience view and the bottom is the broadcaster view.

Hi @Aliharu do you have github or guideline for this screen

**Comment by LichKing-2234** [comment]
could you pls share your code about render mode and video encoder config?
