### ISSUE TITLE
1.0.10通话接通后停在第一画面，不实时传输

### ISSUE THREAD

**Issue by see-sea** [AgoraIO/Flutter-SDK#111]
0.9.7没这个问题

**Comment by LichKing-2234** [comment]
@see-sea 有更详细的信息么

**Comment by see-sea** [comment]
没有，没有报错，能看到自己的摄像头画面，对方的不管是安卓机还是iOS都不动

**Comment by LichKing-2234** [comment]
我们的demo你可以测试下

**Comment by see-sea** [comment]
xr 闪退，切换到 beta channel也不行

**Comment by see-sea** [comment]
xr无法通过flutter run 安装，xcode -> product-> run之后报
dyld: Library not loaded: @rpath/Flutter.framework/Flutter
  Referenced from: /private/var/containers/Bundle/Application/B44E2268-FA5A-4AFE-9EA9-87B264496DC8/Runner.app/Runner
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/B44E2268-FA5A-4AFE-9EA9-87B264496DC8/Runner.app/Frameworks/Flutter.framework/Flutter: code signature invalid for '/private/var/containers/Bundle/Appli(lldb)

**Comment by see-sea** [comment]
可以加下微信或qq？新版的一直卡着没法调试，倒退版本又不现实

**Comment by see-sea** [comment]
我微信haicheng05，谢谢

**Comment by LichKing-2234** [comment]
@see-sea 你测试的是你的项目还是我们的demo？我们的demo你有试过么

**Comment by see-sea** [comment]
你们demo

**Comment by LichKing-2234** [comment]
代码有做改动么，我们测试demo是好的，还有rtc log也发下

**Comment by LichKing-2234** [comment]
channel name取个特别的，我这边方便查后台

**Comment by see-sea** [comment]
好的，稍等

**Comment by see-sea** [comment]
没事了，谢谢
