### ISSUE TITLE
Raw Video Data

### ISSUE THREAD

**Issue by anhkhoa45** [AgoraIO/Flutter-SDK#113]
I need to pre-process the video frames before streaming them.
Is there any API for [Raw Video Data processing](https://docs.agora.io/en/Video/raw_data_video_android?platform=Android) in Flutter-SDK? or another possible way?

**Comment by LichKing-2234** [comment]
We wouldn't provide these API in Flutter-SDK,  because it will reduce performance, you can fork our SDK,  add it in Android and iOS code.

**Comment by anhkhoa45** [comment]
@LichKing-2234 Thanks for your reply
