### ISSUE TITLE
NullPointerException when going back online

### ISSUE THREAD

**Issue by silversquall** [AgoraIO/Flutter-SDK#115]
With agora_rtc_engine: 1.0.5 

**And following init** 

await AgoraRtcEngine.enableVideo();
await AgoraRtcEngine.disableAudio();
await AgoraRtcEngine.enableWebSdkInteroperability(true);
AgoraRtcEngine.setParameters(
        '{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}');

await AgoraRtcEngine.joinChannel(null, widget.channelName, "something", 0);

**i stumbled upon the following issue** 

1. the user creates his channel
2. once joined the user goes offline
3. then the user goes online
4. Nullpointer exception appears in the logs 
5. it doesnt seem to affect the streaming session.

I/flutter (20301): [NetworkConnectivity] network status updated to ConnectivityResult.wifi
I/flutter (27793): [CallPage] onConnectionStateChanged with state = 3 & reason = 1 (MY Own log)
E/RtcEngine(27793): onEvent: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object java.util.HashMap.put(java.lang.Object, java.lang.Object)' on a null object reference

more details in attachement
[stackTrace.txt](https://github.com/AgoraIO/Flutter-SDK/files/4476745/stackTrace.txt)

**Comment by LichKing-2234** [comment]
it crash?

**Comment by plutoless** [comment]
@LichKing-2234  i think it does not crash as he mentioned stream is not affected.

**Comment by silversquall** [comment]
yes no crash

**Comment by LichKing-2234** [comment]
you may ignore this log before we find it's cause
