### ISSUE TITLE
Set and change audio input settings

### ISSUE THREAD

**Issue by iNima** [AgoraIO/Flutter-SDK#116]
Hi @LichKing-2234 , @plutoless 

I need to be able to switch between available audio inputs similar to the `Advanced settings` in the sample web app:

![Screen Shot 2020-04-15 at 12 48 26 pm](https://user-images.githubusercontent.com/4446420/79293574-7315b800-7f17-11ea-8037-a321b7f5f867.png)

Is it possible to implement that with this library in the mobile app?

Thanks
Nima

**Comment by LichKing-2234** [comment]
@iNima mobile not support this

**Comment by iNima** [comment]
Thanks @LichKing-2234

**Comment by LichKing-2234** [comment]
I will close this issue because it is not active. if there are still problems, you can reopen this issue.
