### ISSUE TITLE
D/BufferQueueProducer(17421): SurfaceTexture-42-17421-0 cancelBuffer: slot 1

### ISSUE THREAD

**Issue by sathishkumarjktech** [AgoraIO/Flutter-SDK#119]
D/BufferQueueProducer(17421): SurfaceTexture-42-17421-0 cancelBuffer: slot 1

Why this error coming after video preview started every sec and phone getting Hang

**Comment by LichKing-2234** [comment]
same as https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/97#issuecomment-616056382

**Comment by sathishkumarjktech** [comment]
why this happenig D/BufferQueueProducer(17421): SurfaceTexture-42-17421-0 cancelBuffer: slot 1
continuously
