### ISSUE TITLE
channel history : API to know when and who joined the channel

### ISSUE THREAD

**Issue by silversquall** [AgoraIO/Flutter-SDK#121]
Hi,

I have 4 questions/remarks related to channel history

1) regarding the callback: static void Function(int uid, int elapsed) **onUserJoined**; 
The doc says :  

> /// Communication profile: This callback notifies the app when another user joins the channel. If other users are already in the channel, the SDK also reports to the app on the existing users.
 
In which order are the callbacks called ?
(Seems to be from most recent to older user to join the channel when trying on my side)

2) I see you are using some "elapsed" param in many methods but it's meaning is not clear.
for instance what is it's meaning in Function(int uid, int elapsed) **onUserJoined**;  ?

3) Are you planning to provide some sort of channel history ? (when/who joined and left the chanel)

4) would be great to have 

- :another event containing all current users in the channel (let's say onAllUsersJoined)

- then current onUserJoined callback only triggered for next users

thx.

**Comment by plutoless** [comment]
1. the order is not guaranteed to be the order every user joins the channel precisely
2. it means the elapse time when this user joins since you join the channel
3. we have a backend notification service, but it's for internal use only for now. try talking to sales
4. understand, currently flutter sdk is built upon native sdk, we can't change native sdk behavior. i'll see if i can take this to our PM for future improvements

**Comment by silversquall** [comment]
Just to clarify

1) "the order is not guaranteed to be the order every user joins the channel precisely"
 
I guess the users are somehow sorted on your side and when I Join the channel   you just loop on the list and for each users you fire an event.

Can you at least tell me how the list is ordered on your side and if you put some delay before fireing the events ?

Please let me know, this is critical for me.

2) "it means the elapse time when this user joins since you join the channel" -> what if users were already on the channel before I join ?

3) & 4)  would help a lot.

thx.

**Comment by plutoless** [comment]
1. current design is we notify the event as soon as we find a user joins the channel. so we don't really record the order.
2. you will receive the callback, and the elapse is the time you receive the callback since you join the channel

**Comment by silversquall** [comment]
To verify your point 2 : ""it means the elapse time when this user joins since you join the channel"

I performed the following scenario:

1) user1 is first to join the channel
2) wait some time
3) user2 joins the channel
4) wait some time
5) user3 joins the channel
6) user3 leaves the channel for about 20seconds (the other users stay in the channel) 
7) user3 joins the channel again

//////////////////////////////

**Below logs from user3 point of view**

**step 5: user3 joins for the first time**:

onJoinChannelSuccess: uid: user3, elapsed: 692. print date = 2020-04-29 18:52:43.943418
userJoined: user2, elapsed: 704, "print date = 2020-04-29 18:52:43.980006
userJoined: user1, elapsed: 759, "print date = 2020-04-29 18:52:44.025787

--> user1's elapsed > user2's elapsed 

**step 7: user3 joins the channel again**:

onJoinChannelSuccess: uid: user3, elapsed: 728. print date = 2020-04-29 18:53:08.065049
userJoined: user1, elapsed: 742, "print date = 2020-04-29 18:53:08.117793
userJoined: user2, elapsed: 752, "print date = 2020-04-29 18:53:08.120672

-->now user2's elapsed > user1's elapsed 

i would expect to always have user1's  elapsed > user2's elapsed after joining the channel again.

**My business critical need** : determine the order on which users's joined the channel.

I have the impression the lib is unreliable for that, can you please help me know if it's worth investing more time on it ? 

thx.

**Comment by plutoless** [comment]
@silversquall the elapsed time is the time for your client side, it's not representing the unique shared timestamp across different devices, so the order can be different on different devices depending on their network status. as i said, our sdk does not guarantee the join order. may i know the actual business scenario you are about to accomplish? if the order is really important for you, the suggested approach is to set up a server yourself and ensure client send a request to you to record its joining timestamp before it starts joining rtc.
