### ISSUE TITLE
Agora encryption is not working

### ISSUE THREAD

**Issue by NarHakobyan** [AgoraIO/Flutter-SDK#127]
Hi guys, we are trying to enable agora encryption but we got black/blue screens, support answered us that the problem comes from flutter, so SDK is not encrypting.
**here is code snipped which we used.** testing device: Samsung Galaxy S10
```dart
    await AgoraRtcEngine.create(...);
    await AgoraRtcEngine.setEncryptionMode('aes-128-ecb');
    await AgoraRtcEngine.setEncryptionSecret('ourSecret');
```
also we used other encryption modes too

**Comment by LichKing-2234** [comment]
what version of the plugin did you add? We fix iOS encryption bug in v1.0.10

**Comment by NarHakobyan** [comment]
I am using `agora_rtc_engine: ^1.0.10`

**Comment by LichKing-2234** [comment]
Android or iOS？

**Comment by NarHakobyan** [comment]
I am testing in my real device (Samsung Galaxy S10) also enabled production for agora, so we are using token + appid combination

**Comment by LichKing-2234** [comment]
what platform is another device

**Comment by NarHakobyan** [comment]
Web, (latest chrome)

**Comment by LichKing-2234** [comment]
has web set the same config?

**Comment by NarHakobyan** [comment]
yeah, the same one, also here is support answer

![image](https://user-images.githubusercontent.com/1781506/80577887-af1d4280-8a18-11ea-8607-229a132ef78a.png)

**Comment by LichKing-2234** [comment]
I will test it later.

**Comment by LichKing-2234** [comment]
It works for me. Could you pls share your web code?

**Comment by NarHakobyan** [comment]
here is dart code
```dart
    await AgoraRtcEngine.create(...);
    await AgoraRtcEngine.setEncryptionMode('aes-128-ecb');
    await AgoraRtcEngine.setEncryptionSecret('ourSecret');

    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.enableAudio();
    await AgoraRtcEngine.joinChannel(
      widget.videoCallTokenInfo.token,
      widget.videoCallTokenInfo.room,
      null,
      widget.videoCallTokenInfo.identity,
    );
```

and here is web

```typescript
       const client = this.agoraService.createClient(
            {
                codec: Utils.isSafari() ? 'h264' : 'vp8',
                mode: 'rtc',
            },
            true,
        );
        client.setEncryptionMode('aes-128-ecb');
        client.setEncryptionSecret('ourSecret');
```

and then calling startCall function

```typescript
    startCall({ token, room, identity }): void {
        this.agoraService.client.join(
            token,
            room,
            identity,
            (uid) => {
                this.localStream = this.agoraService.createStream({
                    streamID: uid,
                    audio: true,
                    cameraId: null,
                    microphoneId: null,
                    video: true,
                    screen: false,
                });

            },
            (err) => {
                console.error('Join channel failed', err);
            },
        );
    }

```

**Comment by LichKing-2234** [comment]
Where is `client.init` on the web?

**Comment by NarHakobyan** [comment]
we are using ngx-agora and createClient function inits itself, also currently all infrastructure is working good, it's not working only when I am enabling encryption

**Comment by LichKing-2234** [comment]
could you share the code of `this.agoraService.createClient`?

**Comment by NarHakobyan** [comment]
it's open-source lib, here is the link
https://github.com/drew-thompson/ngx-agora/blob/master/projects/ngx-agora/src/lib/ngx-agora.service.ts#L80

**Comment by LichKing-2234** [comment]
I use our web SDK the same version as ngx-agora, and it works for me.

**Comment by LichKing-2234** [comment]
could you try our demo and add encryption code?

**Comment by NarHakobyan** [comment]
We tested encryption in all web browsers in web and mobile, so the problem comes from agora flutter sdk, maybe it's not supporting token and encryption together

**Comment by LichKing-2234** [comment]
I mean you can use our flutter and web demo, add the encryption code, then test them, it works for me.

**Comment by plutoless** [comment]
@NarHakobyan could you pls provide a channel name and time which you used to join and verified the encryption feature to be not working. we can check our backend to see what could be wrong.

**Comment by NarHakobyan** [comment]
Hi dear @plutoless, sure here is channel name `cf4b11b0-8994-11ea-8004-1b8552d7be8f` and approximately date was 2020-04-29

**Comment by LichKing-2234** [comment]
> I mean you can use our flutter and web demo, add the encryption code, then test them, it works for me.

@NarHakobyan Have you try this?

**Comment by plutoless** [comment]
@NarHakobyan i have checked the backend, it seems your web client is calling encryption api properly while android not. i think sth is wrong with your flutter setup, could you pls double check? as we have verified using our own demo and it's working.

**Comment by NarHakobyan** [comment]
@plutoless I am using the same code from example but with production, so we are not using only APP_ID also using token

**Comment by plutoless** [comment]
i don't think so... token should only affect your channel join, as long as you can join the channel successfully it should not affect your rtmp streaming

**Comment by plutoless** [comment]
i don't think so... token should only affect your channel join, as long as you can join the channel successfully it should not affect your rtmp streaming

**Comment by NarHakobyan** [comment]
I can send full code from mobile, if it will help

**Comment by plutoless** [comment]
yes pls. we can try out

**Comment by NarHakobyan** [comment]
```dart

  @override
  void initState() {
    super.initState();
    WidgetsBinding.instance.addObserver(this);
    socketState.on('cancel-video-call', cancelVideoCallEvent);
    // initialize agora sdk
    initialize();
  }

  @override
  void dispose() {
    // clear users
    _users.clear();
    threadsState.newCreatedThread = null;
    // destroy sdk
    AgoraRtcEngine.leaveChannel();
    AgoraRtcEngine.destroy();
    socketState.off('cancel-video-call', cancelVideoCallEvent);
    super.dispose();
  }

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    //TODO fix bug when close app with muted settings open setstate;
    if (state == AppLifecycleState.paused ||
        state == AppLifecycleState.inactive ||
        state == AppLifecycleState.detached) {
      if (!videoCallMuted) {
        AgoraRtcEngine.muteLocalVideoStream(true);
        videoCallMuted = true;
      }
      if (!muted) {
        AgoraRtcEngine.muteLocalAudioStream(true);
        muted = true;
      }
    }
    if (state == AppLifecycleState.resumed) {
      if (videoCallMuted) {
        AgoraRtcEngine.muteLocalVideoStream(false);
        videoCallMuted = false;
      }
      if (muted) {
        AgoraRtcEngine.muteLocalAudioStream(false);
        muted = false;
      }
    }
  }

  void cancelVideoCallEvent(data) {
    _onCallEnd(context);
  }

  Future<void> initialize() async {
    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
    await AgoraRtcEngine.setParameters(
        '''{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}''');
  }

  /// Create agora sdk instance and initialize
  Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create('78ce6db18fc24e8b8835a4b18644a76a');
    await AgoraRtcEngine.setEncryptionMode('aes-128-ecb');
    await AgoraRtcEngine.setEncryptionSecret('ourSecret');

    await PermissionHandler().requestPermissions([PermissionGroup.camera]);

    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.enableAudio();
    await AgoraRtcEngine.joinChannel(
      widget.videoCallTokenInfo.token,
      widget.videoCallTokenInfo.room,
      null,
      widget.videoCallTokenInfo.identity,
    );
  }

  /// Add agora event handlers
  void _addAgoraEventHandlers() {
    AgoraRtcEngine.onError = (code) {
      setState(() {
        final info = 'onError: $code';
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onJoinChannelSuccess = (
      String channel,
      int uid,
      int elapsed,
    ) {
      setState(() {
        final info = 'onJoinChannel: $channel, uid: $uid';
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onLeaveChannel = () {
      setState(() {
        _infoStrings.add('onLeaveChannel');
        _users.clear();
      });
    };

    AgoraRtcEngine.onUserJoined = (int uid, int elapsed) {
      setState(() {
        final info = 'userJoined: $uid';
        _infoStrings.add(info);
        _users.add(uid);
      });
    };

    AgoraRtcEngine.onUserOffline = (int uid, int reason) {
      setState(() {
        final info = 'userOffline: $uid';
        _infoStrings.add(info);
        _users.remove(uid);
      });
    };

    AgoraRtcEngine.onFirstRemoteVideoFrame = (
      int uid,
      int width,
      int height,
      int elapsed,
    ) {
      setState(() {
        final info = 'firstRemoteVideo: $uid ${width}x $height';
        _infoStrings.add(info);
      });
    };
  }

  /// Helper function to get list of native views
  List<Widget> _getRenderViews() {
    final List<AgoraRenderWidget> list = [
      AgoraRenderWidget(0, local: true, preview: true),
    ];
    _users.forEach((int uid) => list.add(AgoraRenderWidget(uid)));
    return list;
  }
```

**Comment by LichKing-2234** [comment]
@NarHakobyan run createClient, but the client is initing, you should setEncryptionMode after onSuccess callback
```
const client = this.agoraService.createClient(
            {
                codec: Utils.isSafari() ? 'h264' : 'vp8',
                mode: 'rtc',
            },
            true,
        );
        client.setEncryptionMode('aes-128-ecb');
        client.setEncryptionSecret('ourSecret');
```

```
 createClient(
    config: ClientConfig,
    autoInitializing: boolean = true,
    onSuccess?: () => void,
    onFailure?: (error: Error) => void
  ): AgoraClient {
    this.client = this.AgoraRTC.createClient(config);
    if (autoInitializing) {
      this.init(this.config.AppID, onSuccess, onFailure);
    }
    return this.client;
  }
```

**Comment by NarHakobyan** [comment]
@LichKing-2234 I have tried that approach also

**Comment by LichKing-2234** [comment]
@NarHakobyan By the way, if you call leaveChannel, you should setEncryptionMode again.

**Comment by LichKing-2234** [comment]
I have tried your code, if setEncryptionMode after onSuccess callback, it worked

**Comment by NarHakobyan** [comment]
but where is onSuccess callback in flutter?

**Comment by NarHakobyan** [comment]
I am sure it's a problem of flutter, I have tested web encryption in all browsers, all worked but flutter, it's showing a blue and black screen, also added onSuccess (in web) but the same

**Comment by NarHakobyan** [comment]
```dart
            this.agoraService.createClient(
                {
                    codec: Utils.isSafari() ? 'h264' : 'vp8',
                    mode: 'rtc',
                },
                true,
                // eslint-disable-next-line no-console
                () => {
                    console.log('create is created');
                    this.agoraService.client.setEncryptionMode('aes-128-ecb');
                    this.agoraService.client.setEncryptionSecret('ourSecret');
                },
                () => console.error("error client isn't created"),
            );
```

**Comment by LichKing-2234** [comment]
is it worked flutter with flutter? I think web encryption failed.

**Comment by NarHakobyan** [comment]
can you please check this channel? `41a88f28-fb3e-4ddb-a2dd-4099adc61e7e`

**Comment by NarHakobyan** [comment]
@LichKing-2234 @plutoless any new guys? 😨 this is a very important part
![image](https://user-images.githubusercontent.com/1781506/83407301-7e6a6780-a421-11ea-8960-12527780331b.png)

**Comment by shu8** [comment]
Hi, I'm not sure if this is your problem, but it might be worth a try!

The Flutter documentation says to call `setEncryptionSecret` *before* `setEncryptionMode` (see https://github.com/Meherdeep/agora-flutter-documentation#setencryptionmode), so you could try changing the code from [your comment](https://github.com/AgoraIO/Flutter-SDK/issues/127#issuecomment-624077234) to:

```
/// Create agora sdk instance and initialize
Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create('...');
    await AgoraRtcEngine.setEncryptionSecret('ourSecret');
    await AgoraRtcEngine.setEncryptionMode('aes-128-ecb');

    await PermissionHandler().requestPermissions([PermissionGroup.camera]);

    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.enableAudio();
    await AgoraRtcEngine.joinChannel(
      widget.videoCallTokenInfo.token,
      widget.videoCallTokenInfo.room,
      null,
      widget.videoCallTokenInfo.identity,
    );
  }
```

I'm not sure if it does actually make a difference but could be worth a try!

**Comment by LichKing-2234** [comment]
> @LichKing-2234 @plutoless any new guys? 😨 this is a very important part
> ![image](https://user-images.githubusercontent.com/1781506/83407301-7e6a6780-a421-11ea-8960-12527780331b.png)

I will try to run the angular lib and test it

**Comment by LichKing-2234** [comment]
I have tried the angular demo and flutter demo, it works for me

**Comment by LichKing-2234** [comment]
here is the changed code
![image](https://user-images.githubusercontent.com/9312526/83484515-addbab80-a4d7-11ea-8965-cb7714831377.png)

**Comment by LichKing-2234** [comment]
here is the changed code of flutter demo
![image](https://user-images.githubusercontent.com/9312526/83484571-cd72d400-a4d7-11ea-9f2f-50d6fc76d3b1.png)

**Comment by LichKing-2234** [comment]
if the encryption is not matching flutter, you can see the warning in the console log.
13:59:55:641 Agora-SDK [WARNING]: [82CEB] stream crypt error

**Comment by NarHakobyan** [comment]
Sorry guys for delay, here is logs

![image](https://user-images.githubusercontent.com/1781506/85391514-54f1b700-b55b-11ea-9848-989fb5ccf155.png)

**Comment by LichKing-2234** [comment]
maybe you can try to add encryption after `enbaleViedeo`

**Comment by NarHakobyan** [comment]
The same, also I am getting 504 timeout and cors errors 
![image](https://user-images.githubusercontent.com/1781506/85407930-e91c4800-b574-11ea-893c-ac8abbdeff7b.png)

**Comment by LichKing-2234** [comment]
Please refer to the diff code picture, which I have commented above. I test the sample code and it works fine.

**Comment by NarHakobyan** [comment]
I just did the same :)

**Comment by LichKing-2234** [comment]
> I just did the same :)

The same code without any differences?

**Comment by LichKing-2234** [comment]
you can try to clone our flutter demo and the `ngx-agora` demo, then modify the code as same as mine. and test it.

**Comment by NarHakobyan** [comment]
In the demo there is only appID configuration, we are using also token

**Comment by NarHakobyan** [comment]
what about cors errors?

**Comment by LichKing-2234** [comment]
> In the demo there is only appID configuration, we are using also token

okay, I will test it with the token.

**Comment by LichKing-2234** [comment]
I have joinChannel with the token, it works fine. please ignore web video is black because my mac camera is broken.
![image](https://user-images.githubusercontent.com/9312526/85519858-bb96d380-b634-11ea-82ee-a3b087f380f9.png)
![image](https://user-images.githubusercontent.com/9312526/85519919-ce110d00-b634-11ea-8756-a9e3952af03b.png)

**Comment by LichKing-2234** [comment]
> what about cors errors?

try `ping webcollector-1.agora.io`?

**Comment by NarHakobyan** [comment]
> > what about cors errors?
> 
> try `ping webcollector-1.agora.io`?

it's cors error, ping is working maybe in webcollector need to add * for cross-origin access.

**Comment by NarHakobyan** [comment]
guys, I am sure agora flutter SDK has issues, It's working nice on the web, We tested many times with both encrypted and encrypted with nonencrypted, so all cases working. We are getting errors on mobile

![image](https://user-images.githubusercontent.com/1781506/85573033-927f3e80-b646-11ea-8f02-33ebc6f94828.png)

![Uploading image.png…]()

**Comment by LichKing-2234** [comment]
is it work the first time?

**Comment by LichKing-2234** [comment]
have you set encryption config when you rejoin the channel?
the encryption config will reset when you leave the channel.
https://docs.agora.io/en/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a3586017747a74d79ea6e7421af6b1a20

**Comment by NarHakobyan** [comment]
Yeah, it's not working for the first time

**Comment by LichKing-2234** [comment]
I have no idea about it,The best way is provide your project or make a demo, then I can test it.

**Comment by NarHakobyan** [comment]
can you check from logs why it's giving 120 error?

**Comment by NarHakobyan** [comment]
Hey guys, sorry for so much disturbing you, that was really dummy issue, web and mobile used different appid, but I don't know why videocall worked, thanks a lot for help

Be safe.
