### ISSUE TITLE
Is there any method to get Video's framerate?

### ISSUE THREAD

**Issue by BansookNam** [AgoraIO/Flutter-SDK#130]
Hi, First of all, Thank you for providing this amazing flutter plugin.

We need a method to listen of video's frame rate continuously.

I found onNetworkQuality method. but I need more details.

It will be awesome you provide a listening method for `Video Frame Rate, Video Width-Height, Audio rate`.

We need this for checking user's video chat is working ok.

**Comment by plutoless** [comment]
how about remoteVideoStats remoteAudioStats?

**Comment by BansookNam** [comment]
Awesome Thank you @plutoless !👍 That was exactly what I'm looking for. Peace!
