### ISSUE TITLE
Use Texture instead of Surface

### ISSUE THREAD

**Issue by agungsb** [AgoraIO/Flutter-SDK#133]
Can you provide a method to let the developer use Texture instead of Surface?

I am developing an application using Agora and need to take a screenshot of the video. Since by default Agora use Surface, the screenshot results a blank screen.

I saw in the documentation there are methods to render using Texture instead of Surface in Android SDK. But I don't see any in Flutter SDK.

Do you have any plan to provide it in the future? Thanks.

**Comment by LichKing-2234** [comment]
[android demo](https://github.com/AgoraIO/Advanced-Video/blob/master/Android/lib-external-video/src/main/java/io/agora/advancedvideo/externvideosource/localvideo/LocalVideoInput.java)
[doc](https://docs.agora.io/en/Interactive%20Broadcast/custom_video_android?platform=Android)

**Comment by LichKing-2234** [comment]
We will support the TextureView at the next beta version.

**Comment by LichKing-2234** [comment]
finished
