### ISSUE TITLE
SEVERE!!! This library kills all touch input to my phone

### ISSUE THREAD

**Issue by edTheGuy00** [AgoraIO/Flutter-SDK#136]
I tried the example app on my Galaxy Note 10 and after about 10 seconds all touch input stops working making my phone completely unusable and I have to do a  hard reboot. This is 100% reproducible and only happens on Note 10. There is no discernible error messages, but looking at my logcat there appears to be some crashes with the Navigation bar. 

https://imgur.com/a/0ga77P9

```
D/SurfaceView(31501): surfaceCreated 1 #8 io.flutter.embedding.android.FlutterSurfaceView{6801d1e V.E...... ........ 0,0-1080,2280}
D/SurfaceView(31501): surfaceChanged (1080,2280) 1 #8 io.flutter.embedding.android.FlutterSurfaceView{6801d1e V.E...... ........ 0,0-1080,2280}
I/CameraManagerGlobal(31501): Camera 91 facing CAMERA_FACING_FRONT state now CAMERA_STATE_IDLE for client com.samsung.android.bio.face.service API Level 2
D/ViewRootImpl@64bda0[MainActivity](31501): MSG_WINDOW_FOCUS_CHANGED 1 1
D/InputMethodManager(31501): prepareNavigationBarInfo() DecorView@f14b234[MainActivity]
D/InputMethodManager(31501): getNavigationBarColor() -855310
D/InputMethodManager(31501): prepareNavigationBarInfo() DecorView@f14b234[MainActivity]
D/InputMethodManager(31501): getNavigationBarColor() -855310
V/InputMethodManager(31501): Starting input: tba=com.example.agora_test ic=null mNaviBarColor -855310 mIsGetNaviBarColorSuccess true , NavVisible : true , NavTrans : false
D/InputMethodManager(31501): startInputInner - Id : 0
I/InputMethodManager(31501): startInputInner - mService.startInputOrWindowGainedFocus
D/InputTransport(31501): Input channel destroyed: 'ClientS', fd=103
I/CameraManagerGlobal(31501): Camera 91 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.samsung.android.bio.face.service API Level 2
```

**Comment by plutoless** [comment]
we will try looking for a device and reproduce

**Comment by BansookNam** [comment]
it's also reproduced on galaxy s10 5g, s10e (android 10)
<img width="254" alt="스크린샷 2020-05-19 오후 5 39 09" src="https://user-images.githubusercontent.com/7719604/82304736-ad331780-99f7-11ea-870f-ad2033d83ae3.png">
<img width="252" alt="스크린샷 2020-05-19 오후 5 39 15" src="https://user-images.githubusercontent.com/7719604/82304743-b0c69e80-99f7-11ea-8672-04110427be8d.png">

we providing a chat component in the consultation screen.
After using another camera app for attaching. it reproduced.

we call AgoraRtcEngine.muteLocalVideoStream(true); before open another camera app.
and call AgoraRtcEngine.muteLocalVideoStream(false); after came back.

Then `I/CameraManagerGlobal( 3692): postSingleUpdate device: camera id 1 status STATUS_PRESENT
I/CameraManagerGlobal( 3692): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.lawfully.lawfully_ai_tracker.dev API Level 2
I/CameraManagerGlobal( 3692): postSingleUpdate device: camera id 1 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal( 3692): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.lawfully.lawfully_ai_tracker.dev API Level 2
I/CameraManagerGlobal( 3692): postSingleUpdate device: camera id 1 status STATUS_PRESENT
I/CameraManagerGlobal( 3692): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_CLOSED for client com.lawfully.lawfully_ai_tracker.dev API Level 2
I/CameraManagerGlobal( 3692): postSingleUpdate device: camera id 1 status STATUS_NOT_AVAILABLE
I/CameraManagerGlobal( 3692): Camera 1 facing CAMERA_FACING_FRONT state now CAMERA_STATE_OPEN for client com.lawfully.lawfully_ai_tracker.dev API Level 2`

this log is reproduced infinitely.

please fix this bug

**Comment by BansookNam** [comment]
I found something.

1. use agora with front camera.
2. open camera with imagePicker using rear camera.
3. comeback to agora with front camera.
4. error like stackoverflow is reproduced.
5. use AgoraRTCengine.switchCamera().
6. the error disappear and everything came back to normal.

**Comment by LichKing-2234** [comment]
we don't have the device to test, is it causes ANR? or other problems?

**Comment by BansookNam** [comment]
@LichKing-2234 it causes exactly same proplem as @edTheGuy00 has.
The application and, os system become frozen. 

However, when I call `AgoraRTCengine.switchCamera().` it came back to normal.

So, in our service. When we came back to the application again we forcely

**Comment by plutoless** [comment]
@BansookNam i think a more proper approach is to disableVideo when app goes to background, and enable when it comes back to foreground. wait 300ms sounds bit tricky.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
