### ISSUE TITLE
App crash for android

### ISSUE THREAD

**Issue by stringsoul** [AgoraIO/Flutter-SDK#137]
No implementation found for int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog__ILjava_lang_String_2)
E/flutter (11364): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: No implementation found for int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String) (tried Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog and Java_io_agora_rtc_internal_RtcEngineImpl_nativeLog__ILjava_lang_String_2)
E/flutter (11364):      at io.agora.rtc.internal.RtcEngineImpl.nativeLog(Native Method)
E/flutter (11364):      at io.agora.rtc.internal.c.a(:25)
E/flutter (11364):      at io.agora.rtc.internal.c.b(:49)
E/flutter (11364):      at io.agora.rtc.internal.RtcEngineImpl.h(:155)
E/flutter (11364):      at g.a.b.c.a(:881)
E/flutter (11364):      at g.a.a.a.a(:22)
E/flutter (11364):      at io.flutter.plugin.platform.SingleViewPresentation.onCreate(:186)
E/flutter (11364):      at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/flutter (11364):      at android.app.Dialog.show(Dialog.java:313)
E/flutter (11364):      at android.app.Presentation.show(Presentation.java:257)
E/flutter (11364):      at io.flutter.plugin.platform.k.<init>(:95)
E/flutter (11364):      at io.flutter.plugin.platform.k.a(:48)
E/flutter (11364):      at io.flutter.plugin.platform.j$a.a(:112)
E/flutter (11364):      at io.flutter.embedding.engine.f.g$a.c(:95)
E/flutter (11364):      at io.flutter.embedding.engine.f.g$a.a(:59)
E/flutter (11364):      at g.c.b.a.k$a.a(:226)
E/flutter (11364):      at io.flutter.embedding.engine.b.b.a(:85)
E/flutter (11364):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(:631)
E/flutter (11364):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (11364):      at android.os.MessageQueue.next(MessageQueue.java:335)
E/flutter (11364):      at android.os.Looper.loop(Looper.java:183)
E/flutter (11364):      at android.app.ActivityThread.main(ActivityThread.java:7478)
E/flutter (11364):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter (11364):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/flutter (11364):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)

**Comment by LichKing-2234** [comment]
You may forget run `AgoraRtcEngine.create`

**Comment by stringsoul** [comment]
You mean like this right?

Future<void> _initialize() async {
    await checkPermission([
      PermissionGroup.microphone,
      PermissionGroup.camera,
    ]);
    await _initAgoraRtcEngine();
    _addAgoraEventHandlers();
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
    await AgoraRtcEngine.setParameters(
        '''{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}''');
//    AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");
    await AgoraRtcEngine.joinChannel(null, "class-${widget.classId}", null, 0);
  }

  Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create(Application.config.agoraAppId);
    await AgoraRtcEngine.enableVideo();
  }

**Comment by LichKing-2234** [comment]
crash on release mode?

**Comment by stringsoul** [comment]
nope, debug mode

**Comment by stringsoul** [comment]
I already add on -keep class io.agora.**{*;} in the ProGuard-rules.pro.. but seems doesn't work at all

**Comment by stringsoul** [comment]
I already fix it, the page cannot wait for check permission..
