### ISSUE TITLE
Unable to invoke create on AgoraRtcEngine Error occurred "Access denied finding property "net.dns1""

### ISSUE THREAD

**Issue by subhadeepdas91** [AgoraIO/Flutter-SDK#138]
Unable to invoke create AgoraRtcEngine instance following error occurred

RTC Engine version:
agora_rtc_engine: **^1.0.12**

Error while executing line 
**await AgoraRtcEngine.create("AGORA_APP_ID");**

Launching lib/main.dart on Android SDK built for x86 in debug mode...
Running Gradle task 'assembleDebug'...
✓ Built build/app/outputs/apk/debug/app-debug.apk.
Debug service listening on ws://127.0.0.1:43061/dL_wOeaJMg0=/ws
Syncing files to device Android SDK built for x86...
D/EGL_emulation( 6315): eglMakeCurrent: 0xdc1f0640: ver 2 0 (tinfo 0xe0be0b20)
I/flutter ( 6315): initiating state
I/flutter ( 6315): **{Permission.camera: PermissionStatus.granted, Permission.microphone: PermissionStatus.granted}**
W/Settings( 6315): Setting android_id has moved from android.provider.Settings.System to android.provider.Settings.Secure, returning read-only value.
E/BluetoothAdapter( 6315): Bluetooth binder is null
E/libc    ( 6315): **Access denied finding property "net.dns1"**
E/libc    ( 6315): **Access denied finding property "net.dns1"**
E/libc    ( 6315): **Access denied finding property "net.dns2"**
E/libc    ( 6315): **Access denied finding property "net.dns2"**
E/libc    ( 6315): **Access denied finding property "net.dns3"**
E/libc    ( 6315): **Access denied finding property "net.dns4"**
E/libc    ( 6315): **Access denied finding property "net.dns3"**
E/libc    ( 6315): **Access denied finding property "net.dns4"**

![Screenshot_20200520_115904](https://user-images.githubusercontent.com/29140664/82412474-5712b280-9a91-11ea-931d-cbd9418b70b8.png)

**Comment by ironynet** [comment]
refer to https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/41#issuecomment-624979308

**Comment by subhadeepdas91** [comment]
@ironynet 
Fixed the problem by enclosing the code in try catch and ignoring the error, but is it a good approach to ignore the exception?

By the way, Thanks for the help and quick reply...
