### ISSUE TITLE
请在AgoraRtcEnginePlugin中暴露获取RtcEngine实例的静态方法

### ISSUE THREAD

**Issue by 39251474** [AgoraIO/Flutter-SDK#14]
如题，我的产品中有屏幕共享需求，此前使用我自己写的声网插件，最近考虑切换到官方插件，但是拿不到实例，无法调用setVideoSource。
目前依赖声网RtcEngine.create的单例特性来获取实例，但是依然存在一些问题，因为原生这边监听不方便监听RtcEngine是否被销毁

**Comment by LichKing-2234** [comment]
dev version supports it.
