### ISSUE TITLE
Remote video problem

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Flutter-SDK#140]
I experience a problem with the video as follows:
1. Local user starts a video session.
2. Local user successfully joins the channel and local video starts rendering
3. Remote user joins the channel.
4. AgoraRtcEngine.onUserJoined is triggered and remote user uid is received. 
5. AgoraRtcEngine.onFirstRemoteVideoFrame is never triggered and the remote user screen is not rendered. 

The above was happening despite several attempts at the time. The remote user was able to see and hear me (the local user), I could hear the remote user but no video was coming through.

Note that in our implementation the video is always on and the user does not have the option of turning it off. 

Sure enough, a few hours later none of this was reproducible. 

- So my question is if anyone has had a similar issue? 
- Any educated guesses as to what might cause AgoraRtcEngine.onFirstRemoteVideoFrame never to be triggered?

**Comment by LichKing-2234** [comment]
have you invoked enbaleVideo method?

**Comment by rgb1380** [comment]
Of course. It was an intermittent problem and started working fine later without any changes.

**Comment by LichKing-2234** [comment]
please provide our SDK log

**Comment by rgb1380** [comment]
This was happening in an instance of the app compiled for release. I know from our own app logs that  onFirstRemoteVideoFrame was not being invoked. Is there a way to get the SDK logs? If not, how do I capture SDK logs in case it happens in the future?

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/java/v2.9.2/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ab25d55c7f95903ff09280e308a977c08

**Comment by LichKing-2234** [comment]
by the way, you need the write storage permission.

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 @rgb1380 
I encountered same issue.

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 @rgb1380 
I realized that this bug occurs when you create `AgoraRenderView` without specifying width and height. I could display and fire `onFirstRemoteVideoFrame` by giving an initial video size.

**Comment by rgb1380** [comment]
I have seen this problem (out of nowhere again) and this time have been able to capture the SDK logs. 

[LRsDCyKIq0dLtxL1Y2hc.log](https://github.com/AgoraIO/Flutter-SDK/files/4958892/LRsDCyKIq0dLtxL1Y2hc.log)
[3JO7upTSvvS8ts3nDXTw.log](https://github.com/AgoraIO/Flutter-SDK/files/4958893/3JO7upTSvvS8ts3nDXTw.log)

LRsDCyKIq0dLtxL1Y2hc.log belongs to user with uid=1, that joins the channel first (using iPad).
3JO7upTSvvS8ts3nDXTw.log belongs to user with uid=2 (using an Android phone).

Both users can render their local video feed. Neither of the users are able to see the counterparty video feed (remote video feed). But audio feed works fine (in this test we did not enabled audio though). OnVideoSizeChanged and onFirstRemoteVideoFrame are not called for remote channels. 

Both users started on audio mute and did not unmute.d However, If we unmute the audio,  onFirstRemoteAudioDecoded will be called. This was not done in this test to keep the logs to minimum. 

This next log was taken a few minutes later from uid=1. This time log level was set to debug and audio was enabled in the middle of the call. User 2 joined but neither were able to see each other's video feed.
[LRsDCyKIq0dLtxL1Y2hc (2).log](https://github.com/AgoraIO/Flutter-SDK/files/4958993/LRsDCyKIq0dLtxL1Y2hc.2.log)

In a third test, we added another user (uid=3) to the channel. This user is using an iPhone.
Users 2, and 3 can see and hear each other. Neither of them can see user uid=1, and user with uid=1 can see neither of users 2 or 3. There is no difference between the code running on iPhone and iPad. User 1 & 3 log file is set to debug but user 2 was at info level.

[LRsDCyKIq0dLtxL1Y2hc (3).log](https://github.com/AgoraIO/Flutter-SDK/files/4959091/LRsDCyKIq0dLtxL1Y2hc.3.log)
[3JO7upTSvvS8ts3nDXTw (3).log](https://github.com/AgoraIO/Flutter-SDK/files/4959100/3JO7upTSvvS8ts3nDXTw.3.log)
[MqLwjXYbuRrpKeLsC2xh (3).log](https://github.com/AgoraIO/Flutter-SDK/files/4959102/MqLwjXYbuRrpKeLsC2xh.3.log)

Last time we had this issue, it persisted for several hours and then went away the next day.

**Comment by LichKing-2234** [comment]
> @LichKing-2234 @rgb1380
> I realized that this bug occurs when you create `AgoraRenderView` without specifying width and height. I could display and fire `onFirstRemoteVideoFrame` by giving an initial video size.

@yukitaka13-1110 AgoraRenderView must have size, or set in a widget container

**Comment by rgb1380** [comment]
> > @LichKing-2234 @rgb1380
> > I realized that this bug occurs when you create `AgoraRenderView` without specifying width and height. I could display and fire `onFirstRemoteVideoFrame` by giving an initial video size.
> 
> @yukitaka13-1110 AgoraRenderView must have size, or set in a widget container

So if AgoraRenderView does not have an explicit size, this issue will or may happen? I do not set an explicit size for AgoraRenderView and it works fine, except for the issue I have described here. I also tried to set an explicit size when this issue was happening on the iPad and it made no difference. Can you elaborate on your response? Are you able to reproduce the problem when you do not set an explicit size?

**Comment by LichKing-2234** [comment]
@rgb1380 iPad need to use the dev version, and call this method.
`setParameters("{\"che.video.inactive_enable_encoding_and_decoding\":true}")`

**Comment by rgb1380** [comment]
> @rgb1380 iPad need to use the dev version, and call this method.
> `setParameters("{\"che.video.inactive_enable_encoding_and_decoding\":true}")`

Can you please elaborate on your response? What does this setting do?
Should this be only done on iPad or does not hurt if it is enabled for other devices?
What is the issue with iPad and where has the issue been logged and being tracked? How does the dev release is fixing this issue?
Also, is there a way to find out when AgoraRenderView is not working properly? We are currently unable to detect if the user has a problem, unless they report the black screen. I have also seen this happening on slow connections (the black screen). Is there a way to detect when this is happening?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
