### ISSUE TITLE
onRecordFrame NOT FOUND

### ISSUE THREAD

**Issue by wenboLee** [AgoraIO/Flutter-SDK#141]
support `onRecordFrame` in flutter

https://docs.agora.io/cn/Voice/API%20Reference/java/v2.9.2/interfaceio_1_1agora_1_1rtc_1_1_i_audio_frame_observer.html

**Comment by LichKing-2234** [comment]
we do not want to support it on flutter platform, because it is quite performance hungry. why do you want to use it on flutter?

**Comment by wenboLee** [comment]
i neet the data for a Visualizer in flutter. 😭

**Comment by LichKing-2234** [comment]
you can for our SDK, and add it with native code

**Comment by azhansy** [comment]
I also have this requirement, we hope to support this function.
