### ISSUE TITLE
Question: Is it possible to use agora videocall when ios device is locked  and using native callkit?

### ISSUE THREAD

**Issue by NarHakobyan** [AgoraIO/Flutter-SDK#145]

**Comment by LichKing-2234** [comment]
I think just need to enable background mode?

**Comment by NarHakobyan** [comment]
It's enabled, but there is a problem, when iPhone is locked there is only one way to receive calls, need to use native callKit, and it's showing native call page, so users can do call from this screen.

![image](https://user-images.githubusercontent.com/1781506/84397680-ff8ae100-ac0f-11ea-95fd-997bca6f2ef5.png)

**Comment by LichKing-2234** [comment]
it needs to use CallKit and PushKit, maybe you can fork our SDK and customize the native code.

**Comment by NarHakobyan** [comment]
without customizing it will not work?

**Comment by LichKing-2234** [comment]
yes, it is not working default.

**Comment by NarHakobyan** [comment]
Okay, thanks for answering.

**Comment by rekonvald** [comment]
Hi! Have you found solution? I have the same issue
