### ISSUE TITLE
Phone oveheating while videocall after agora sdk intgration

### ISSUE THREAD

**Issue by vaibhavmali123** [AgoraIO/Flutter-SDK#149]
**I added agora SDK plugins to my flutter project's pubspec.yaml but while i am testing video call my phone is overheating**

**Comment by plutoless** [comment]
video encoding/decoding itself will consume certain amount of cpu/gpu power. so it's normal if it's heating your device a little bit.

**Comment by plutoless** [comment]
what kind of resolution are you using? and framerate? will the situation be better if you use a lower resolution and fps?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
