### ISSUE TITLE
flutter调用native大部分接口没有执行result.success

### ISSUE THREAD

**Issue by 39251474** [AgoraIO/Flutter-SDK#15]
Android实现大部分的接口没有调用result.success(null)来返回结果，并且dart端全部使用 async+await模式。这样导致如果在dart端调用AgoraRtcEngine方法时也使用协程会卡住无法继续执行，因为大部分接口返回的Future永远不会被执行。还有Android端result不需要包装，不管Android端在哪个线程调用result的方法都会在dart的主线程返回。

**Comment by plutoless** [comment]
感谢指出 确实是我们当时开发的疏忽，这边可能给我们提个PR吗？
