### ISSUE TITLE
Can you get video previews of calls?

### ISSUE THREAD

**Issue by MaskyS** [AgoraIO/Flutter-SDK#151]
Scenario: Multiple live streams are occurring on different users' channels. On the app's feed, is it possible to show video previews of each call, similar to twitch?

**Comment by LichKing-2234** [comment]
preview video or just picture?

**Comment by MaskyS** [comment]
Preferably video, but just a picture updated periodically could do as well

**Comment by LichKing-2234** [comment]
you can join the channel and add render widget to preview remote video. but only one at the same time.

**Comment by MaskyS** [comment]
I'd like to fetch previews of multiple channels, going at it one at a time
seems rather inefficient. Is there any other way?

**Comment by LichKing-2234** [comment]
the best way is getting preview from CDN.
