### ISSUE TITLE
Simulator vs Real Device Testing [ios]

### ISSUE THREAD

**Issue by toklive** [AgoraIO/Flutter-SDK#153]
I am testing the example provided in this repo as well as the community provided one. Both works in the real device but not in the real device. In simulator after asking for the camera/microphone permission, it just shows black screen. Both sample has the following set to true for ios.

	<key>io.flutter.embedded_views_preview</key>
	<true/>

Any idea what I might be missing here. Thanks!

**Comment by plutoless** [comment]
ios simulator does not support camera i believe.

**Comment by sowsan** [comment]
Does it work in Android? It didn’t work either for me

**Comment by plutoless** [comment]
android does support it. you can configure to use a virtual camera or real camera in simulator settings. if it's not working it's most likely some other issues
