### ISSUE TITLE
onAudioVolumeIndication is not working fine

### ISSUE THREAD

**Issue by singlakaran** [AgoraIO/Flutter-SDK#156]
`onAudioVolumeIndication` this method is not giving me information of local stream.

as write in this agora [documentation](https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_i_rtc_engine_event_handler.html#a4d37f2b4d569fa787bb8c0e3ae8cd424)

**Comment by shashikantdurge** [comment]
Issue #150

**Comment by LichKing-2234** [comment]
dev version fixed
