### ISSUE TITLE
How to run with ARGear partner?

### ISSUE THREAD

**Issue by cnttechio** [AgoraIO/Flutter-SDK#157]
I want to use the package with ARGear, so Can you show me how to do that?

**Comment by LichKing-2234** [comment]
you can fork our SDK, and write code in the native layer

**Comment by cnttechio** [comment]
Hi Arthas,

That's sounds great. Do you have documents about that?.

Many thanks.

**Comment by LichKing-2234** [comment]
documents about what? ARGear?

**Comment by cnttechio** [comment]
Hi @LichKing-2234 ,
Documents about How to call methods from Flutter to Agora's SDK Native for iOS and Android?.

**Comment by plutoless** [comment]
@cnttechio 
e.g. you can find android native implementation in this file,
https://github.com/AgoraIO/Flutter-SDK/blob/master/android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java
similarly you can find implementation for iOS, you may add methods as you like there

**Comment by LichKing-2234** [comment]
[Raw data plugin](https://pub.dev/packages/agora_rtc_rawdata) is beta now, you can refer to the example and implement the code in the Android&iOS or C++ layer.
