### ISSUE TITLE
dart端AgoraRtcEngine的事件回调不适合用静态变量

### ISSUE THREAD

**Issue by 39251474** [AgoraIO/Flutter-SDK#16]
如题，客户端在集成声网时往往会实现一个client类用以管理音视频的各种操作和状态，其中包括AgoraRtcEngine的初始化和回调绑定。
在客户端使用音视频时会实例化client类，不使用时销毁client。
但是由于AgoraRtcEngine中的回调全部是静态变量，这就需要在client销毁时把AgoraRtcEngine绑定的回调全部置空以便client的内存可以被回收，显然这种操作非常不友好且容易被忽略。
如果有人直接在StatefulWidget中集成AgoraRtcEngine功能，极有可能导致State不会被释放。

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
