### ISSUE TITLE
Broken camera after sleep mode on Android

### ISSUE THREAD

**Issue by theSharpestTool** [AgoraIO/Flutter-SDK#161]
Steps to reproduce:
1) Turn off the screen of android device/wait until it goes to sleep mode
2) After a minute a message in the logs:

> E/AGORA_SDK(24213): cannot open log file for writing: agorartm.log, err=30
E/AGORA_SDK(24213): cannot open log file for writing: agorartm.log, err=30
W/Binder:24213_1(24213): type=1400 audit(0.0:235716): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=15660 scontext=u:r:untrusted_app_27:s0:c236,c257,c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (24213): Access denied finding property "camera.aux.packagelist"
W/Binder:24213_3(24213): type=1400 audit(0.0:235717): avc: denied { read } for name="u:object_r:camera_prop:s0" dev="tmpfs" ino=15660 scontext=u:r:untrusted_app_27:s0:c236,c257,c512,c768 tcontext=u:object_r:camera_prop:s0 tclass=file permissive=0
E/libc    (24213): Access denied finding property "camera.aux.packagelist"
W/om.openmed.liv(24213): Long monitor contention with owner main (24213) at boolean android.os.BinderProxy.transactNative(int, android.os.Parcel, android.os.Parcel, int)(BinderProxy.java:-2) waiters=0 in void android.hardware.camera2.impl.CameraDeviceImpl$CameraDeviceCallbacks.onCaptureStarted(android.hardware.camera2.impl.CaptureResultExtras, long) for 339ms

3) After the screen is turned on the camera is frozen.
4) `AgoraRtcEngine.muteLocalVideoStream(false);` makes the camera image black

 The issue can only be solved by reloading the app. On IOS works fine.

**Comment by plutoless** [comment]
on android you will need to call disableVideo when going to background mode, while you will need to call enableVideo when coming back to foreground mode. If you want to keep camera working you will need to use foreground service, otherwise you will need to follow above guidance

**Comment by theSharpestTool** [comment]
@plutoless Thank you, the solution with disableVideo works

**Comment by LichKing-2234** [comment]
you can refer to this comment.
https://github.com/AgoraIO/Flutter-SDK/issues/28#issuecomment-717667342
