### ISSUE TITLE
Notification like google meet

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO/Flutter-SDK#162]
Can we have an optional notification with title & some actions (Leave button) in Android ?

**Comment by LichKing-2234** [comment]
I think it is irrelevant to RTC SDK?

**Comment by shashikantdurge** [comment]
It can be an optional feature. Since it's difficult to create this feature in flutter, we can do it similar to meet and keep it optional and a little flexible

**Comment by LichKing-2234** [comment]
I'd love to hear what you think. Can you describe it in detail?

**Comment by shashikantleher** [comment]
Developer have to do additional configuration to enable notification.

For reference: https://pub.dev/packages/flutter_segment#installation
In this plugin _ENABLE_BRANCH_IO_INTEGRATION_ is an additional and optional feature which the plugin offers.

**Comment by shashikantdurge** [comment]
And by flexible I mean, The notification text and notification icon to be configurable

**Comment by plutoless** [comment]
hi @shashikantdurge there are lots of packages on pub.dev. just search notification and you should find what you want there. For the moment there's unfortunately no plan to support notifcation banner ui in our flutter package. I'm closing this, feel free to reopen if you disagree.
