### ISSUE TITLE
ld: library not found for -lcrypto [iOS] [Dev version]

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO/Flutter-SDK#163]
Tried to run app with **agora_rtc_engine: 3.0.1-dev.2**. 
iOS build is failing with:

```
ld: library not found for -lcrypto
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
Could not build the precompiled application for the device.

Error launching application on iPhone.
```

flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at /Users/shashikantdurge/development/flutter
    • Framework revision f139b11009 (4 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/shashikantdurge/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone • 98ca07e3d86d8b3fea6272de95e3604e225a77a4 • ios • iOS 13.5.1

• No issues found!

**Comment by shashikantdurge** [comment]
@LichKing-2234 Any quick solutions please

**Comment by shashikantdurge** [comment]
logs: flutter doctor -v
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.12.13+hotfix.9 at /Users/shashikantdurge/development/flutter
    • Framework revision f139b11009 (4 months ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/shashikantdurge/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • iPhone • 98ca07e3d86d8b3fea6272de95e3604e225a77a4 • ios • iOS 13.5.1

• No issues found!
```

**Comment by shashikantdurge** [comment]
This is happening only after updating the agora_rtc_engine plugin to dev version, stable version is working fine.

**Comment by LichKing-2234** [comment]
seem like your cocoapods version is too old

**Comment by shashikantdurge** [comment]
Cocoapods latest stable version 1.9.3
https://github.com/CocoaPods/CocoaPods/releases

This is what I use

**Comment by LichKing-2234** [comment]
could you share the sample project?

**Comment by shashikantdurge** [comment]
I am able to build in fresh flutter project, But not existing project.

**Comment by shashikantdurge** [comment]
This is how it solved for me:

1. create a new flutter project 
2. add dependency agora_rtc_engine: 3.0.x
3. Build iOS, works.
4. Copy ios folder to existing flutter project.
