### ISSUE TITLE
cannot open log file for writing: agorartm.log, err=30

### ISSUE THREAD

**Issue by shivaprasad-n-v** [AgoraIO/Flutter-SDK#168]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LichKing-2234** [comment]
maybe you forget the write storage permission?

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
