### ISSUE TITLE
Change remote broadcaster role to audience

### ISSUE THREAD

**Issue by parvbhullar** [AgoraIO/Flutter-SDK#170]
How to switch the remote user role from broadcaster to audience or vice-versa?

Not able to findout anything regarding that. 

Also How should I get the total audience count who is watching the live stream.

**Comment by LichKing-2234** [comment]
you should use a socket or our RTM SDK to send an order, the remote broadcaster can switch to the audience when received the order.

**Comment by parvbhullar** [comment]
@LichKing-2234 Any documentation reference on how to send the order to remote broadcaster??

**Comment by LichKing-2234** [comment]
the flutter RTM SDK is communicating now, you can refer to the [native doc](https://docs.agora.io/en/Real-time-Messaging/messaging_android?platform=Android)
