### ISSUE TITLE
Beauty Filter in Agora Flutter SDK

### ISSUE THREAD

**Issue by RuhaanSharma** [AgoraIO/Flutter-SDK#171]
**Is your feature request related to a problem? Please describe.**
Yes. RTCEngine BeautyOptions() is not giving good result as per expectation of the user.

**Describe the solution you'd like**
There is code for SenseTime or some other beauty SDK in native code.
Is there any solution for using some awesome in call beauty features in flutter too.

**Describe alternatives you've considered**
Alternatively can you give some demo code using flutter to use those sdks.
How can I use following code in flutter ?

 ```
private void createRemoteView(final Context context, final int uid) {
        runOnUiThread(() -> {
            SurfaceView remoteView = RtcEngine.CreateRendererView(context);
            mRemotePreviewLayout.addView(remoteView);
            mRemotePreviewLayout.setVisibility(View.VISIBLE);
            rtcEngine().setupRemoteVideo(new VideoCanvas(remoteView,
                    VideoCanvas.RENDER_MODE_HIDDEN, uid));
        });
    }
```

It will be really helpful if you can provide a sample code to use these beauty filter sdk from AgoraRTCEngine implementation in flutter.
I know your valuable suggestion could be call native method.
But I have done enough search from my part and I don't even have idea which activity will be called , where to initialise what.
If you can please provide a sample code for my request (for any solution of your choice Banuba, DeepAr, SenseTime), I am sure it will be helpful for many developers using Agora Flutter implementation.
I will be highly thankful to you.

**Comment by LichKing-2234** [comment]
I will think about how to design a plugin to use third party beauty SDK.
Now, you can fork our SDK, and add it by native code.

**Comment by RuhaanSharma** [comment]
Thanks for your reply @LichKing-2234 
To be honest I don't know where to even start with.
I have done enough search I even can't think if a flutter screen is in front , 
which activity will be handling native calls?
which parameter should be passed as in android code it is expecting FrameLayout.
This is just above my pay grade and that is the reason I came to ask for your help.
If a sample code to do what you have suggested to complete this task can be given by you,
it will be highly helpful.
In other case I will have to wait for your plugin and how much time will it take, I don't know.
I really hope to get code wise help from you keeping finger crossed.

**Comment by plutoless** [comment]
@RuhaanSharma it will not work like you expose native api call and it's done. considering performance you should do video filtering under the hood, i.e. native layer. So the apis exposed on top will most likely be some signaling api calls like startVideoFiltering/stopVideoFiltering/setVideoFilteringParameters and everything needs to be done on native side. that's why @LichKing-2234 said this layer will be provided by us. if you have idea how to do video filter on native layer then you can fork our sdk and implement the logic yourself. hope this helps

**Comment by RuhaanSharma** [comment]
@plutoless 
Thanks for reply with such explanation.
I don't have idea how to do video filter on native layer.
My client expect me to finish this task within matter of days and seems like it is not possible at all by me.
Only if possible for you to tell , can you please let me know how much time will it take to provide such layer from your side ?
Will it be matter of 10 days or so , 2-4 weeks or so , or could be months ?

**Comment by LichKing-2234** [comment]
@RuhaanSharma It maybe starts in Q4.

**Comment by RuhaanSharma** [comment]
@LichKing-2234 Thanks for estimated completion time.
I am looking forward to get this plugin in another 5 weeks time.
I will keep this tab open until then , waiting everyday.
Please do drop a comment here too when complete to implement.
Looking forward to it.
Thanks.

**Comment by RuhaanSharma** [comment]
@LichKing-2234 Please do consider my request of plugin for third party beauty sdk.
It is very essential for me. Looking forward to it.

**Comment by LichKing-2234** [comment]
Yes, it has In planning

**Comment by RuhaanSharma** [comment]
@LichKing-2234 Many thanks for re-assuring me. Looking forward to it desperately.

**Comment by LichKing-2234** [comment]
you can get the raw data plugin from this.
https://github.com/AgoraIO/Flutter-SDK/issues/183

**Comment by RuhaanSharma** [comment]
Hi @LichKing-2234 Can you provide a sample code for using beauty filter using this raw data in flutter ?
These 4 methods are not helpful for me to find how actually I can achieve this.
Mostly developer posting issues here must be very experienced but I am new and I could not do it.

**Comment by LichKing-2234** [comment]
@RuhaanSharma  There are too many beauty SDK, I can't support all of them, so I provide the plugin which you can make it by yourself.

**Comment by RuhaanSharma** [comment]
@LichKing-2234 Thanks for your reply.
Yes , I understand that but sample for any one beauty sdk which is of your preference will be highly appreciated.
If you can do that I am sure it will be helpful for many developers like me as well in near future.
I may be asking too much but I don't have any other door to knock for this feature.

**Comment by LichKing-2234** [comment]
@RuhaanSharma 
Maybe you are right, but it won't be a high priority thing, could you pls list some popular beauty SDK, I will plan to make an integration demo for one of them.

**Comment by LichKing-2234** [comment]
@RuhaanSharma 
BTW, have you read the [README](https://github.com/LichKing-2234/flutter_agora_rtc_rawdata#important) file of the plugin?
it needs you to have the ability to develop native applications. Maybe you will use some flutter beauty SDK?

**Comment by SedulousCoder** [comment]
@LichKing-2234 : Is there any beauty filter SDK now in Agora-flutter ? Any sample anywhere ?
