### ISSUE TITLE
Ability to kick out a user

### ISSUE THREAD

**Issue by boucoding** [AgoraIO/Flutter-SDK#172]
Hi,

thank you for this awesome sdk I really appreciate your work,

I want to know if there is a method where a user can kick out a user ( like admin ) and mute all other participants' audio and video?

Should I implement that the user will never enter again myself or already the sdk has such a way?

Thank you for your time!

**Comment by LichKing-2234** [comment]
you can use our restful API.
https://docs.agora.io/en/Agora%20Platform/dashboard_restful_communication?platform=All%20Platforms#banning-rule-management
