### ISSUE TITLE
String type for uid

### ISSUE THREAD

**Issue by NarHakobyan** [AgoraIO/Flutter-SDK#174]
**Describe the bug**
We are storing user ids as UUID, so it's type is a string, in front end lib it's allowing us to pass a string as uid, but in a flutter, it's requires int type

**To Reproduce**
1. Go to '/lib/agora_rtc_engine.dart:457'
2. Find function 'joinChannel'
3. See last argument 'int uid'

**Expected behavior**
It should be a dynamic type

**Screenshots**
![image](https://user-images.githubusercontent.com/1781506/90387043-863bbe80-e096-11ea-8e99-fee5878cd7a2.png)

**Smartphone (please complete the following information):**
 - Version 1.0.13

**Comment by LichKing-2234** [comment]
the uid is must be int, you can use [joinChannelByUserAccount](https://pub.dev/documentation/agora_rtc_engine/latest/agora_rtc_engine/AgoraRtcEngine/joinChannelByUserAccount.html)
