### ISSUE TITLE
[3.0.1-dev6] onVideoSizeChannged triggered without a change in orientation of device

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Flutter-SDK#175]
**Describe the bug**
There is a new problem, where onVideoSizeChanged gets triggered with no good reason indicating that the device has rotated when it has not changed orientation.

**To Reproduce**
1. Start a video session with one phone (I am using an Android phone).
2. Put the device into landscape mode.
3. onVideoSizeChanged is triggered as expected.
4. Use a second device to connect to the video session (ensure that you keep the orientation of the first device as is).
5. onVideoSizeChannged is triggered on both devices indicating a change in rotation for the first device to portrait mode. This is unexpected.
6. Now change the orientation of the first device back to portrait mode.
7. Note that onVideoSizeChanged is not triggered as the system already believes that the device is in portrait mode.

This is completely repeatable on my side. Hopefully, you can replicate this on your side easily. If not, let me know if you need any further information.

**Comment by LichKing-2234** [comment]
@rgb1380 okay, Thank you for your careful test, I will try it today

**Comment by LichKing-2234** [comment]
fixed in 3.0.1.dev.7
