### ISSUE TITLE
Support multiple channel (supports creating multiple RtcEngine)

### ISSUE THREAD

**Issue by thangvq95** [AgoraIO/Flutter-SDK#176]
**Is your feature request related to a problem? Please describe.**
Yes. Future<RtcEngine> create(String appId) 
/// The Agora RTC Native SDK supports creating only one RtcEngine instance for an app for now.

My platform need to handle multiple channel at the same time. Could Agora's team help this? Thanks a lot !!!

**Comment by LichKing-2234** [comment]
dev version support multiple channel

**Comment by thangvq95** [comment]
Thanks for your reply @LichKing-2234 

I'm using dev version. But RtcEngine it still using Singleton pattern. So we can use only one RtcEngine instance. 
I can not use RtcEngine rtcEngine2 to join another channel (it will overload the old one). Or we have another way join multiple channel?
Could you help me check again. Thanks @LichKing-2234 !

<img width="861" alt="Screen Shot 2020-08-27 at 10 47 35 AM" src="https://user-images.githubusercontent.com/13799377/91382527-22628400-e854-11ea-84e9-d04c00a71136.png">
