### ISSUE TITLE
Background Calls in Android Not Working

### ISSUE THREAD

**Issue by rohandkn** [AgoraIO/Flutter-SDK#177]
**Describe the bug**
When putting the app in the background (switching to a different app or going to the home screen), the Agora voice call fails after about two minutes. We've noted the following behaviors.

Android 11 Beta: App gets killed after two minutes of background usage
Android 10: App no longer receives microphone input but can hear other members of the call

**To Reproduce**
1. Install Agora with Flutter
2. Run app and switch to background

**Expected behavior**
1. I expected the voice call to continue to work in the background.

**Desktop (please complete the following information):**
 - MacOS
 - Safari
 - Version 13

**Smartphone (please complete the following information):**
 - Pixel 3
 - Android 10
 - Chrome
 - Version 29

**Comment by plutoless** [comment]
i think this is system behavior. if you want the mic to keep working you will need to implement a foreground service.

**Comment by veyhong** [comment]
Same happen to me, App become mute after switched to background android only.

**Comment by plutoless** [comment]
@veyhong as described above, you will need to use foreground service in this case.
i tried finding some example libs here: https://stackoverflow.com/questions/56862952/foreground-service-example-in-flutter
you can implement it by your own if needed.

**Comment by plutoless** [comment]
@veyhong as described above, you will need to use foreground service in this case.
i tried finding some example libs here: https://stackoverflow.com/questions/56862952/foreground-service-example-in-flutter
you can implement it by your own if needed.

**Comment by veyhong** [comment]
@plutoless isn't it Need to use Background service instead of foreground since we are put the app in background ?

**Comment by Tejareddy94** [comment]
i too have that issue. @plutoless  it would be great if you provide example for this in your example code.

**Comment by plutoless** [comment]
@veyhong please read here what a foreground service does. https://developer.android.com/guide/components/foreground-services

**Comment by LichKing-2234** [comment]
you can refer to this comment.
https://github.com/AgoraIO/Flutter-SDK/issues/28#issuecomment-717667342
