### ISSUE TITLE
playEffect not working on iOS

### ISSUE THREAD

**Issue by jacksonw765** [AgoraIO/Flutter-SDK#181]
I am running this command. It works fine on Android but doesn't do anything on iOS.
`await AgoraRtcEngine.playEffect(1, "assets/sounds/beep_normal.mp3", 1, 1, 1, 100, true);`

**Expected behavior**
Play the sound effect to all members on the call. 

**Smartphone (please complete the following information):**
  - Pixel 3XL (Works great!)
  - iPhone 7 (Doesn't work)

Any help would be appreciated. Thanks!

**Comment by LichKing-2234** [comment]
where is the mp3 file in ios?

**Comment by jacksonw765** [comment]
The mp3 is located in the correct path. It plays correctly with other audio player plugins.

**Comment by jacksonw765** [comment]
`audioMixingOpenError` is thrown

**Comment by LichKing-2234** [comment]
you can refer to this doc.
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/playEffect:filePath:loopCount:pitch:pan:gain:publish:

**Comment by LichKing-2234** [comment]
have you try the full path on iOS?

**Comment by jacksonw765** [comment]
> have you try the full path on iOS?

Yes, same result. `audioMixingOpenError` is thrown

**Comment by LichKing-2234** [comment]
could you pls share a screenshot about the location of your .mp3 file?

**Comment by jacksonw765** [comment]
![image](https://user-images.githubusercontent.com/13068724/95531286-2e427980-09ae-11eb-8b14-2cbf19720fcb.png)
It plays fine with other audio plugins. Sound effects are added to pubspec.ymal.

**Comment by LichKing-2234** [comment]
will be fixed in the next version. flutter assets should use `lookupKeyForAsset` to get the real path.
https://flutter.dev/docs/development/ui/assets-and-images#loading-flutter-assets-in-ios

**Comment by LichKing-2234** [comment]
you should add the mp3 file to your Xcode project, and set the absolute path to our SDK.

**Comment by LichKing-2234** [comment]
https://github.com/AgoraIO/Agora-Flutter-SDK/blob/master/lib/src/rtc_engine_extension.dart

**Comment by plutoless** [comment]
@CodingAleCR for iOS yes you need to add the file into your bundle so that the file will be copied to your device while installing your app. And yes you can play effects while talking.
