### ISSUE TITLE
Black screen on Android release

### ISSUE THREAD

**Issue by jennsenr** [AgoraIO/Flutter-SDK#182]
**Describe the bug**
Black screen on Android release

**To Reproduce**
compile, install and run on Android release

**Additional context**
agora_rtc_engine: ^3.0.1-dev.7

https://github.com/AgoraIO/Flutter-SDK/issues/165 here is a similar problem that had been fixed in previous versions. It is the same in debug it works perfect but in release it remains black.

I could see what is the error that is throwing me

![WhatsApp Image 2020-09-14 at 4 54 10 PM](https://user-images.githubusercontent.com/21229782/93137990-52ab7e80-f6ac-11ea-8924-a87549d014ea.jpeg)

**Comment by LichKing-2234** [comment]
you can refer to this comment.
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/177#issuecomment-692008309
