### ISSUE TITLE
华为手机报错E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!

### ISSUE THREAD

**Issue by wupeng889900** [AgoraIO/Flutter-SDK#19]
07/16 11:07:46: Launching app
$ adb install-multiple -r -t /Users/pengwu/Flutter-SDK/example/build/app/intermediates/resources/instant-run/debug/resources-debug.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/dep/dependencies.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_4.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_3.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_0.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_2.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_1.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_8.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_6.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_7.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_9.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/split-apk/debug/slices/slice_5.apk /Users/pengwu/Flutter-SDK/example/build/app/intermediates/instant-run-apk/debug/app-debug.apk 
Split APKs installed in 9 s 33 ms
$ adb shell am start -n "io.agora.agorartcengineexample/io.agora.agorartcengineexample.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Client not ready yet..Waiting for process to come online
Connected to process 27085 on device huawei-col_al10-9YE0218703008060
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=io.agora.agorartcengineexample#10610#256
I/HwApiCacheMangerEx: apicache path=/storage/emulated/0 state=mounted key=io.agora.agorartcengineexample#10610#0
I/tcengineexampl: The ClassLoaderContext is a special shared library.
W/tcengineexampl: JIT profile information will not be recorded: profile file does not exits.
W/tcengineexampl: JIT profile information will not be recorded: profile file does not exits.
I/AwareBitmapCacher: init processName:io.agora.agorartcengineexample pid=27085 uid=10610
I/InstantRun: starting instant run server: is main process
E/AwareLog: AtomicFileUtils: readFileLines file not exist: android.util.AtomicFile@1209910
I/ResourceExtractor: Resource version mismatch res_timestamp-1-1563246473911
E/MemoryLeakMonitorManager: MemoryLeakMonitor.jar is not exist!
D/ZrHung.AppEyeUiProbe: notify runnable to start.
D/ZrHung.AppEyeUiProbe: Runnable thread started.
D/IMonitor: Load library imonitor_jni
V/ActivityThread: Skipping new config:{1.0 460mcc7mnc [zh_CN_#Hans] ldltr sw360dp w360dp h730dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2190, 1080) mAppBounds=Rect(0, 90 - 1080, 2280) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.184}, config:{1.0 460mcc7mnc [zh_CN_#Hans] ldltr sw360dp w360dp h730dp 480dpi nrml long hdr port finger -keyb/v/h -nav/h winConfig={ mBounds=Rect(0, 0 - 2190, 1080) mAppBounds=Rect(0, 90 - 1080, 2280) mWindowingMode=fullscreen mActivityType=undefined} nonFullScreen=0 suim:1 s.184} for app:io.agora.agorartcengineexample
V/HwPolicyFactory: : success to get AllImpl object and return....
V/ActivityThread: callActivityOnCreate
V/HwWidgetFactory: : successes to get AllImpl object and return....
I/HwApsImpl: APS: new HwApsImpl created
I/hwaps: HwAps: JNI_OnLoad
D/HiTouch_PressGestureDetector: HiTouch on notch display, height corret:90
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/kernel_blob.bin
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/vm_snapshot_data
I/ResourceExtractor: Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
D/OpenGLRenderer: Skia GL Pipeline
I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
    android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
I/iGraphics: [0020080c] pn: io.agora.agorartcengineexample, p: 27085
I/iGraphics: [0030050a] lv: 1.0, cv: 5, Version:B343
W/iGraphics: [0030050c] io.agora.agorartcengineexample not in
I/iGraphics: [0030080c] opt app: 0
D/ActivityThread: add activity client record, r= ActivityRecord{ee0bdc3 token=android.os.BinderProxy@bde363c {io.agora.agorartcengineexample/io.agora.agorartcengineexample.MainActivity}} token= android.os.BinderProxy@bde363c
D/ZrHung.AppEyeUiProbe: notify runnable to start.
D/HwAppInnerBoostImpl: set config for io.agora.agorartcengineexample BOOST_FLAG=true REPORT_DURATION_CLICK=1000 REPORT_TIMES_CLICK=3 REPORT_DURATION_SLIDE=5000 REPORT_TIMES_SLIDE=16
D/OpenGLRenderer:   HWUI Binary is  enabled
    disableOutlineDraw is true
I/HiTouch_HiTouchSensor: enabledInPad = false,isPcCastMode = false
I/flutter: Observatory listening on http://127.0.0.1:46261/t7GfWQYNDDc=/
I/iGraphics: [0030080c] opt app: 0
I/OpenGLRenderer: Initialized EGL, version 1.4
D/OpenGLRenderer: Swap behavior 2
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
D/mali_winsys: EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
I/ViewRootImpl: jank_removeInvalidNode jank list is null
W/InputMethodManager: startInputReason = 1
W/InputMethodManager: startInputReason = 5
V/AudioManager: isWiredHeadsetOn...
E/agora-jni: exception occurred at jni call safeCallIntMethod()
W/System.err: java.lang.SecurityException: getSerial requires READ_PHONE_STATE or READ_PRIVILEGED_PHONE_STATE permission
        at android.os.Parcel.createException(Parcel.java:1953)
        at android.os.Parcel.readException(Parcel.java:1921)
        at android.os.Parcel.readException(Parcel.java:1871)
        at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerial(IDeviceIdentifiersPolicyService.java:94)
        at android.os.Build.getSerial(Build.java:154)
        at io.agora.rtc.internal.CommonUtility.isSimulator(CommonUtility.java:253)
        at io.agora.rtc.internal.RtcEngineImpl.nativeObjectInit(Native Method)
        at io.agora.rtc.internal.RtcEngineImpl.<init>(RtcEngineImpl.java:175)
W/System.err:     at io.agora.rtc.RtcEngine.create(RtcEngine.java:61)
        at io.agora.agorartcengine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.java:82)
        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:386)
        at android.os.Looper.loop(Looper.java:169)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
    Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.os.DeviceIdentifiersPolicyService$DeviceIdentifiersPolicy.getSerial(DeviceIdentifiersPolicyService.java:89)
        at android.os.IDeviceIdentifiersPolicyService$Stub.onTransact(IDeviceIdentifiersPolicyService.java:52)
        at android.os.Binder.execTransact(Binder.java:739)
E/libc: Access denied finding property "net.dns1"
    Access denied finding property "net.dns2"
    Access denied finding property "net.dns3"
    Access denied finding property "net.dns4"
W/tcengineexampl: Accessing hidden method Landroid/telephony/SignalStrength;->getDbm()I (light greylist, reflection)
W/tcengineexampl: Accessing hidden method Landroid/telephony/SignalStrength;->getAsuLevel()I (light greylist, reflection)
E/libc: Access denied finding property "net.dns1"
    Access denied finding property "net.dns2"
    Access denied finding property "net.dns3"
    Access denied finding property "net.dns4"
D/BluetoothHeadset: Proxy object connected
D/HiTouch_PressGestureDetector: HiTouch on notch display, width corret:99
D/OpenGLRenderer:   HWUI Binary is  enabled
    disableOutlineDraw is true

**Comment by wupeng889900** [comment]
其他类型手机正常

**Comment by plutoless** [comment]
看错误的话是华为本身的问题
https://segmentfault.com/q/1010000017304340
这个影响使用吗？不影响的话忽略就好

**Comment by wupeng889900** [comment]
> 看错误的话是华为本身的问题
> https://segmentfault.com/q/1010000017304340
> 这个影响使用吗？不影响的话忽略就好

Agora Flutter Quickstart用了这个好像可以，但是会有偶尔闪退的问题安卓上，

**Comment by wupeng889900** [comment]
> > 看错误的话是华为本身的问题
> > https://segmentfault.com/q/1010000017304340
> > 这个影响使用吗？不影响的话忽略就好
> 
> Agora Flutter Quickstart用了这个好像可以，但是会有偶尔闪退的问题安卓上，

我指的是视频直播过程中应用会闪退

**Comment by plutoless** [comment]
有具体的崩溃栈吗？还是就是上面那个？

**Comment by wupeng889900** [comment]
之前好像报的是空指针的错，今儿测了下没出现这个问题，谢了，到时候有问题再问你把😁

**Comment by plutoless** [comment]
好的
