### ISSUE TITLE
PlatformException when calling leaveChannel() after joinChannelWithUserAccount() in v3.1.2

### ISSUE THREAD

**Issue by ratherNotB** [AgoraIO/Flutter-SDK#193]
In release v3.1.2 an exception is thrown when I try to call leaveChannel() on a channel that was joined using a uid string rather than int:

await _AgoraRtcEngine.joinChannelWithUserAccount(
          token, channelName, userStr);

I/flutter (29071): Error caught by Crashlytics plugin <recordError>:
E/BufferQueueProducer(29071): [SurfaceTexture-0-29071-3](id:718f00000005,api:1,p:707,c:29071) dequeueBuffer: BufferQueue has been abandoned
I/flutter (29071): PlatformException(7, not initialized, null, null)
I/flutter (29071): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
I/flutter (29071): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
I/flutter (29071): <asynchronous suspension>
I/flutter (29071): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (29071): #3      RtcEngine._invokeMethod (package:agora_rtc_engine/src/rtc_engine.dart:32:27)
I/flutter (29071): #4      RtcEngine.leaveChannel (package:agora_rtc_engine/src/rtc_engine.dart:136:12)
I/flutter (29071): #5      _AgoraCallPageState.dispose (package:Tuter/widgets/agora_call.dart:134:25)
I/flutter (29071): #6      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
I/flutter (29071): #7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1998:13)
I/flutter (29071): #8      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (29071): #9      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2007:25)
I/flutter (29071): #10     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2821:27)
I/flutter (29071): #11     BuildOwne
I/flutter (29071): Error caught by Crashlytics plugin <recordError>:
I/flutter (29071): PlatformException(7, not initialized, null, null)
I/flutter (29071): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:582:7)
I/flutter (29071): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:18)
I/flutter (29071): <asynchronous suspension>
I/flutter (29071): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
I/flutter (29071): #3      RtcEngine._invokeMethod (package:agora_rtc_engine/src/rtc_engine.dart:32:27)
I/flutter (29071): #4      RtcEngine.destroy (package:agora_rtc_engine/src/rtc_engine.dart:93:12)
I/flutter (29071): #5      _AgoraCallPageState.dispose (package:Tuter/widgets/agora_call.dart:135:25)
I/flutter (29071): #6      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:4854:12)
I/flutter (29071): #7      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1998:13)
I/flutter (29071): #8      ListIterable.forEach (dart:_internal/iterable.dart:39:13)
I/flutter (29071): #9      _InactiveElements._unmountAll (package:flutter/src/widgets/framework.dart:2007:25)
I/flutter (29071): #10     BuildOwner.finalizeTree.<anonymous closure> (package:flutter/src/widgets/framework.dart:2821:27)
I/flutter (29071): #11     BuildOwner.lock

**Comment by jacksonw765** [comment]
I am seeing this issue as well, only on Android.

**Comment by tushardubey121** [comment]
I am facing the same issue in android and iOS both. Anyone have any update.

**Comment by LichKing-2234** [comment]
I will check it later.

**Comment by LichKing-2234** [comment]
@ratherNotB could you provide the code about this issue? I have tested it, it works.

`PlatformException(7, not initialized, null, null)` means the RtcEngine did not init or has been destroyed.

maybe you call `destroy` twice, or click the button twice.

**Comment by LichKing-2234** [comment]
I will close the issue because it is not active, you can reopen it if the issue still exists.
