### ISSUE TITLE
Make eventHandlers uid parameter dynamic instead of int

### ISSUE THREAD

**Issue by jacksonw765** [AgoraIO/Flutter-SDK#194]
This line ` await engine.joinChannelWithUserAccount(null, this.gameID.toString(), userId);` allows you to join a channel with a string instead of an int. 

However when you create event handlers, (userJoined, userOffline) the uid variable is an int not a string.

Could we make this variable dyanmic instead so it reports back the correct uid?

**Comment by LichKing-2234** [comment]
the uid in the callback is always int, you can use [getUserInfoByUid](https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/react_native/classes/rtcengine.html#getuserinfobyuid)
