### ISSUE TITLE
[Question] Whiteboard and Screensharing

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Flutter-SDK#197]
Are these SDKs available in the Flutter wrapper?
If not any plans to add them to Flutter?
Thanks

**Comment by LichKing-2234** [comment]
Sorry, the whiteboard is not in the scope of our business.
Screensharing is only be supported on the desktop layer by our native SDK.

**Comment by rgb1380** [comment]
I found this
https://www.facebook.com/AgoraIO/photos/voice-video-whiteboard-screen-sharing-all-available-in-agora-sdks-v15-get-starte/1293697364003775/
which seems to suggest whiteboard was released with SDK 1.5. So this is not accurate?

**Comment by plutoless** [comment]
@rgb1380 sorry that was an old post and that whiteboard product has been deprecated and no longer maintained
