### ISSUE TITLE
SDK location not found. Define location with an ANDROID_SDK_ROOT environment variable or by setting the sdk.dir path in your project's local properties file at 'C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-1.0.15\android\local.properties'.

### ISSUE THREAD

**Issue by ds-patel-33** [AgoraIO/Flutter-SDK#199]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by LichKing-2234** [comment]
maybe you can refer to this link.
https://stackoverflow.com/questions/60220030/flutter-debug-build-successful-but-release-gives-error?rq=1
