### ISSUE TITLE
SDK是否包含Agora美颜功能

### ISSUE THREAD

**Issue by isxuelinme** [AgoraIO/Flutter-SDK#2]
如题，如果带美颜功能iOS 版本开发我们会考虑替换为Agora，谢谢声网为Flutter生态助力。

 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by PRWrl** [comment]
Agora SDK 下个版本中会有基础美颜的功能，等发布后会第一时间放进 Flutter

**Comment by PRWrl** [comment]
0.9.4 已经添加 `setBeautyEffectOptions` 接口提供了基础美颜能力
