### ISSUE TITLE
打apk包失败

### ISSUE THREAD

**Issue by HeberLee** [AgoraIO/Flutter-SDK#20]
flutter build apk
Initializing gradle...                                           2.0s
Resolving dependencies...                                        4.6s
Gradle task 'assembleRelease'...

Compiler message:
file:///D:/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-0.9.7/lib/agora_rtc_engine.dart:385:20: Error: Th
e method 'invokeListMethod' isn't defined for the class '#lib1::MethodChannel'.
Try correcting the name to the name of an existing method, or defining a method named 'invokeListMethod'.
    await _channel.invokeListMethod('setBeautyEffectOptions',
                   ^^^^^^^^^^^^^^^^
Compiler terminated unexpectedly.
12.5s
Gradle task assembleRelease failed with exit code 1

**Comment by Matrixbirds** [comment]
跑的是example目录里的demo吗？麻烦提供一下flutter的版本，可以贴一下`flutter doctor`的结果

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
