### ISSUE TITLE
AgoraRenderWidget is getting error.

### ISSUE THREAD

**Issue by shinewanna** [AgoraIO/Flutter-SDK#200]
**Describe the bug**
I have been update the agora_rtc_engine plugin, there's many changes in development field.
So, i'm fixing one by one, but the one AgoraRenderWidget is not found, how to call that.

**Screenshots**
<img width="588" alt="Screen Shot 2020-10-12 at 4 02 30 PM" src="https://user-images.githubusercontent.com/39454969/95730808-c7220f00-0ca4-11eb-8a67-c881c43c36d0.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone 11 pro max]
 - OS: [e.g. iOS 14]

**Comment by LichKing-2234** [comment]
you can refer to the quickstart and modify code.

**Comment by Muhammad-Ullah** [comment]
@shinewanna @LichKing-2234  did you people find any solution?
Help Please...

**Comment by shinewanna** [comment]
> @shinewanna @LichKing-2234  did you people find any solution?
> Help Please...

You can reference from updated Agora quick start flutter. This errors cause by updating the agora plugin. Agora plugin upgraded and usage are modified. You can check the difference from agora quick start github repo.

**Comment by imrajeshcoder** [comment]
import 'package:agora_rtc_engine/rtc_local_view.dart' as RtcLocalView;
import 'package:agora_rtc_engine/rtc_remote_view.dart' as RtcRemoteView;

```
/// Helper function to get list of native views
  List<Widget> _getRenderViews() {
    final List<StatefulWidget> list = [];
    list.add(RtcLocalView.SurfaceView());
    _users.forEach((int uid) => list.add(RtcRemoteView.SurfaceView(uid: uid)));

    
    return list;
  }
```

**Comment by AyuBella97** [comment]
> **Describe the bug** I have been update the agora_rtc_engine plugin, there's many changes in development field. So, i'm fixing one by one, but the one AgoraRenderWidget is not found, how to call that.
> 
> **Screenshots** <img alt="Screen Shot 2020-10-12 at 4 02 30 PM" width="588" src="https://user-images.githubusercontent.com/39454969/95730808-c7220f00-0ca4-11eb-8a67-c881c43c36d0.png">
> 
> **Desktop (please complete the following information):**
> 
> * OS: [e.g. iOS]
> * Browser [e.g. chrome, safari]
> * Version [e.g. 22]
> 
> **Smartphone (please complete the following information):**
> 
> * Device: [e.g. iPhone 11 pro max]
> * OS: [e.g. iOS 14]
> * Browser [e.g. stock browser, safari]
> * Version [e.g. 22]

Just replace "AgoraRenderWidget" with "StatefulWidget". Hope this will help you.
