### ISSUE TITLE
Type cast errors in version 3.1.3

### ISSUE THREAD

**Issue by shashikantdurge** [AgoraIO/Flutter-SDK#204]
**Describe the bug**
agora_rtc_engine 3.1.3
There are some type cast errors
Example : `_TypeError (type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'Map<String, dynamic>')`

**To Reproduce**
Call method `rtcEngine.getUserInfoByUid(uid);`

**Expected behavior**
No typecast errors

**Screenshots**
<img width="720" alt="Screenshot 2020-10-21 at 4 41 09 PM" src="https://user-images.githubusercontent.com/20161204/96712162-4fe32e00-13bc-11eb-96f6-08b19b360fc9.png">

flutter doctor -v
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.7 19H2, locale en-IN)
    • Flutter version 1.17.5 at /Users/shashikantdurge/Development/flutter
    • Framework revision 8af6b2f038 (4 months ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/shashikantdurge/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • ONEPLUS A3003 • 2c21d4b0 • android-arm64 • Android 9 (API 28)
```

**Comment by LichKing-2234** [comment]
Thanks for your issue, it will be fixed next version.

**Comment by LichKing-2234** [comment]
the solution is:
![image](https://user-images.githubusercontent.com/9312526/96714007-1a4a3f00-13d4-11eb-8522-d3ca5f28e1b1.png)

**Comment by LichKing-2234** [comment]
fixed in [3.1.4-rc.0](https://pub.dev/packages/agora_rtc_engine/versions/3.1.4-rc.0/changelog)

**Comment by shashikantdurge** [comment]
@LichKing-2234 Found some more Type case errors
<img width="1102" alt="Screenshot 2020-11-05 at 7 33 47 AM" src="https://user-images.githubusercontent.com/20161204/98188621-5b486480-1f39-11eb-9da8-6b4136b0daa0.png">

**Comment by shashikantdurge** [comment]
I'm working on it. will raise a PR once done
