### ISSUE TITLE
In Broadcast mode, is there a way to find out the number of audience currently in the channel?

### ISSUE THREAD

**Issue by ayha** [AgoraIO/Flutter-SDK#206]
I noticed the RTCStats.users only returns the number of hosts or number of hosts + 1 in the case of local users, however I thought it'd be useful to find out how many people have current joined the channel and watching the broadcast.

Thanks.

**Comment by LichKing-2234** [comment]
you can refer to this.
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/174
