### ISSUE TITLE
新增对arm64架构的支持

### ISSUE THREAD

**Issue by unclexiao** [AgoraIO/Flutter-SDK#21]
一周以前，Flutter官方发布了**v1.7.8+hotfix.3**，已经默认支持了ARM64，声网是否可以同步更新支持呢？ 

[官方的原文](https://medium.com/flutter/announcing-flutter-1-7-9cab4f34eacf)描述如下：

> From August 1st, 2019, Android apps that use native code and target Android 9 Pie will be required to provide a 64-bit version in addition to the 32-bit version when publishing to the Google Play Store. While Flutter has long supported generating 64-bit Android apps, version 1.7 adds support for creating Android App Bundles that target both 64-bit and 32-bit from a single submission. See the updated documentation on publishing Flutter-based Android apps to learn how to do this, as well as how to create separate APK files for both 32-bit and 64-bit devices.

[中文社区](https://flutter-io.cn/posts/announcing-flutter-1-7-9.html)的翻译如下：

> 从 2019 年 8 月 1 日开始，为了 target 到 Android Pie 版本，开发者们在 Google Play 上发布的应用 必须支持 64 位架构。Flutter 一直都支持生成 64 位的 Android 应用，在 1.7 版本里，我们加入了对 Android App Bundles 的支持，开发者们可以在一次提交里同时 target 到 64 位和 32 位。可通过阅读 这篇文档 了解到如何分别生成 32 位和 64 位到应用等更多内容。

---

现在默认build会同时编译到两种CPU架构，加上**agora_rtc_engine**依赖项之后，会因为找不到**libflutter.so** 而报如下错误：

`Gradle build failed to produce an Android package.`

加上`--target-platform android-arm`  参数则正常编译出apk。

期待尽早修复～

**Comment by Matrixbirds** [comment]
这个是编译参数错误和SDK无关 libflutter.so是1.7.x开始支持的arm64 之前的是因为不包括所以要自己配置

**Comment by unclexiao** [comment]
确实是我这边的问题，现在已修复啦，同样感谢🙏
