### ISSUE TITLE
Detect poor connection before the voice call start

### ISSUE THREAD

**Issue by MohammedAlimoor** [AgoraIO/Flutter-SDK#212]
hello there 
how can I check if the internet connection is poor "slow" before creating a channel or join it

**Comment by LichKing-2234** [comment]
you can use this function.
https://docs.agora.io/en/Interactive%20Broadcast/API%20Reference/flutter/rtc_engine/RtcEngine/enableLastmileTest.html

**Comment by MohammedAlimoor** [comment]
thank you  👍
