### ISSUE TITLE
Voice and video doesn't coming synchronous

### ISSUE THREAD

**Issue by cosakin** [AgoraIO/Flutter-SDK#213]
Hi, we have problem in video call. Voice and video doesn't coming synchronous.

We match two user in queue. One of user is login when before put in queue, other user anonymous. After the match start video call. Video call doesn't coming synchronous, especially on low-end Android Smartphone.

How we can solve this problem?

Dimension: 840*480
Frame Rate: 30 Fps
Min. Frame Rate: 24 Fps
Bit Rate: 1860 Kbps
Min. Bit Rate: 930 Kbps
Orientation Mode : Fixed Portrait
Degradation Prefer: Maintain Framerate

Device: Samsung A10(SM-A105F)
OS: Android 10

**Comment by plutoless** [comment]
do you have a recording? it might be easier for us to understand. if you can provide a unique channel name it may also help us investigate

**Comment by cosakin** [comment]
We recorded the day before, but we had a problem with the audio recording (with the device, not the agora problem). We will record and share it with channel id as soon as possible.

**Comment by plutoless** [comment]
@cosakin thanks. looking forward to that

**Comment by cosakin** [comment]
Hi @plutoless , sorry for delay. We solved this problem. It was an error with rendering for first frame. Thank you for your attention.
Regards.

**Comment by rekonvald** [comment]
Hi there!
I have the same issue! How did you solve it?
