### ISSUE TITLE
Type cast of null in `AgoraSurfaceViewFactory.kt` line 80

### ISSUE THREAD

**Issue by wheel1992** [AgoraIO/Flutter-SDK#214]
**Describe the bug**
Type cast of null in `AgoraSurfaceViewFactory.kt` line 80

`data["uid"]`

**Version**
 - agora_rtc_engine: 3.1.2, 3.1.3 and 3.1.4-rc.0

**To Reproduce**

```
// Execute joinChannel and this return joinChannelSuccess in listener
await _rtcEngine.joinChannel("<token>", "<channel_name>", null, 13);
```

**Expected behavior**
Video should start

**Screenshots**
```
E/MethodChannel#flutter/platform_views(17449): Failed to handle method call
E/MethodChannel#flutter/platform_views(17449): kotlin.TypeCastException: null cannot be cast to non-null type kotlin.Int
E/MethodChannel#flutter/platform_views(17449): 	at io.agora.agora_rtc_engine.AgoraSurfaceView.setData(AgoraSurfaceViewFactory.kt:80)
E/MethodChannel#flutter/platform_views(17449): 	at io.agora.agora_rtc_engine.AgoraSurfaceView.<init>(AgoraSurfaceViewFactory.kt:40)
E/MethodChannel#flutter/platform_views(17449): 	at io.agora.agora_rtc_engine.AgoraSurfaceViewFactory.create(AgoraSurfaceViewFactory.kt:23)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.plugin.platform.SingleViewPresentation.onCreate(SingleViewPresentation.java:186)
E/MethodChannel#flutter/platform_views(17449): 	at android.app.Dialog.dispatchOnCreate(Dialog.java:419)
E/MethodChannel#flutter/platform_views(17449): 	at android.app.Dialog.show(Dialog.java:313)
E/MethodChannel#flutter/platform_views(17449): 	at android.app.Presentation.show(Presentation.java:257)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.plugin.platform.VirtualDisplayController.<init>(VirtualDisplayController.java:95)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.plugin.platform.VirtualDisplayController.create(VirtualDisplayController.java:48)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.plugin.platform.PlatformViewsController$1.createVirtualDisplayForPlatformView(PlatformViewsController.java:207)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.create(PlatformViewsChannel.java:104)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.embedding.engine.systemchannels.PlatformViewsChannel$1.onMethodCall(PlatformViewsChannel.java:59)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/MethodChannel#flutter/platform_views(17449): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/MethodChannel#flutter/platform_views(17449): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter/platform_views(17449): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter/platform_views(17449): 	at android.os.Looper.loop(Looper.java:183)
E/MethodChannel#flutter/platform_views(17449): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/MethodChannel#flutter/platform_views(17449): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter/platform_views(17449): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/MethodChannel#flutter/platform_views(17449): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Smartphone (please complete the following information):**
 - Device: Android 11 Emulator

**Additional context**

**Comment by LichKing-2234** [comment]
you may miss `uid` in `SurfaceView`

**Comment by wheel1992** [comment]
> you may miss `uid` in `SurfaceView`

Hi @LichKing-2234 , thought that `RtcLocalView.SurfaceView()` does not need `uid`?

**Comment by LichKing-2234** [comment]
@wheel1992 `RtcLocalView.SurfaceView()` set uid = 0 by itself.

**Comment by wheel1992** [comment]
> @wheel1992 `RtcLocalView.SurfaceView()` set uid = 0 by itself.

Oic, currently, my user with `uid=13` is the host and would like to view his/her current view.

How do we show current uid `SurfaceView`?

Is it using `RtcRemoteView.SurfaceView(uid: 13);`

**Comment by LichKing-2234** [comment]
have you tried our quickstart?

**Comment by wheel1992** [comment]
Hi @LichKing-2234 ,

In QuickStart https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/blob/1fe227d9b3cc52409f92696764e2010323883073/lib/src/pages/call.dart#L113,

`RtcLocalView.SurfaceView()` does not have uid.

Similar, in this repository example folder https://github.com/AgoraIO/Flutter-SDK/blob/532f3f80af1c611fb27e1e0797ce705cf4ecd2aa/example/lib/main.dart#L95,

`RtcLocalView.SurfaceView()` does not have uid too.

I do know that `RtcRemoteView.SurfaceView(uid: ...)` requires uid. 

My issue is showing the local surface view (the host who is broadcasting on him/her device).

**Comment by LichKing-2234** [comment]
> have you tried our quickstart?

I means is our quickstart working on your device.

**Comment by LichKing-2234** [comment]
> Hi @LichKing-2234 ,
> 
> In QuickStart
> https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/blob/1fe227d9b3cc52409f92696764e2010323883073/lib/src/pages/call.dart#L113
> 
> `RtcLocalView.SurfaceView()` does not have uid.
> 
> Similar, in this repository example folder
> https://github.com/AgoraIO/Flutter-SDK/blob/532f3f80af1c611fb27e1e0797ce705cf4ecd2aa/example/lib/main.dart#L95
> 
> `RtcLocalView.SurfaceView()` does not have uid too.
> 
> I do know that `RtcRemoteView.SurfaceView(uid: ...)` require `uid`.
> 
> My issue is showing the local surface view (the host who is broadcasting with him/her device).
> 
> The host has a custom `uid=13` and not using the default `uid=0`.

yes, `RtcLocalView` do not need to set uid, but `RtcLocalView` need it.

**Comment by wheel1992** [comment]
Hi @LichKing-2234 , the quickstart is working on our device.

It could be something wrong with our implementation.

Thank you for taking your time! 👍
