### ISSUE TITLE
When connected to a headphone with voice cancellation, sound from outside (noise, and extremely) could be heard on the other end.

### ISSUE THREAD

**Issue by kadariyaujwal** [AgoraIO/Flutter-SDK#217]
First, two devices are physically very far.
This was not issue/ occurred very less frequently in previous version (1.0.7) of agora sdk.

When headphones are connected to device (ios/android), noise from background is extremely loud. When headphones are removed, the noise is not heard/extremely low.

To reproduce:
Using latest version of agora sdk, make a call with flutter demo project by connecting headphones, and play some music in background. When headphones are removed, the background noise is not heard.

What was expected was that when we connected headphones, the background noise should have been minimal or should not have been heard.

**Smartphone (please complete the following information):**
 - Device: All Android and Ios Devices
 -Version:3.1.3/3.1.4-rc.0

**Comment by LichKing-2234** [comment]
you mean 3.0.1 is working, but 3.1.3 or later is not working?

by the way, which headphones you used.

**Comment by kadariyaujwal** [comment]
@LichKing-2234 My bad, it was actually 1.0.7 Version. Yes, 1.0.7 was working as expected. Sony WH1000XM3 headphone & Some other headphones too. I can confirm it's not headphone issue because it's working normal in skype or other apps.

**Comment by kadariyaujwal** [comment]
It was because of setting channel mode to LIVE_BROADCASTING. Worked fine After updating to COMMUNICATION.
