### ISSUE TITLE
setEnableSpeakerphone(true) doesnt work on ios devices

### ISSUE THREAD

**Issue by Aliharu** [AgoraIO/Flutter-SDK#22]
Im trying to get audio calls to use the speakerphone but the command to do so does nothing on ios devices. 

AgoraRtcEngine.setEnableSpeakerphone(true);
    AgoraRtcEngine.isSpeakerphoneEnabled().then((value) {
      print(value);  //This returns true but on ios it still uses the earpiece speaker.
    });

**Comment by plutoless** [comment]
did you do it after joining channel?

**Comment by Aliharu** [comment]
I tried it before and after joining channel.

**Comment by plutoless** [comment]
could you pls show me your code snippet if possible?

**Comment by Aliharu** [comment]
```
  void initialize() {
    _initAgoraRtcEngine();
    _addAgoraEventHandlers();
      setupChannel();
      joinChannel();
  }
  void setupChannel() {
    AgoraRtcEngine.setEnableSpeakerphone(true); //Trying to do before join channel
  }

  void joinChannel() async {
    AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
    AgoraRtcEngine.setEnableSpeakerphone(true); //Trying to join after
  }

I tried in both spots on separate attempt.  Neither works on IOS
```

**Comment by plutoless** [comment]
@Aliharu try doing it after receiving onJoinChannelSuccess callback.

**Comment by Aliharu** [comment]
Just tried
```
  void joinChannel() async {
    AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0).then((value) {
      AgoraRtcEngine.setEnableSpeakerphone(true);
    });
  }
and 
  void joinChannel() async {
    await AgoraRtcEngine.joinChannel(null, widget.channelName, null, 0);
    AgoraRtcEngine.setEnableSpeakerphone(true);
  }
```
Still uses earpiece on IOS

**Comment by plutoless** [comment]
@Aliharu calling async on joinChannel simply means the api call was transmitted to native side and returned with a return value
To listen to joinchannelsuccess callback you will need to do sth like this:
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/blob/87a097c4d07f01555c0cf4832ee9a8c87f7f27e2/lib/src/pages/call.dart#L79

**Comment by Aliharu** [comment]
Okay looks like that works.  Thank you.
