### ISSUE TITLE
Old version

### ISSUE THREAD

**Issue by topfreeworker123** [AgoraIO/Flutter-SDK#222]
Hello
I want to check if old agora_rtc_engine is running now.
For example, I am using version 1.0.13 agora_rtc_engine for video call .
But it does not run now.
Please help me

**Comment by LichKing-2234** [comment]
any log about it?

**Comment by topfreeworker123** [comment]
sorry,I have fixed it myself.
Thanks for your reply and interesting.

**Comment by LichKing-2234** [comment]
Maybe you can share the details of the question for others to refer to, thanks.
