### ISSUE TITLE
新增对setLocalVoiceChanger(本地变声)的支持

### ISSUE THREAD

**Issue by unclexiao** [AgoraIO/Flutter-SDK#23]
当前版本（0.9.7）暂时没有[setLocalVoiceChanger](https://docs.agora.io/cn/Interactive%20Broadcast/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#ade6883c7878b7a596d5b2563462597dd)，请问是否考虑新增支持？

- VOICE_CHANGER_OFF(0)：原声，即关闭本地语音变声
- VOICE_CHANGER_OLDMAN(1)：老男孩
- VOICE_CHANGER_BABYBOY(2)：小男孩
- VOICE_CHANGER_BABYGILR(3)：小女孩
- VOICE_CHANGER_ZHUBAJIE(4)：猪八戒
- VOICE_CHANGER_ETHEREAL(5))：空灵
- VOICE_CHANGER_HULK(6))：绿巨人

**Comment by Matrixbirds** [comment]
@unclexiao 我们会在下一个版本加上的

**Comment by unclexiao** [comment]
还有目前依赖的SDK是很旧的版本了：

```
dependencies {
    implementation 'io.agora.rtc:full-sdk:2.4.1'
}
```

这个依赖库找不到**setLocalVoiceChanger**方法，但是下载2.8.0最新版的Jar包又是失败，所以我也无法写Flutter插件进行整合😅

**Comment by plutoless** [comment]
其实也没有很旧，2.4.1是2.8.0的上一个版本
我们会择期发布2.8.0的

**Comment by unclexiao** [comment]
请问一下：合并的#25 是否需要大量测试？计划什么时候同步到[pub.dev](https://pub.dev/packages/agora_rtc_engine)呢? 

现在我只能发布[tell_rtc_temp](https://pub.dev/packages/tell_rtc_temp)作为临时解决方案，期待官方尽早同步，我也好顺便关了这个PR～～ 

感激不尽🍻🍻

**Comment by plutoless** [comment]
@Matrixbirds

**Comment by Matrixbirds** [comment]
目前还有一些测试没覆盖上，这个本周五下午会发新版。 感谢关注

**Comment by Matrixbirds** [comment]
0.9.9 release了
