### ISSUE TITLE
Need Agora RTC version 2.9.0 for x86_64 arch

### ISSUE THREAD

**Issue by pavankumarkatakam** [AgoraIO/Flutter-SDK#29]
Google is now restricting to publish app only if 64 bit code should be present along with 32bit code. For the native agora rtc version 2.8.0 there is no 'x86_64' code but v2.9.0 has. so please update the agora version so that in final build we will get 64bit code as well.

**Comment by pavankumarkatakam** [comment]
Im trying to increase the version  of `io.agora.rtc:full-sdk` in `build.gradle` but getting error as below

> AgoraRtcEnginePlugin.java:673: error: method does not override or implement a method from a supertype
>         @Override                                                                                                  
>         ^                                                                                                          
> /home/storage/work/gitlab/DrDog/Flutter-SDK/android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java:675: error: method onRemoteVideoStateChanged in class IRtcEngineEventHandler cannot be applied to given types;
>             super.onRemoteVideoStateChanged(uid , state);                                                          
>                  ^                                                                                                 
>   required: int,int,int,int                                                                                        
>   found: int,int                                                                                                   
>   reason: actual and formal argument lists differ in length                                                        
> Note: /home/storage/work/gitlab/DrDog/Flutter-SDK/android/src/main/java/io/agora/agorartcengine/AgoraRtcEnginePlugin.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.                                                               
> 2 errors

**Comment by Matrixbirds** [comment]
We will release the 2.9.0 native version for flutter wrapper this week

**Comment by pavankumarkatakam** [comment]
Thanks @Matrixbirds for confirmation.

**Comment by Matrixbirds** [comment]
@pavankumarkatakam  We have released 1.0.0, you upgrade to this version.

**Comment by pavankumarkatakam** [comment]
Hi @Matrixbirds , im using the version 1.0.0 only but in the final bundle why im not getting the `x86-64` folder im getting only `arm64-v8a`, `armeabi-v7a`, `x86`

**Comment by pavankumarkatakam** [comment]
ping @Matrixbirds

**Comment by Matrixbirds** [comment]
Okay, Please provide your `flutter doctor` & compilation environment here. I will try to reproduce it.

**Comment by pavankumarkatakam** [comment]
Output of flutter doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.7.8+hotfix.4, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
[✓] Android Studio (version 3.4)
[✓] VS Code (version 1.38.0)
[✓] Connected device (1 available)

• No issues found!

```

I can provide you a sample app if required

**Comment by Matrixbirds** [comment]
Please provide your sample project here. I will try to reproduce on it.

**Comment by pavankumarkatakam** [comment]
please check this repo https://github.com/pavankumarkatakam/agora64bit,

clone and just run `flutter build appbundle`, and analyze the apk it doesnt have xs6_64 arch, please refer the attached image
![agora1_bundle](https://user-images.githubusercontent.com/6078669/64506244-75b28e00-d2f4-11e9-9cf4-f303b7401821.png)

**Comment by pavankumarkatakam** [comment]
Did you checked @Matrixbirds

**Comment by pavankumarkatakam** [comment]
But when i build the sample project and analyze the bundle then it is showing x86-64 arch
![agora_sample](https://user-images.githubusercontent.com/6078669/64677527-5b63e600-d495-11e9-8cea-bd60de928fa5.png)

**Comment by Matrixbirds** [comment]
I have checked and cannot reproduce it, I think probably you did some gradle cache when you did build it again.
