### ISSUE TITLE
setLocalVideoMirrorMode?

### ISSUE THREAD

**Issue by Aliharu** [AgoraIO/Flutter-SDK#31]
I see a setLocalVideoMirrorMode function the Java API reference there doesn't seem to be a way to use it in the flutter plugin.  Is there any plans to add this as functionality?

**Comment by Matrixbirds** [comment]
Yes, We have already schedule it on the next version roadmap. And also support more functional that native SDK already support. If you have more proposal like u mentioned, you could keep ping me.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
