### ISSUE TITLE
Flutter android 打 release 包打开后 crash 附  catlog 【已解决】

### ISSUE THREAD

**Issue by zhangdszq** [AgoraIO/Flutter-SDK#32]
```java
def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystorePropertiesFile = rootProject.file("key.properties")
def keystoreProperties = new Properties()
keystoreProperties.load(new FileInputStream(keystorePropertiesFile))

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {

        applicationId "com.flywheel.lemon_english"
        minSdkVersion 28
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            //选择要添加的对应 cpu 类型的 .so 库。
            abiFilters 'armeabi-v7a'            // 还可以添加
        }

       
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }

    buildTypes {
        // release {
        // TODO: Add your own signing config for the release build.
        // Signing with the debug keys for now, so `flutter run --release` works.
        //  signingConfig signingConfigs.debug
        //}

        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'
}

```

**cat log**
============

9-18 20:32:06.623  1929  1929 D EventBus: [1929, u0] send(AppTransitionFinishedEvent)
09-18 20:32:06.623  1929  1929 D EventBus: [1929, u0]  -> ForcedResizableInfoActivityController [0x6d65460, P1] onBusEvent(AppTransitionFinishedEvent)
09-18 20:32:06.623  1929  1929 D EventBus: [1929, u0] onBusEvent(AppTransitionFinishedEvent) duration: 3 microseconds, avg: 1293
09-18 20:32:06.623  1929  1929 D GestureStubView: resetRenderProperty: showGestureStub
09-18 20:32:06.623  1929  1929 D GestureStubView: showGestureStub
09-18 20:32:06.623  1929  1929 D GestureStubView: resetRenderProperty: showGestureStub
09-18 20:32:06.623  1929  1929 D GestureStubView: showGestureStub
09-18 20:32:06.626 16687 16687 E l.lemon_englis: ----- class 'Lio/agora/rtc/internal/RtcEngineImpl;' cl=0x13084040 -----
09-18 20:32:06.626 16687 16687 E l.lemon_englis:   objectSize=405 (120 from super)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:   access=0x8008.0001
09-18 20:32:06.626 16687 16687 E l.lemon_englis:   super='java.lang.Class<io.agora.rtc.c>' (cl=0x13084040)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:   vtable (58 entries, 0 in super):
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      0: int io.agora.rtc.internal.RtcEngineImpl.a(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      1: int io.agora.rtc.internal.RtcEngineImpl.a(int, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      2: int io.agora.rtc.internal.RtcEngineImpl.a(int, boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      3: int io.agora.rtc.internal.RtcEngineImpl.a(io.agora.rtc.a.b)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      4: int io.agora.rtc.internal.RtcEngineImpl.a(io.agora.rtc.video.c)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      5: int io.agora.rtc.internal.RtcEngineImpl.a(io.agora.rtc.video.d)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      6: int io.agora.rtc.internal.RtcEngineImpl.a(java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      7: int io.agora.rtc.internal.RtcEngineImpl.a(java.lang.String, io.agora.rtc.a.a)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      8: int io.agora.rtc.internal.RtcEngineImpl.a(java.lang.String, java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      9: int io.agora.rtc.internal.RtcEngineImpl.a(java.lang.String, java.lang.String, java.lang.String, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     10: int io.agora.rtc.internal.RtcEngineImpl.a(java.lang.String, boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     11: int io.agora.rtc.internal.RtcEngineImpl.a(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     12: int io.agora.rtc.internal.RtcEngineImpl.a(boolean, io.agora.rtc.video.b)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     13: void io.agora.rtc.internal.RtcEngineImpl.a(io.agora.rtc.a)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     14: void io.agora.rtc.internal.RtcEngineImpl.a(boolean, boolean, boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     15: int io.agora.rtc.internal.RtcEngineImpl.b()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     16: int io.agora.rtc.internal.RtcEngineImpl.b(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     17: int io.agora.rtc.internal.RtcEngineImpl.b(int, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     18: int io.agora.rtc.internal.RtcEngineImpl.b(int, boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     19: int io.agora.rtc.internal.RtcEngineImpl.b(io.agora.rtc.video.c)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     20: int io.agora.rtc.internal.RtcEngineImpl.b(java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     21: int io.agora.rtc.internal.RtcEngineImpl.b(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     22: void io.agora.rtc.internal.RtcEngineImpl.b(android.content.Context, java.lang.String, io.agora.rtc.a)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     23: int io.agora.rtc.internal.RtcEngineImpl.c()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     24: int io.agora.rtc.internal.RtcEngineImpl.c(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     25: int io.agora.rtc.internal.RtcEngineImpl.c(int, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     26: int io.agora.rtc.internal.RtcEngineImpl.c(java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     27: int io.agora.rtc.internal.RtcEngineImpl.c(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     28: int io.agora.rtc.internal.RtcEngineImpl.d()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     29: int io.agora.rtc.internal.RtcEngineImpl.d(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     30: int io.agora.rtc.internal.RtcEngineImpl.d(int, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     31: int io.agora.rtc.internal.RtcEngineImpl.d(java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     32: int io.agora.rtc.internal.RtcEngineImpl.d(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     33: int io.agora.rtc.internal.RtcEngineImpl.e()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     34: int io.agora.rtc.internal.RtcEngineImpl.e(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     35: int io.agora.rtc.internal.RtcEngineImpl.e(int, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     36: int io.agora.rtc.internal.RtcEngineImpl.e(java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     37: int io.agora.rtc.internal.RtcEngineImpl.e(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     38: int io.agora.rtc.internal.RtcEngineImpl.f()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     39: int io.agora.rtc.internal.RtcEngineImpl.f(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     40: int io.agora.rtc.internal.RtcEngineImpl.f(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     41: void io.agora.rtc.internal.RtcEngineImpl.finalize()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     42: int io.agora.rtc.internal.RtcEngineImpl.g()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     43: int io.agora.rtc.internal.RtcEngineImpl.g(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     44: int io.agora.rtc.internal.RtcEngineImpl.g(java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     45: int io.agora.rtc.internal.RtcEngineImpl.g(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     46: int io.agora.rtc.internal.RtcEngineImpl.h()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     47: int io.agora.rtc.internal.RtcEngineImpl.h(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     48: int io.agora.rtc.internal.RtcEngineImpl.h(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     49: int io.agora.rtc.internal.RtcEngineImpl.i()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     50: int io.agora.rtc.internal.RtcEngineImpl.i(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     51: int io.agora.rtc.internal.RtcEngineImpl.i(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     52: int io.agora.rtc.internal.RtcEngineImpl.j(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     53: boolean io.agora.rtc.internal.RtcEngineImpl.j()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     54: int io.agora.rtc.internal.RtcEngineImpl.k()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     55: int io.agora.rtc.internal.RtcEngineImpl.k(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     56: int io.agora.rtc.internal.RtcEngineImpl.l(boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     57: void io.agora.rtc.internal.RtcEngineImpl.o()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:   direct methods (54 entries):
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      0: void io.agora.rtc.internal.RtcEngineImpl.<clinit>()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      1: void io.agora.rtc.internal.RtcEngineImpl.<init>(android.content.Context, java.lang.String, io.agora.rtc.a)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      2: int io.agora.rtc.internal.RtcEngineImpl.a(android.content.Context, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      3: int io.agora.rtc.internal.RtcEngineImpl.a(java.lang.String, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      4: java.lang.String io.agora.rtc.internal.RtcEngineImpl.a(java.lang.String, java.lang.Object[])
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      5: void io.agora.rtc.internal.RtcEngineImpl.a(android.content.Context, java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      6: void io.agora.rtc.internal.RtcEngineImpl.a(io.agora.rtc.internal.RtcEngineImpl, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      7: boolean io.agora.rtc.internal.RtcEngineImpl.a(io.agora.rtc.internal.RtcEngineImpl)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      8: int io.agora.rtc.internal.RtcEngineImpl.b(java.lang.String, java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:      9: int io.agora.rtc.internal.RtcEngineImpl.b(java.lang.String, boolean)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     10: void io.agora.rtc.internal.RtcEngineImpl.b(android.content.Context)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     11: int io.agora.rtc.internal.RtcEngineImpl.c(java.lang.String, java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     12: void io.agora.rtc.internal.RtcEngineImpl.c(android.content.Context)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     13: int io.agora.rtc.internal.RtcEngineImpl.d(android.content.Context)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     14: int io.agora.rtc.internal.RtcEngineImpl.f(int, int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     15: boolean io.agora.rtc.internal.RtcEngineImpl.f(java.lang.String)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     16: void io.agora.rtc.internal.RtcEngineImpl.j(int)
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     17: void io.agora.rtc.internal.RtcEngineImpl.m()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     18: boolean io.agora.rtc.internal.RtcEngineImpl.n()
09-18 20:32:06.626 16687 16687 E l.lemon_englis:     19: int io.agora.rtc.internal.RtcEngineImpl.nativeAddInjectStreamUrl(long, java.lang.String, byte[])
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     20: int io.agora.rtc.internal.RtcEngineImpl.nativeAddPublishStreamUrl(long, java.lang.String, boolean)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     21: int io.agora.rtc.internal.RtcEngineImpl.nativeClassInit()
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     22: int io.agora.rtc.internal.RtcEngineImpl.nativeDestroy(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     23: int io.agora.rtc.internal.RtcEngineImpl.nativeDisableVideo(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     24: int io.agora.rtc.internal.RtcEngineImpl.nativeEnableLocalAudio(long, boolean)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     25: int io.agora.rtc.internal.RtcEngineImpl.nativeEnableVideo(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     26: int io.agora.rtc.internal.RtcEngineImpl.nativeGetConncetionState(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     27: java.lang.String io.agora.rtc.internal.RtcEngineImpl.nativeGetSdkVersion()
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     28: boolean io.agora.rtc.internal.RtcEngineImpl.nativeIsSpeakerphoneEnabled(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     29: int io.agora.rtc.internal.RtcEngineImpl.nativeJoinChannel(long, byte[], java.lang.String, java.lang.String, java.lang.String, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     30: int io.agora.rtc.internal.RtcEngineImpl.nativeLeaveChannel(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     31: int io.agora.rtc.internal.RtcEngineImpl.nativeLog(int, java.lang.String)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     32: int io.agora.rtc.internal.RtcEngineImpl.nativeMuteAllRemoteVideoStreams(long, boolean)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     33: int io.agora.rtc.internal.RtcEngineImpl.nativeMuteLocalVideoStream(long, boolean)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     34: long io.agora.rtc.internal.RtcEngineImpl.nativeObjectInit(java.lang.Object, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     35: int io.agora.rtc.internal.RtcEngineImpl.nativeRemoveInjectStreamUrl(long, java.lang.String)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     36: int io.agora.rtc.internal.RtcEngineImpl.nativeRemovePublishStreamUrl(long, java.lang.String)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     37: int io.agora.rtc.internal.RtcEngineImpl.nativeSetAudioProfile(long, int, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     38: int io.agora.rtc.internal.RtcEngineImpl.nativeSetBeautyEffectOptions(long, boolean, int, float, float, float)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     39: int io.agora.rtc.internal.RtcEngineImpl.nativeSetChannelProfile(long, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     40: int io.agora.rtc.internal.RtcEngineImpl.nativeSetDefaultAudioRoutetoSpeakerphone(long, boolean)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     41: int io.agora.rtc.internal.RtcEngineImpl.nativeSetEnableSpeakerphone(long, boolean)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     42: int io.agora.rtc.internal.RtcEngineImpl.nativeSetEncryptionSecret(long, java.lang.String)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     43: int io.agora.rtc.internal.RtcEngineImpl.nativeSetLiveTranscoding(long, byte[])
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     44: int io.agora.rtc.internal.RtcEngineImpl.nativeSetParameters(long, java.lang.String)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     45: int io.agora.rtc.internal.RtcEngineImpl.nativeSetRemoteUserPriority(long, int, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     46: int io.agora.rtc.internal.RtcEngineImpl.nativeSetVideoEncoderConfiguration(long, int, int, int, int, int, int, int, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     47: int io.agora.rtc.internal.RtcEngineImpl.nativeSetupVideoLocal(long, android.view.SurfaceView, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     48: int io.agora.rtc.internal.RtcEngineImpl.nativeSetupVideoRemote(long, android.view.SurfaceView, int, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     49: int io.agora.rtc.internal.RtcEngineImpl.nativeStartPreview(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     50: int io.agora.rtc.internal.RtcEngineImpl.nativeSwitchCamera(long)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     51: int io.agora.rtc.internal.RtcEngineImpl.nativeSwitchChannel(long, java.lang.String, java.lang.String)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     52: void io.agora.rtc.internal.RtcEngineImpl.p()
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     53: int io.agora.rtc.internal.RtcEngineImpl.setExtVideoSource(long, int, int)
09-18 20:32:06.627 16687 16687 E l.lemon_englis:   static fields (2 entries):
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      0: float[] io.agora.rtc.internal.RtcEngineImpl.a
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      1: boolean io.agora.rtc.internal.RtcEngineImpl.k
09-18 20:32:06.627 16687 16687 E l.lemon_englis:   instance fields (16 entries):
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      0: int io.agora.rtc.internal.RtcEngineImpl.b
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      1: boolean io.agora.rtc.internal.RtcEngineImpl.c
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      2: boolean io.agora.rtc.internal.RtcEngineImpl.d
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      3: int io.agora.rtc.internal.RtcEngineImpl.e
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      4: int io.agora.rtc.internal.RtcEngineImpl.f
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      5: android.view.OrientationEventListener io.agora.rtc.internal.RtcEngineImpl.g
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      6: long io.agora.rtc.internal.RtcEngineImpl.h
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      7: int io.agora.rtc.internal.RtcEngineImpl.i
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      8: long io.agora.rtc.internal.RtcEngineImpl.j
09-18 20:32:06.627 16687 16687 E l.lemon_englis:      9: java.util.concurrent.ConcurrentHashMap io.agora.rtc.internal.RtcEngineImpl.l
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     10: io.agora.rtc.a$a io.agora.rtc.internal.RtcEngineImpl.m
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     11: android.net.wifi.WifiManager$WifiLock io.agora.rtc.internal.RtcEngineImpl.n
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     12: int io.agora.rtc.internal.RtcEngineImpl.o
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     13: int io.agora.rtc.internal.RtcEngineImpl.p
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     14: java.lang.ref.WeakReference io.agora.rtc.internal.RtcEngineImpl.q
09-18 20:32:06.627 16687 16687 E l.lemon_englis:     15: int io.agora.rtc.internal.RtcEngineImpl.r
09-18 20:32:06.627 16687 16687 E l.lemon_englis:
09-18 20:32:06.627 16687 16687 E l.lemon_englis: Failed to register native method io.agora.rtc.internal.RtcEngineImpl.nativeGetParameters(JLjava/lang/String;)Ljava/lang/String; in /data/app/com.flywheel.lemon_english-NI3NueZAJPQ5rSyfYiIk7A==/base.apk
09-18 20:32:06.628 16687 16687 E flutter : [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: no static or non-static method "Lio/agora/rtc/internal/RtcEngineImpl;.nativeGetParameters(JLjava/lang/String;)Ljava/lang/String;"
09-18 20:32:06.628 16687 16687 E flutter : 	at java.lang.Runtime.nativeLoad(Native Method)
09-18 20:32:06.628 16687 16687 E flutter : 	at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
09-18 20:32:06.628 16687 16687 E flutter : 	at java.lang.System.loadLibrary(System.java:1669)
09-18 20:32:06.628 16687 16687 E flutter : 	at io.agora.rtc.internal.RtcEngineImpl.m(Unknown Source:5)
09-18 20:32:06.628 16687 16687 E flutter : 	at io.agora.rtc.internal.RtcEngineImpl.n(Unknown Source:7)
09-18 20:32:06.628 16687 16687 E flutter : 	at io.agora.rtc.b.a(Unknown Source:5)
09-18 20:32:06.628 16687 16687 E flutter : 	at io.agora.a.c.onMethodCall(Unknown Source:2581)
09-18 20:32:06.628 16687 16687 E flutter : 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
09-18 20:32:06.628 16687 16687 E flutter : 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:59)
09-18 20:32:06.628 16687 16687 E flutter : 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:6)
09-18 20:32:06.628 16687 16687 E flutter : 	at android.os.MessageQueue.nativePollOnce(Native Method)
09-18 20:32:06.628 16687 16687 E flutter : 	at android.os.MessageQueue.next(MessageQueue.java:326)
09-18 20:32:06.628 16687 16687 E flutter : 	at android.os.Looper.loop(Looper.java:165)
09-18 20:32:06.628 16687 16687 E flutter : 	at android.app.ActivityThread.main(ActivityThread.java:6806)
09-18 20:32:06.628 16687 16687 E flutter : 	at java.lang.reflect.Method.invoke(Native Method)
09-18 20:32:06.628 16687 16687 E flutter : 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
09-18 20:32:06.628 16687 16687 E flutter : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
09-18 20:32:06.628 16687 16687 E flutter :
09-18 20:32:06.628 16687 16687 F flutter : [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
09-18 20:32:06.628 16687 16687 F libc    : Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 16687 (l.lemon_english), pid 16687 (l.lemon_english)
09-18 20:32:06.638  1929  1929 D GestureStubView: gatherTransparentRegion: need render w:54  h:1348
09-18 20:32:06.641  1929  1929 D GestureStubView: gatherTransparentRegion: need render w:54  h:1348
09-18 20:32:06.712 16747 16747 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
09-18 20:32:06.712   972   972 I /system/bin/tombstoned: received crash request for pid 16687
09-18 20:32:06.713 16747 16747 I crash_dump32: performing dump of process 16687 (target tid = 16687)
09-18 20:32:06.722 16747 16747 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-18 20:32:06.722 16747 16747 F DEBUG   : Build fingerprint: 'Xiaomi/dipper/dipper:9/PKQ1.180729.001/9.3.1:user/release-keys'
09-18 20:32:06.723 16747 16747 F DEBUG   : Revision: '0'
09-18 20:32:06.723 16747 16747 F DEBUG   : ABI: 'arm'
09-18 20:32:06.723 16747 16747 F DEBUG   : pid: 16687, tid: 16687, name: l.lemon_english  >>> com.flywheel.lemon_english <<<
09-18 20:32:06.723 16747 16747 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
09-18 20:32:06.723 16747 16747 F DEBUG   : Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
09-18 20:32:06.723 16747 16747 F DEBUG   : '
09-18 20:32:06.723 16747 16747 F DEBUG   :     r0  00000000  r1  0000412f  r2  00000006  r3  00000008
09-18 20:32:06.723 16747 16747 F DEBUG   :     r4  0000412f  r5  0000412f  r6  ff8ac3c4  r7  0000010c

**Comment by zhangdszq** [comment]
感谢~ 我在 proguard-rules.pro 中加了  `-keep class io.agora.** { *; }` 解决了

**Comment by himiku** [comment]
thanks bruh.. its work for me too...

**Comment by duongtruong12** [comment]
did anyone of you guys face issue crashes on ios when video call?

> thanks bruh.. its work for me too...

**Comment by h1amza** [comment]
where is proguard-rules.pro file in android studio  ???

**Comment by Malkhansingh4883** [comment]
> where is proguard-rules.pro file in android studio ???

create proguard-rules.pro file in android/app folder
