### ISSUE TITLE
use voice call only?

### ISSUE THREAD

**Issue by mshanak** [AgoraIO/Flutter-SDK#33]
hello
can i use this sdk to make voice calls only without video ?

thanks

**Comment by plutoless** [comment]
yes you can. just call disableVideo before you join channel

**Comment by mshanak** [comment]
I used this plugin for voice call
Every thing works fine 


Thank you

**Comment by Ufuk94** [comment]
> yes you can. just call disableVideo before you join channel

@plutoless Hi, I have a question regarding the pricing: disabling video will only count as voice minutes right?

**Comment by LichKing-2234** [comment]
@Ufuk94 sure
