### ISSUE TITLE
onLocalVideoStateChanged 方法回调类型错误，无法解析

### ISSUE THREAD

**Issue by seemelala** [AgoraIO/Flutter-SDK#40]
case 'onLocalVideoStateChanged':
        if (onLocalVideoStateChanged != null) {
          onLocalVideoStateChanged(map['localVideoState'], map['errorCode']);
        }
        break;

**Comment by Matrixbirds** [comment]
可以提供一下报错堆栈吗？

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
