### ISSUE TITLE
setLiveTranscoding - VideoCodecProfileType - Array of out bounds

### ISSUE THREAD

**Issue by EdwindTay** [AgoraIO/Flutter-SDK#41]
In Android, when I use setLiveTranscoding, I'm hitting the below error:

```
E/MethodChannel#agora_rtc_engine( 6273): java.lang.ArrayIndexOutOfBoundsException: length=3; index=100
E/MethodChannel#agora_rtc_engine( 6273):        at io.agora.agorartcengine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.java:512)
```

The particular line which throws the error:
`transcoding.videoCodecProfile = LiveTranscoding.VideoCodecProfileType.values()[(int) params.get("videoCodecProfile")];`

The issue:
In Agora SDK, VideoCodecProfileType enum has the following members:
BASELINE =(66)
MAIN =(77)
HIGH =(100)

In the Agora Flutter SDK, when it's invoking setLiveTranscoding platform channel method, its resolving the VideoCodecProfileType enum to its int value.
```
Map<AgoraVideoCodecProfileType, int> _resolveVideoCodecProfileType = {
  AgoraVideoCodecProfileType.BaseLine: 66,
  AgoraVideoCodecProfileType.Main: 77,
  AgoraVideoCodecProfileType.High: 100
};
```
The particular line 512 is trying to resolve the int value back to the enum by using the ordinal of the enum, which causes the ArrayIndexOutOfBoundsException.

**Comment by Matrixbirds** [comment]
thx for feedback, We will fix it ASAP.

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
