### ISSUE TITLE
setLiveTranscoding - Casting alpha field from Integer to float error

### ISSUE THREAD

**Issue by EdwindTay** [AgoraIO/Flutter-SDK#43]
When I call setLiveTranscoding, I'm hitting the following error:

```
E/MethodChannel#agora_rtc_engine( 7411): java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Float
E/MethodChannel#agora_rtc_engine( 7411):        at io.agora.agorartcengine.AgoraRtcEnginePlugin.onMethodCall(AgoraRtcEnginePlugin.java:568)
```

Particular line in question:
`user.alpha = (float) optionUser.get("alpha");`

**Comment by plutoless** [comment]
i think it's because you are providing an integer and it here failed to cast it to float directly. but i agree this is sth we should fix from sdk side.

**Comment by plutoless** [comment]
for a quick fix you can provide alpha value as float. we will fix from sdk wise

**Comment by EdwindTay** [comment]
Providing it as float causes an exception because it's defined as int value in lib/src/base.dart before being passed to the platform channel method:

```
class AgoraLiveTranscodingUser {
  int uid;
  int width;
  int height;
  int x;
  int y;
  int zOrder;
  int alpha;
  int audioChannel;
```

**Comment by LichKing-2234** [comment]
setLiveTranscoding
