### ISSUE TITLE
Flutter怎么制作类似android悬浮窗最小化的功能

### ISSUE THREAD

**Issue by ArthurKnight** [AgoraIO/Flutter-SDK#45]
Flutter怎么制作类似android悬浮窗最小化的功能，在语音聊天，视频聊天，聊天室中退出界面，保持语音不断开，可以给点思路吗

**Comment by unclexiao** [comment]
出于平台规范，想要一直在后台运行，几乎不可能。除非申请Root权限，不然总会由于系统调度被Kill掉。

我目前的场景是只有音频，且大部分都是围观，这样更容易因为用户切换应用而失去连接。但也有规避方案，我是这么做的：
1. 保持屏幕常亮：只要用户在当前页面听音频/文字聊天，就不关闭屏幕。社区已有较好的实现了，比如[screen](https://pub.dev/packages/screen)，代码也相当简单：
```dart
import 'package:screen/screen.dart';
Screen.keepOn(true);
```
2.  监听生命周期：万一用户切出了应用，但要保证回来时恢复状态。这个Flutter有内置的服务支持，名为[AppLifecycleState](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html)，实现[WidgetsBindingObserver](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver-class.html)即可，代码如下：
```dart
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    if (state == AppLifecycleState.resumed) {
       // 重连工作
    }
  }
```

希望能给你提供一些思路，如有疑惑可以继续在此交流。 @ArthurKnight

**Comment by LichKing-2234** [comment]
you can reopen this issue if the problem still exists.
