### ISSUE TITLE
Release 打包APK错误

### ISSUE THREAD

**Issue by goodsiwen** [AgoraIO/Flutter-SDK#46]
Debug版本没有问题，但是Release APK时抱错了：
* What went wrong:                                                      
Execution failed for task ':agora_rtc_engine:verifyReleaseResources'.   
> 1 exception was raised by workers:                                    
  com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
 xxx/build/agora_rtc_engine/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/fontVariationSettings not found.
  xxxx/agora_rtc_engine/intermediates/res/merged/release/values/values.xml:238: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by plutoless** [comment]
https://github.com/Baseflow/flutter-permission-handler/issues/81#issuecomment-465058307
试试把你的app的配置修改一下再试下

**Comment by oliwenfly** [comment]
我也遇到同样的问题，一直没盖好，求指点

**Comment by unclexiao** [comment]
Android X要求SDK最低为28，改一下配置就好啦

**Comment by oliwenfly** [comment]
> Android X要求SDK最低为28，改一下配置就好啦

我的已经改成29了，报错依旧，希望能帮解决一下

**Comment by unclexiao** [comment]
@oliwenfly 不仅是你的项目（`%YOUR_PROJECT%/android/app/build.gradle`），还包括插件本身，以Mac为例位置为：
`%FLUTTER_HOME%/.pub-cache/hosted/pub.flutter-io.cn/agora_rtc_engine-1.0.1/android/build.gradle`。

清除缓存之后重新构建即可：
```bash
$ flutter clean
$ flutter build apk
```
