### ISSUE TITLE
对比 Android与IOS缺少函数

### ISSUE THREAD

**Issue by guoheping113** [AgoraIO/Flutter-SDK#47]
isCameraExposurePositionSupported
setCameraExposurePosition
isCameraAutoFocusFaceModeSupported
setCameraAutoFocusFaceModeEnabled
isCameraFocusSupported
setCameraFocusPositionInPreview
以上函数在flutterSDK中都找不到

**Comment by guoheping113** [comment]
作者都不带回复的？

**Comment by plutoless** [comment]
后续会添加，如果急的话可以提个PR加一下

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 Any progress about this issue?

**Comment by LichKing-2234** [comment]
@yukitaka13-1110 the new version is testing

**Comment by LichKing-2234** [comment]
finished
