### ISSUE TITLE
部分api还没有啊？

### ISSUE THREAD

**Issue by chenenyu** [AgoraIO/Flutter-SDK#5]
`startAudioMixing`这种比较常用的还没有支持吗？

**Comment by PRWrl** [comment]
目前只支持了核心API，其他API近期会陆续完善的

**Comment by Matrixbirds** [comment]
感谢反馈，下周会开始适配其他api，有什么需要提高优先级的可以在这里讨论 @chenenyu

**Comment by zhangdszq** [comment]
@Matrixbirds 呼叫邀请现在还没有，希望可以加上

**Comment by Matrixbirds** [comment]
@zhangdszq  你是指实时消息吗？ 可以参考[这里](https://github.com/agoraio/flutter-rtm)

**Comment by luckmlc** [comment]
@Matrixbirds 

createDataStream 
sendStreamMessage

这两个api能支持下么，业务上需要用😂

**Comment by unclexiao** [comment]
@luckmlc 我看到iOS工程的.h文件已经有了，估计gradle的依赖也包含，可以自己加上去提个PR
