### ISSUE TITLE
Provide a end to end video calling example.

### ISSUE THREAD

**Issue by prafgup** [AgoraIO/Flutter-SDK#51]
Please provide a end to end video calling example where one device is used to call other device even when app is closed in the other device .

**Comment by plutoless** [comment]
you will need to do push notification in this case, which differs based on the service you chose, especially for android.

**Comment by prafgup** [comment]
> you will need to do push notification in this case, which differs based on the service you chose, especially for android.

Assuming push notifications(Firebase or any other) are set up how do we register callbacks and incoming call ui ?

**Comment by plutoless** [comment]
https://github.com/AgoraIO/Advanced-Video/tree/master/Calling-Interface
we have one such sample for native sdk while we don't have it for flutter yet. it's system api so maybe you can try looking for any other flutter packages supporting showing this ui.

**Comment by prafgup** [comment]
I hope there is a flutter integrated version of the same in near future. As this is one of the most basic use of the agora sdk, I hope your team would like to work this out soon and provide us with a working flutter example soon .

**Comment by plutoless** [comment]
agora sdk is responsible for audio/video communication, while offline notification and calling interface is provided by 3rd party service or system. we are working on a native version of such example, but flutter one it will come later with lower priority.

**Comment by AxesandGrinds** [comment]
The priority should be higher. I spend 90% of my time working out signaling and UI for Agora use.

**Comment by plutoless** [comment]
@AxesandGrinds sorry to hear that. it would be appreciated if you can help provide some concrete problems regarding signaling and UI and we will try to improve it.

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.

**Comment by Kevy235** [comment]
> Please provide a end to end video calling example where one device is used to call other device even when app is closed in the other device .

Hi there, someone could help if there is any solution for that.

**Comment by LichKing-2234** [comment]
You can try https://pub.dev/packages/callkeep

**Comment by Kevy235** [comment]
> You can try https://pub.dev/packages/callkeep

thanks @LichKing-2234 , i'm new in flutter, could you please give the right example to follow ?
