### ISSUE TITLE
flutter build apk报错

### ISSUE THREAD

**Issue by oliwenfly** [AgoraIO/Flutter-SDK#53]
主要配置如下:
    • Flutter version 1.12.13 at /Users/oliwen/sdk/flutter
classpath 'com.android.tools.build:gradle:3.2.1'
compileSdkVersion 29

debug都正常，build就报错，很奇怪，求解决

报错如下：
* What went wrong:                                                      
Execution failed for task ':agora_rtc_engine:verifyReleaseResources'.   
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /Users/oliwen/77/77dj_app/build/agora_rtc_engine/intermediates/res/merged/release/values/values.xml:186: error: resource android:attr/fontVariationSettings not found.
  /Users/oliwen/77/77dj_app/build/agora_rtc_engine/intermediates/res/merged/release/values/values.xml:187: error: resource android:attr/ttcIndex not found.
  error: failed linking references.                                     
                                                                        
  Command: /Users/oliwen/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/e6b9d6bb1b14e5a2bc026728f7062fec/aapt2-3.2.1-4818971-osx/aapt2 link -I\

**Comment by oliwenfly** [comment]
求官方解答

**Comment by LichKing-2234** [comment]
#54 fix it
