### ISSUE TITLE
failed to build apk

### ISSUE THREAD

**Issue by MuhammedKasujja** [AgoraIO/Flutter-SDK#55]
I have failed to build the final apk on debug that works but cannot 
![Screenshot 2019-12-16 at 12 03 27](https://user-images.githubusercontent.com/40717406/70893479-3b940f00-1ffc-11ea-8b7b-3db5ffbaf5f9.png)

**Comment by MuhammedKasujja** [comment]
I have tried this more 2 weeks now but the issue is not being same case no sdk found any help

**Comment by unclexiao** [comment]
Duplicate of #46, you should update your plugin's `compileSdkVersion` from 27 to 28.

By the way , I have submit a PR(#54) to fix this problem, and waiting for merge...

**Comment by LichKing-2234** [comment]
#54 fix it
