### ISSUE TITLE
flutter sdk没有封装Log接口

### ISSUE THREAD

**Issue by huangred** [AgoraIO/Flutter-SDK#57]
E/AGORA_SDK(13447): cannot open log file for writing: agorartm.log, err=30

**Comment by plutoless** [comment]
会尽快安排补齐

**Comment by LichKing-2234** [comment]
> E/AGORA_SDK(13447): cannot open log file for writing: agorartm.log, err=30

@huangred 1.0.3版本已经加上相关接口
