### ISSUE TITLE
android9.0音量键调节无效

### ISSUE THREAD

**Issue by chenenyu** [AgoraIO/Flutter-SDK#6]
android9.0系统，在音频直播场景下，通过音量键调节音量不生效，但是其他系统是正常的，需要开发者自己处理`onKeyDown `事件吗？还是说有其他某些地方设置不对？

**Comment by PRWrl** [comment]
请问具体是什么型号手机上遇到这个问题？

**Comment by chenenyu** [comment]
小米8  用的sdk是2.3.1，通过替换sdk到2.4.0已解决。。。
