### ISSUE TITLE
VoIP Push Notification

### ISSUE THREAD

**Issue by harunB10** [AgoraIO/Flutter-SDK#60]
Is it included in the project? I mean, is it possible to show ringing screen when user A is calling user B.. Like Messenger/Viber/WhatsUp?

Thx!

**Comment by plutoless** [comment]
it has nothing todo with agora sdk. mobile device system natively support this screen. if you have no idea how to do it from native end, try looking for relevant dart packages here https://pub.dev/packages?q=callkit
