### ISSUE TITLE
Broadcast Video Black screen

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO/Flutter-SDK#62]
I receive a black screen when trying to broadcast videos.

` VideoEncoderConfiguration _configuration = VideoEncoderConfiguration();

  _handleCameraAndMicPermissions() async {
    await PermissionHandler().requestPermissions([
      PermissionGroup.camera,
      PermissionGroup.microphone,
      PermissionGroup.storage
    ]);
  }

  Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create(HBTV.API_KEY);
    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
  }

  _eventHandlers() {
    AgoraRtcEngine.onError = (error) {
      print(error);
    };

    AgoraRtcEngine.onJoinChannelSuccess = (channel, uid, elapsed) {
      print('OnJoined: $channel, uid: $uid, time: $elapsed');
    };

    AgoraRtcEngine.onFirstRemoteVideoFrame = (uid, witdh, height, elapsed) {
      print('Uid: $uid, witdh: $witdh, height: $height, time: $elapsed');
    };
  }

  Future<void> init() async {
    await _initAgoraRtcEngine();
    _eventHandlers();
  }

  @override
  void initState() {
    super.initState();
    _handleCameraAndMicPermissions();
    init();
  }

  @override
  void dispose() {
    AgoraRtcEngine.leaveChannel().then((_) {
      AgoraRtcEngine.destroy();
    });
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: Column(
          children: [
            Container(
              height: MediaQuery.of(context).size.height - 100,
              child: AgoraRtcEngine.createNativeView((viweId) {
                AgoraRtcEngine.setupLocalVideo(viweId, VideoRenderMode.Fit);
                _configuration.bitrate = 30;
                _configuration.dimensions = MediaQuery.of(context).size;
                _configuration.orientationMode =
                    VideoOutputOrientationMode.FixedPortrait;
                AgoraRtcEngine.setVideoEncoderConfiguration(_configuration);
                AgoraRtcEngine.joinChannel(null, 'flutter', null, 0);
                AgoraRtcEngine.startPreview();
              }),
            ),
          ],
        ),
      ),
    );
  }
}`

**Comment by plutoless** [comment]
please follow instructions [here](https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#reporting-an-issue) to report an issue.

**Comment by rlee1990** [comment]
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.18362.535], locale en-US)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.41.0)
[√] Connected device (1 available)

• No issues found!

**Comment by rlee1990** [comment]
@plutoless I added my flutter doctor output and added the requested line go code to my project also this is not for a video call this is for a video broadcast.

**Comment by rlee1990** [comment]
`import 'package:agora_rtc_engine/agora_rtc_engine.dart';
import 'package:flutter/material.dart';
import 'package:hbtv/utils/hbtv.dart';
import 'package:permission_handler/permission_handler.dart';
import 'dart:async';

class HostStreamView extends StatefulWidget {
  HostStreamView({Key key}) : super(key: key);

  @override
  _HostStreamViewState createState() => _HostStreamViewState();
}

class _HostStreamViewState extends State<HostStreamView> {
  VideoEncoderConfiguration _configuration = VideoEncoderConfiguration();

  _handleCameraAndMicPermissions() async {
    await PermissionHandler().requestPermissions([
      PermissionGroup.camera,
      PermissionGroup.microphone,
      PermissionGroup.storage
    ]);
  }

  Future<void> _initAgoraRtcEngine() async {
    await AgoraRtcEngine.create(HBTV.API_KEY);
    await AgoraRtcEngine.enableVideo();
    await AgoraRtcEngine.enableAudio();
    await AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    await AgoraRtcEngine.setClientRole(ClientRole.Broadcaster);
    await AgoraRtcEngine.enableWebSdkInteroperability(true);
  }

  _eventHandlers() {
    AgoraRtcEngine.onError = (error) {
      print(error);
    };

    AgoraRtcEngine.onJoinChannelSuccess = (channel, uid, elapsed) {
      print('OnJoined: $channel, uid: $uid, time: $elapsed');
    };

    AgoraRtcEngine.onFirstRemoteVideoFrame = (uid, witdh, height, elapsed) {
      print('Uid: $uid, witdh: $witdh, height: $height, time: $elapsed');
    };

    AgoraRtcEngine.onFirstRemoteVideoFrame = (uid, width, height, time) {
      print(uid);
    };
  }

  Future<void> init() async {
    await _initAgoraRtcEngine();
    _eventHandlers();
    AgoraRtcEngine.setParameters('{\"che.video.lowBitRateStreamParameter\":{\"width\":320,\"height\":180,\"frameRate\":15,\"bitRate\":140}}');
    AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");
  }

  @override
  void initState() {
    super.initState();
    _handleCameraAndMicPermissions();
    init();
  }

  @override
  void dispose() {
    AgoraRtcEngine.leaveChannel().then((_) {
      AgoraRtcEngine.destroy();
    });
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Container(
        child: Column(
          children: [
            Container(
              height: MediaQuery.of(context).size.height - 100,
              child: AgoraRtcEngine.createNativeView((viweId) {
                AgoraRtcEngine.setupLocalVideo(viweId, VideoRenderMode.Fit).then((a) {
                  _configuration.bitrate = 30;
                _configuration.dimensions = MediaQuery.of(context).size;
                _configuration.orientationMode =
                    VideoOutputOrientationMode.FixedPortrait;
                AgoraRtcEngine.setVideoEncoderConfiguration(_configuration);
                AgoraRtcEngine.startPreview().then((p) {
                  AgoraRtcEngine.joinChannel(null, 'flutter', null, 0);
                });
                });
              }),
            ),
          ],
        ),
      ),
    );
  }
}`

**Comment by rlee1990** [comment]
Launching lib\main.dart on SM N950U in debug mode...
I/flutter ( 9351): OnJoined: flutter, uid: -1159979276, time: 1044
√ Built build\app\outputs\apk\debug\app-debug.apk.
I/flutter (10115): OnJoined: flutter, uid: 697494085, time: 913

**Comment by rlee1990** [comment]
[terminal.txt](https://github.com/AgoraIO/Flutter-SDK/files/3992840/terminal.txt)

**Comment by plutoless** [comment]
your terminal.txt does not include any of our sdk logs.
from your code it seems you are not escaping the parameters:

*Correct*
AgoraRtcEngine.setParameters("{\"rtc.log_filter\": 65535}");

*Yours*
AgoraRtcEngine.setParameters("{"rtc.log_filter": 65535}");

**Comment by rlee1990** [comment]
@plutoless im not seeing a difference between my code and what your asking me to add. When I run the project the audio works just fine but just not the video. Do you have an example using the video broadcasting?

**Comment by plutoless** [comment]
looks like my code was escaped. now looks proper

**Comment by rlee1990** [comment]
Any clue as to what could be the issue? The only thing I have not tried yet but will today is to use an older version on the sdk @plutoless

**Comment by plutoless** [comment]
w/o your sdk log i can hardly judge

**Comment by rlee1990** [comment]
I have ran flutter doctor and ran flutter run —verbose to try to get a log not sure how else to get a log to show.

**Comment by rlee1990** [comment]
I see there was an update today I will try that later today and see if it prints a proper log. @plutoless

**Comment by plutoless** [comment]
i need our sdk log, not flutter doctor output. i saw your flutter doctor output is fine.

**Comment by rlee1990** [comment]
Okay that should show when I run the project with the code you requested me to add correct? @plutoless

**Comment by plutoless** [comment]
yep. in your console

**Comment by rlee1990** [comment]
Okay @plutoless i will run the project again today and see what happens and let you know

**Comment by rlee1990** [comment]
@plutoless I have tried everything while in flutter even added `AgoraRtcEngine.setLogFilter(65535);` and still there are not any logs showing when a run the flutter application. There has to be a reason why audio is working but not video.

**Comment by plutoless** [comment]
usually if audio is working but video is not, there could be multiple reasons:
1. rendering view is not properly set
2. permission is not properly granted
if setting 65535 is not working for you, could you pls upgrade to latest version and use setLogFile with log file path to save our sdk log to your sdk or somewhere you know so that you can grab it?

**Comment by rlee1990** [comment]
@plutoless Here is the log using the above option
[agorasdk.log](https://github.com/AgoraIO/Flutter-SDK/files/3999151/agorasdk.log)
