### ISSUE TITLE
Flutter: Execution failed for task ':package_info:verifyReleaseResources'

### ISSUE THREAD

**Issue by bobanminic96** [AgoraIO/Flutter-SDK#65]
On building debug and release APK, same issue.
Prevously i created signed apk with compileSdkVersion 28 successfully, so it is already set on 28.

I tried to solve it with: #42310 #27226 #47337 but no success.

> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  [PATH]\flutter\mobile_client\build\package_info\intermediates\res\merged\release\values\values.xml:236: error: resource android:attr/fontVariationSettings not found.
  [PATH]\flutter\mobile_client\build\package_info\intermediates\res\merged\release\values\values.xml:237: error: resource android:attr/ttcIndex not found.

  error: failed linking references.

**Comment by plutoless** [comment]
please upgrade to 1.0.3
i believe it's fixed by [this commit](https://github.com/AgoraIO/Flutter-SDK/pull/54)
