### ISSUE TITLE
setLocalVoiceReverbPreset

### ISSUE THREAD

**Issue by guoheping113** [AgoraIO/Flutter-SDK#66]
AUDIO_REVERB_OFF(0)：原声，即关闭本地语音混响 
AUDIO_REVERB_POPULAR(1)：流行 
AUDIO_REVERB_RNB(2)：R&B 
AUDIO_REVERB_ROCK(3)：摇滚 
AUDIO_REVERB_HIPHOP(4)：嘻哈 
AUDIO_REVERB_VOCAL_CONCERT(5)：演唱会 
AUDIO_REVERB_KTV(6)：KTV 
AUDIO_REVERB_STUDIO(7)：录音棚 

flutter中 定义不了解？
enum AgoraAudioReverbType {
  AgoraAudioReverbDryLevel,
  AgoraAudioReverbWetLevel,
  AgoraAudioReverbRoomSize,
  AgoraAudioReverbWetDelay,
  AgoraAudioReverbStrength,
}

**Comment by plutoless** [comment]
上面是预设值，下面是自定义reverb类型

**Comment by guoheping113** [comment]
flutter 没有预设值，只能自己定义



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qianze Zhang"<notifications@github.com&gt;; 
发送时间: 2019年12月23日(星期一) 晚上8:21
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] setLocalVoiceReverbPreset (#66)




上面是预设值，下面是自定义reverb类型

**Comment by plutoless** [comment]
直接用对应的int值即可
