### ISSUE TITLE
切换前后摄像头,图像会倒过来

### ISSUE THREAD

**Issue by guoheping113** [AgoraIO/Flutter-SDK#67]

**Comment by LichKing-2234** [comment]
请问用的sdk版本是多少，我这边看下

**Comment by guoheping113** [comment]
1.0.3
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 上午10:55
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




请问用的sdk版本是多少，我这边看下

**Comment by LichKing-2234** [comment]
我这边没有复现，麻烦提供下sdk log，顺便拍照看下

**Comment by guoheping113** [comment]
好的，稍等


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上8:03
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




我这边没有复现，麻烦提供下sdk log，顺便拍照看下

**Comment by guoheping113** [comment]
一闪就没有了，只能录像了，截不到图，可以吗
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上8:03
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




我这边没有复现，麻烦提供下sdk log，顺便拍照看下

**Comment by guoheping113** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上8:03
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




我这边没有复现，麻烦提供下sdk log，顺便拍照看下

**Comment by guoheping113** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arthas"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 晚上8:03
收件人:&nbsp;"AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;;
抄送:&nbsp;"Jason"<292303029@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




我这边没有复现，麻烦提供下sdk log，顺便拍照看下
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

QQ视频20191225201013.mp4 (8.61M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=7f326539e25a469987020928116102490b04075c515502021f01075b014c04550550485b5555094b5302500f035203555705505a3779303763f8b6ff825300570b03570b02530057020356175a1104660f&t=exs_ftn_download&code=22e97a0f

**Comment by LichKing-2234** [comment]
sdk log 也提供下

**Comment by guoheping113** [comment]
I/MediaCodec(10249): (0x79bb953c00) Encoder: mInputBufCnt = 15 fps, mOutputBufCnt = 15 fps, mRenderFrameCnt = 0 fps







I/MediaCodec(10249): (0x79bb953c00) Encoder: mInputBufCnt = 15 fps, mOutputBufCnt = 15 fps, mRenderFrameCnt = 0 fps







I/MediaCodec(10249): (0x79bb953c00) Encoder: mInputBufCnt = 15 fps, mOutputBufCnt = 15 fps, mRenderFrameCnt = 0 fps







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







D/*WEBRTCN*(10249): VideoRenderAndroid dtor







D/*WEBRTCN*(10249): StopRender:







D/*WEBRTCN*(10249): JavaRenderThreadProcess: Java thread detached







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







I/chatty&nbsp; (10249): uid=10181(com.newqidian.live) Thread-26707 identical 7 lines







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







D/Camera&nbsp; (10249): mHypnusCtrl is true







E/CheckPermission(10249): camera-code= 3







I/flutter (10249): 发送中心服务器心跳请求







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







I/flutter (10249): 中心服务器心跳请求成功







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







I/chatty&nbsp; (10249): uid=10181(com.newqidian.live) Thread-26713 identical 3 lines







E/libc&nbsp;&nbsp;&nbsp; (10249): Access denied finding property "vendor.camera.aux.packagelist"







D/*WEBRTCN*(10249): StartRender: thread started: 3099587824





 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上8:18
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




sdk log 也提供下

**Comment by LichKing-2234** [comment]
完整的sdk log 文件

**Comment by guoheping113** [comment]
不知道在哪里打印你需要的日志信息
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上8:22
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




完整的sdk log 文件

**Comment by LichKing-2234** [comment]
![image](https://user-images.githubusercontent.com/9312526/71445520-7e20be80-2755-11ea-9247-46e08beebc5e.png)

**Comment by guoheping113** [comment]
发的什么，没有显示出来
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上8:31
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)

**Comment by LichKing-2234** [comment]
图片，你可能需要翻墙

**Comment by LichKing-2234** [comment]
默认sdk日志在/sdcard/包名/agorasdk.log，如果你没有设置setLogFile

**Comment by guoheping113** [comment]
哦，我没有设置setLogFile


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月25日(星期三) 晚上8:36
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




默认sdk日志在/sdcard/包名/agorasdk.log，如果你没有设置setLogFile

**Comment by guoheping113** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Arthas"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月25日(星期三) 晚上8:36
收件人:&nbsp;"AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;;
抄送:&nbsp;"Jason"<292303029@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [AgoraIO/Flutter-SDK] 切换前后摄像头,图像会倒过来 (#67)




默认sdk日志在/sdcard/包名/agorasdk.log，如果你没有设置setLogFile

**Comment by LichKing-2234** [comment]
你好，没有看到你的logFile
