### ISSUE TITLE
android机型，debug调试都正常，debug的打包文件安装也正常，但是release的打包文件就闪退

### ISSUE THREAD

**Issue by oliwenfly** [AgoraIO/Flutter-SDK#68]
E/flutter ( 9431): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: no static or non-static method “Lio/agora/rtc/internal/RtcEngineImpl;.nativeAddVideoCapturer(JLio/agora/rtc/mediaio/IVideoSource;I)I”
E/flutter ( 9431): at java.lang.Runtime.nativeLoad(Native Method)
E/flutter ( 9431): at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
E/flutter ( 9431): at java.lang.System.loadLibrary(System.java:1669)
E/flutter ( 9431): at io.agora.rtc.internal.RtcEngineImpl.W(SourceFile:141)
E/flutter ( 9431): at io.agora.rtc.internal.RtcEngineImpl.X(SourceFile:147)
E/flutter ( 9431): at xb.j.a(SourceFile:59)
E/flutter ( 9431): at ub.h.a(SourceFile:108)
E/flutter ( 9431): at Ub.p$a.a(SourceFile:231)
E/flutter ( 9431): at Kb.c.a(SourceFile:93)
E/flutter ( 9431): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(SourceFile:642)
E/flutter ( 9431): at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 9431): at android.os.MessageQueue.next(MessageQueue.java:326)
E/flutter ( 9431): at android.os.Looper.loop(Looper.java:165)
E/flutter ( 9431): at android.app.ActivityThread.main(ActivityThread.java:6806)
E/flutter ( 9431): at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 9431): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/flutter ( 9431): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/flutter ( 9431):
F/flutter ( 9431): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).

agora_rtc_engine: ^1.0.3已经是最新版了
项目用到了androidX

麻烦大神看看，app等着上线，急！

**Comment by LichKing-2234** [comment]
是不是没有添加不混淆配置

**Comment by LichKing-2234** [comment]
> E/flutter ( 9431): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoSuchMethodError: no static or non-static method “Lio/agora/rtc/internal/RtcEngineImpl;.nativeAddVideoCapturer(JLio/agora/rtc/mediaio/IVideoSource;I)I”
> E/flutter ( 9431): at java.lang.Runtime.nativeLoad(Native Method)
> E/flutter ( 9431): at java.lang.Runtime.loadLibrary0(Runtime.java:1014)
> E/flutter ( 9431): at java.lang.System.loadLibrary(System.java:1669)
> E/flutter ( 9431): at io.agora.rtc.internal.RtcEngineImpl.W(SourceFile:141)
> E/flutter ( 9431): at io.agora.rtc.internal.RtcEngineImpl.X(SourceFile:147)
> E/flutter ( 9431): at xb.j.a(SourceFile:59)
> E/flutter ( 9431): at ub.h.a(SourceFile:108)
> E/flutter ( 9431): at Ub.p$a.a(SourceFile:231)
> E/flutter ( 9431): at Kb.c.a(SourceFile:93)
> E/flutter ( 9431): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(SourceFile:642)
> E/flutter ( 9431): at android.os.MessageQueue.nativePollOnce(Native Method)
> E/flutter ( 9431): at android.os.MessageQueue.next(MessageQueue.java:326)
> E/flutter ( 9431): at android.os.Looper.loop(Looper.java:165)
> E/flutter ( 9431): at android.app.ActivityThread.main(ActivityThread.java:6806)
> E/flutter ( 9431): at java.lang.reflect.Method.invoke(Native Method)
> E/flutter ( 9431): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
> E/flutter ( 9431): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
> E/flutter ( 9431):
> F/flutter ( 9431): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env).
> 
> agora_rtc_engine: ^1.0.3已经是最新版了
> 项目用到了androidX
> 
> 麻烦大神看看，app等着上线，急！

是不是没有添加不混淆配置

**Comment by LichKing-2234** [comment]
@oliwenfly 是不是没有添加不混淆配置

**Comment by oliwenfly** [comment]
org.gradle.jvmargs=-Xmx1536M

android.useAndroidX=true
android.enableJetifier=true
android.enableR8=true
这是gradle的配置，只开启了代码压缩
没有设置代码混淆

现在最新的flutter项目都是默认androidX的，建议你们能把项目切换到androidX整体测试一下可以吗？
项目急着上线，麻烦给解答一下

**Comment by oliwenfly** [comment]
> @oliwenfly 是不是没有添加不混淆配置

麻烦帮解答一下， 打包运行就闪退

**Comment by oliwenfly** [comment]
> @oliwenfly 是不是没有添加不混淆配置

能加个联系方式吗？这个sdk已经耗费我2周时间了，开始是编译不支持androidX的问题，搞了好久，现在又是打包闪退的问题，语音功能已经开发了2周时间，急着上线，求帮忙解决一下这最后一步的问题

**Comment by unclexiao** [comment]
> @oliwenfly 是不是没有添加不混淆配置

我遇到和你一模一样的问题 @oliwenfly ，确实是因为其它插件（比如[fluwx](https://github.com/OpenFlutter/fluwx/)）开启了混淆导致的，你需要改的不是`android/gradle.properties`，而是`android/app/build.gradle`，把整个项目的混淆都关掉，类似这样：

```gradle
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
        }
        debug {
            signingConfig signingConfigs.release
            minifyEnabled false
            shrinkResources false
        }
    }
```

**Comment by LichKing-2234** [comment]
@oliwenfly android.enableR8=true 这个会启用混淆，解决方案就和楼上所说

**Comment by oliwenfly** [comment]
> > @oliwenfly 是不是没有添加不混淆配置
> 
> 我遇到和你一模一样的问题 @oliwenfly ，确实是因为其它插件（比如[fluwx](https://github.com/OpenFlutter/fluwx/)）开启了混淆导致的，你需要改的不是`android/gradle.properties`，而是`android/app/build.gradle`，把整个项目的混淆都关掉，类似这样：
> 
> ```groovy-gradle
>     buildTypes {
>         release {
>             signingConfig signingConfigs.release
>             minifyEnabled false
>             shrinkResources false
>         }
>         debug {
>             signingConfig signingConfigs.release
>             minifyEnabled false
>             shrinkResources false
>         }
>     }
> ```

感谢!这样设置后果真搞定了！之前这两项都没配置，还以为整个项目默认会是false

**Comment by LichKing-2234** [comment]
R8是代替以前的Proguard混淆，flutter默认会开启，有兴趣可以了解下
