### ISSUE TITLE
startAudioMixing 函数无效，播放不了

### ISSUE THREAD

**Issue by guoheping113** [AgoraIO/Flutter-SDK#69]

**Comment by plutoless** [comment]
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#reporting-an-issue
麻烦参考这里取一下SDK日志

**Comment by guoheping113** [comment]
在吗？
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qianze Zhang"<notifications@github.com&gt;; 
发送时间: 2019年12月26日(星期四) 上午10:29
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] startAudioMixing 函数无效，播放不了 (#69)




https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#reporting-an-issue
 麻烦参考这里取一下SDK日志

**Comment by LichKing-2234** [comment]
在的？我本地试了没问题的额
`AgoraRtcEngine.startAudioMixing('/assets/mixing.mp3', false, false, 1);`

**Comment by guoheping113** [comment]
onLocalAudioMixingStateChanged 回调显示 errorCode

701 state

714 


 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Arthas"<notifications@github.com&gt;; 
发送时间: 2019年12月26日(星期四) 下午4:54
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] startAudioMixing 函数无效，播放不了 (#69)




在的？我本地试了没问题的额
 AgoraRtcEngine.startAudioMixing('/assets/mixing.mp3', false, false, 1);

**Comment by guoheping113** [comment]
playEffect 播放本地音频文件还崩溃。。。。

**Comment by plutoless** [comment]
![image](https://user-images.githubusercontent.com/471561/71556878-cce19780-2a78-11ea-8913-0a65fad3acac.png)

701 的意思是打开伴奏失败，麻烦检查一下自己的伴奏文件路径，我们自己试了都是没问题的，如果能够复现，麻烦给一个最小复现demo

**Comment by guoheping113** [comment]
路径没问题，我还成网络资源，也是一样






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qianze Zhang"<notifications@github.com&gt;; 
发送时间: 2019年12月29日(星期天) 晚上8:21
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] startAudioMixing 函数无效，播放不了 (#69)





 
701 的意思是打开伴奏失败，麻烦检查一下自己的伴奏文件路径，我们自己试了都是没问题的，如果能够复现，麻烦给一个最小复现demo

**Comment by guoheping113** [comment]
能加下QQ吗？ 这样沟通不方便啊

**Comment by guoheping113** [comment]
我用android的SDK就没问题，用flutter的SDK就播放不了

**Comment by plutoless** [comment]
你就发一下你的flutter项目，我们试一下就知道了

**Comment by guoheping113** [comment]
好的，那我怎么发给你
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Qianze Zhang"<notifications@github.com&gt;; 
发送时间: 2019年12月29日(星期天) 晚上9:01
收件人: "AgoraIO/Flutter-SDK"<Flutter-SDK@noreply.github.com&gt;; 
抄送: "Jason"<292303029@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [AgoraIO/Flutter-SDK] startAudioMixing 函数无效，播放不了 (#69)




你就发一下你的flutter项目，我们试一下就知道了

**Comment by plutoless** [comment]
你就直接作为附件贴在这个issue里就行了，github可以直接上传文件的

**Comment by guoheping113** [comment]
[Client.zip](https://github.com/AgoraIO/Flutter-SDK/files/4008077/Client.zip)

**Comment by LichKing-2234** [comment]
你的项目卡在启动页，能用我们的demo复现你的问题么

**Comment by guoheping113** [comment]
好的，可以，一会我做个

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
