### ISSUE TITLE
FlutterSDK版本升级到1.12后,release打包不能调用

### ISSUE THREAD

**Issue by WestWard-fjlajq** [AgoraIO/Flutter-SDK#71]
FlutterSDK版本升级到1.12后,安卓工程在release打包得到的apk不能调用视频通话功能,尝试调用直接闪退.
在debug模式下未出现这种情况.在FlutterSDK版本为1.9.1时,也能正常使用.

**Comment by LichKing-2234** [comment]
#68 看下这个issue，检查下是不是混淆的问题

**Comment by davewang** [comment]
* What went wrong:                                                      
Execution failed for task ':agora_rtc_engine:verifyReleaseResources'.   
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  /home/dave/dev/github/flutter_share_app/build/agora_rtc_engine/intermediates/res/merged/release/values/values.xml:237: error: resource android:attr/fontVariationSettings not found.
  /home/dave/dev/github/flutter_share_app/build/agora_rtc_engine/intermediates/res/merged/release/values/values.xml:238: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by davewang** [comment]
我的也是升级1.15后，打包报错

**Comment by plutoless** [comment]
@davewang 看下上面那个问题是否是一个问题

**Comment by davewang** [comment]
解决了 我升级了下 1。0。3

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
