### ISSUE TITLE
onAudioVolumeIndication 不能回调

### ISSUE THREAD

**Issue by davewang** [AgoraIO/Flutter-SDK#73]
这个回调接口不能工作把 
``` dart
 AgoraRtcEngine.enableAudioVolumeIndication(1000, 3, false);

 AgoraRtcEngine.onAudioVolumeIndication = (int totalVolume, List<AudioVolumeInfo> speakers){

      if(speakers!=null && speakers.isNotEmpty){
        // 更新音量
        speakers.forEach((speaker){
          if(speaker.uid!=0){
            print("speaker uid = ${speaker.uid} volume = ${speaker.volume}");
          }
        });

      }

    };
```

**Comment by LichKing-2234** [comment]
我这边试过是好的，你这边房间内有其他用户么，本地用户这个uid返回的是0

**Comment by davewang** [comment]
好了，可以了

**Comment by dganzella** [comment]
If any non-chinese speaker end up here, the issue is that for some reason on this callback the local user comes as 0 instead of the correct uid you provide on the join method. I fixed it like this

`
    AgoraRtcEngine.onAudioVolumeIndication = (int totalVolume, List<AudioVolumeInfo> speakers){

      //for some reason, local volume come as uid 0, and not the user uid.
      AudioVolumeInfo avi = speakers.firstWhere((talking) => talking.uid == 0, orElse: () => null );

      if(avi != null)
      {
          speakers.remove(avi);
          speakers.add( AudioVolumeInfo( <<add your correct user id >>, avi.volume) );
       }

    };`
