### ISSUE TITLE
Record stream

### ISSUE THREAD

**Issue by rlee1990** [AgoraIO/Flutter-SDK#74]
Not an issue but a question. How would I record the live stream for later viewing? Also, can I know when someone other then the host joins so I can track view count?

**Comment by plutoless** [comment]
we have our cloud recording service which you can use https://docs.agora.io/en/cloud-recording/product_cloud_recording?platform=All%20Platforms
you have to use your own service to track this count, our media sdk does not track down this. You may also use our RTM sdk - https://docs.agora.io/en/Real-time-Messaging/product_rtm?platform=All%20Platforms

**Comment by rlee1990** [comment]
@plutoless thanks.

**Comment by rlee1990** [comment]
@plutoless one other questions how would I make the live video SDK full screen? I tried all the normal flutter options it does not work

**Comment by LichKing-2234** [comment]
try use `VideoRenderMode.Fit` when init `AgoraRenderWidget`

**Comment by rlee1990** [comment]
@LichKing-2234 it is set to that but for some reason if a use a scaffold with no app bar n just this sdk with a container the size of the device screen the view won’t take up the full size.

**Comment by LichKing-2234** [comment]
could you capture the screen and upload the image

**Comment by rlee1990** [comment]
@LichKing-2234 here you go. I also have removed the appbar but that area stays black
![Screenshot_20200106-061955](https://user-images.githubusercontent.com/21372502/71815244-d9ec2100-304c-11ea-90f7-b3597346c1e6.jpg)

**Comment by LichKing-2234** [comment]
`VideoRenderMode.Hidden` is also not worked?

**Comment by rlee1990** [comment]
@LichKing-2234 i didn’t try that but I will today

**Comment by LichKing-2234** [comment]
`VideoRenderMode.Hidden` is default, and it work for me

**Comment by rlee1990** [comment]
Thanks that worked @LichKing-2234
