### ISSUE TITLE
Does the flutter SDK support RTM?

### ISSUE THREAD

**Issue by OsaXma** [AgoraIO/Flutter-SDK#77]
In the Read Me page, it's mentioned that: "This Flutter plugin is a wapper for Agora Video SDK."

Does this mean doing voice only or using RTM (mainly for text chat messages) isn't supported with Flutter yet?

**Comment by plutoless** [comment]
Flutter-SDK video is a super set of audio SDK. video sdk supports all audio features provided by audio sdk. RTM is a separate SDK.

**Comment by OsaXma** [comment]
so from what I understand, there is no RTM SDK for flutter? 

Also, could you please direct me where I can find info for the RTM pricing in general? I couldn't find anything on the website.

**Comment by LichKing-2234** [comment]
@OsaXma 
https://github.com/AgoraIO/Flutter-RTM

**Comment by plutoless** [comment]
for pricing pls contact sales

**Comment by OsaXma** [comment]
Thank you.
