### ISSUE TITLE
"add to app" not working canvas drawing.

### ISSUE THREAD

**Issue by SAMUKEI** [AgoraIO/Flutter-SDK#80]
I tried "add to app" in iOS app.
I found the problem  local/remote canvas drawing.

###  Environment
iOS: 13.3.1
Agora SDK version: agora_rtc_engine: ^1.0.7

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.3 19D76, locale ja-JP)

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1.4)
[!] VS Code (version 1.42.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

ref. https://flutter.dev/docs/development/add-to-app/ios/add-flutter-screen

### Screenshots

| "flutter only"  iOS app | "add to app" iOS app   |
----|---- 
| ![Image from iOS (1)](https://user-images.githubusercontent.com/12232041/75445042-f9962a80-59a7-11ea-8afe-868280fba617.jpg) | ![Image from iOS (2)](https://user-images.githubusercontent.com/12232041/75445035-f602a380-59a7-11ea-9950-257b27a06c42.png)  |

**Comment by LichKing-2234** [comment]
please provide [the SDK log](https://docs.agora.io/en/Voice/API%20Reference/oc/Classes/AgoraRtcEngineKit.html#//api/name/setLogFile:)

**Comment by SAMUKEI** [comment]
Sorry I tried again today and it worked.
Close this issue.
