### ISSUE TITLE
AgoraLiveTranscoding complete example needed

### ISSUE THREAD

**Issue by AxesandGrinds** [AgoraIO/Flutter-SDK#81]
I need help understanding how to use AgoraLiveTranscoding when initializing video. My main issue is how to use transcodingUsers function.

The android sdk details how to use live transcoding very well but the flutter documentation for this seems to be lacking. Please provide a detailed example for how to use transcodingUsers and let me know what the effect of it is.

Lastly, what does setting the height, width, and bitrate of the livetranscoding config file do?

**Comment by AxesandGrinds** [comment]
I have read https://docs.agora.io/en/Voice/API%20Reference/web/interfaces/agorartc.livetranscoding.html
and have a better idea of livetranscoding, but I still need a full example of how to set transcoding user and to understand how it works.

**Comment by LichKing-2234** [comment]
flutter sdk use the android sdk and ios sdk

**Comment by LichKing-2234** [comment]
you can refer to the android sdk doc

**Comment by AxesandGrinds** [comment]
flutter uses dart so the language is a bit different. You completely neglected my question. I need a flutter version of the two below functions written in java.

```
private void setTranscoding() {

        ArrayList<LiveTranscoding.TranscodingUser> transcodingUsers;

        ArrayList<UserInfo> videoUsers = getAllVideoUser(mUserInfo);

        transcodingUsers = cdnLayout(mBigUserId, videoUsers, mLiveTranscoding.width, mLiveTranscoding.height);

        mLiveTranscoding.setUsers(transcodingUsers);

        mRtcEngine.setLiveTranscoding(mLiveTranscoding);
    }
```

and

```
public static ArrayList<LiveTranscoding.TranscodingUser> cdnLayout(int bigUserId, ArrayList<UserInfo> publishers,
                                                                       int canvasWidth,
                                                                       int canvasHeight) {

        ArrayList<LiveTranscoding.TranscodingUser> users = new ArrayList<>(publishers.size());

        int   index = 0;
        float xIndex, yIndex;
        int   viewWidth;
        int   viewHEdge;

        if (publishers.size() <= 1) {

            viewWidth = canvasWidth;
        }
        else {

            viewWidth = canvasWidth / 2;
        }

        if (publishers.size() <= 2) {

            viewHEdge = canvasHeight;
        }
        else {

            viewHEdge = canvasHeight / ((publishers.size() - 1) / 2 + 1);
        }

        LiveTranscoding.TranscodingUser user0 = new LiveTranscoding.TranscodingUser();
        user0.uid = bigUserId;
        user0.alpha = 1;
        user0.zOrder = 0;
        user0.audioChannel = 0;

        user0.x = 0;
        user0.y = 0;
        user0.width = viewWidth;
        user0.height = viewHEdge;
        users.add(user0);

        index++;

        for (UserInfo entry : publishers) {

            if (entry.uid == bigUserId) {

                continue;
            }

            xIndex = index % 2;
            yIndex = index / 2;

            LiveTranscoding.TranscodingUser tmpUser = new LiveTranscoding.TranscodingUser();

            tmpUser.uid          = entry.uid;
            tmpUser.x            = (int) ((xIndex) * viewWidth);
            tmpUser.y            = (int) (viewHEdge * (yIndex));
            tmpUser.width        = viewWidth;
            tmpUser.height       = viewHEdge;
            tmpUser.zOrder       = index + 1;
            tmpUser.audioChannel = 0;
            tmpUser.alpha        = 1f;

            users.add(tmpUser);

            index++;

        }

        return users;
    }
```

**Comment by LichKing-2234** [comment]
```
await AgoraRtcEngine.setLiveTranscoding(AgoraLiveTranscoding.fromJson({
      'width': 640,
      'height': 480,
      'videoBitrate': 1800,
      'videoFramerate': 15,
      'transcodingUsers': agoraLiveUserList,
      'watermark': AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
      'backgroundImage':
          AgoraImage('https://imgur.com/zt3pL7e', 0, 0, 100, 100),
    }));
```

**Comment by LichKing-2234** [comment]
like this

**Comment by AxesandGrinds** [comment]
Excellent!! Thank you!! I wouldn't have never been able to write that given the android and ios examples. I appreciate your help!

**Comment by AxesandGrinds** [comment]
I'm getting an error that says: "A value of type 'List<int>' can't be assigned to a variable of type 'List<AgoraLiveTranscodingUser>'. " How do I create and initialize the AgoraLiveTranscodingUser in the list?

Below is my code.

```
AgoraLiveTranscoding liveTranscodingConfig;
    liveTranscodingConfig.audioBitrate = 128;
    liveTranscodingConfig.videoBitrate = 700;
    liveTranscodingConfig.height = 640;
    liveTranscodingConfig.width = 480;
    liveTranscodingConfig.videoCodecProfile = AgoraVideoCodecProfileType.High;
    List<int> finalList = [broadcasterMUID];
    finalList.addAll(_users);
    liveTranscodingConfig.transcodingUsers = finalList;
    AgoraRtcEngine.setLiveTranscoding(liveTranscodingConfig);
```

**Comment by LichKing-2234** [comment]
class AgoraLiveTranscodingUser {
  int uid;
  int width;
  int height;
  int x;
  int y;
  int zOrder;
  int alpha;
  int audioChannel;

  AgoraLiveTranscodingUser.fromJson(Map<dynamic, dynamic> json)
      : uid = json['uid'],
        width = json['width'],
        height = json['height'],
        x = json['x'],
        y = json['y'],
        zOrder = json['zOrder'],
        alpha = json['alpha'],
        audioChannel = json['audioChannel'];

  Map<dynamic, dynamic> toJson() => {
        'uid': uid,
        'width': width,
        'height': height,
        'x': x,
        'y': y,
        'zOrder': zOrder,
        'alpha': alpha,
        'audioChannel': audioChannel
      };
}

**Comment by LichKing-2234** [comment]
```
class AgoraLiveTranscodingUser {
  int uid;
  int width;
  int height;
  int x;
  int y;
  int zOrder;
  int alpha;
  int audioChannel;

  AgoraLiveTranscodingUser.fromJson(Map<dynamic, dynamic> json)
      : uid = json['uid'],
        width = json['width'],
        height = json['height'],
        x = json['x'],
        y = json['y'],
        zOrder = json['zOrder'],
        alpha = json['alpha'],
        audioChannel = json['audioChannel'];

  Map<dynamic, dynamic> toJson() => {
        'uid': uid,
        'width': width,
        'height': height,
        'x': x,
        'y': y,
        'zOrder': zOrder,
        'alpha': alpha,
        'audioChannel': audioChannel
      };
}
```

**Comment by khaliqdadmohmand** [comment]
> Excellent!! Thank you!! I wouldn't have never been able to write that given the android and ios examples. I appreciate your help!

hey bro can you send me your code if you successfully created the live streaming a part in flutter

**Comment by khaliqdadmohmand** [comment]
Can anyone help me.
i wan to create the livestreaming app live facebook live. i need code plz

**Comment by plutoless** [comment]
you mean publish live streaming to RTMP Server? Or doing live broadcasting using our sdk directly.

**Comment by khaliqdadmohmand** [comment]
Do you have sdk for flutter with full documentation.

**Comment by plutoless** [comment]
@khaliqdadmohmand all flutter libs has documentation by default
https://pub.dev/documentation/agora_rtc_engine/1.0.10/

**Comment by plutoless** [comment]
still you may take a look at our sdk docs on other platforms to get a brief understanding

**Comment by khaliqdadmohmand** [comment]
Thank you for your email and support
