### ISSUE TITLE
单独的demo能运行，集成进androidx项目后，无法打开本地视频，视频通话能有声音。

### ISSUE THREAD

**Issue by d1bug** [AgoraIO/Flutter-SDK#82]
如题，日志信息如下：
[agorasdk.log.zip](https://github.com/AgoraIO/Flutter-SDK/files/4269979/agorasdk.log.zip)

**Comment by LichKing-2234** [comment]
集成是指作为flutter module？什么代码都没有修改是么

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
