### ISSUE TITLE
Can't render full screen view in iPad

### ISSUE THREAD

**Issue by yukitaka13-1110** [AgoraIO/Flutter-SDK#83]
I tried to render as full screen view in iPad.
But view contain black region on both sides.

I configured videoFrameSize like the following code.

```dart
final size = MediaQuery.of(context).size;
final config = VideoEncoderConfiguration()
   ..dimensions = Size(size.width, size.height)
  ..orientationMode = VideoOutputOrientationMode.FixedPortrait;
```

![IMG_B7B3C7A917B7-1](https://user-images.githubusercontent.com/22259776/75758125-e9e75f00-5d76-11ea-8889-eda04a91a44e.jpeg)

I could render full screen view in iPhone.
What should I do ?

**Comment by LichKing-2234** [comment]
Change `VideoRenderMode` to `Fit` when you init `AgoraRenderWidget`

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 
I already changed to `VideoRenderMode.Fit` but not working well.
In iPhone, working well.

**Comment by LichKing-2234** [comment]
is `VideoRenderMode.Hidden` worked?

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 
It worked. But top and bottom was cropped.
I want to show full screen view of uncut iPad.
ex) iPad 7th 1080x810
Currently, left and right are cropped

**Comment by LichKing-2234** [comment]
if you want uncropped in `Hidden` mode, you need set the aspect ratio is the same as your screen

**Comment by LichKing-2234** [comment]
just like Android ImageView `scaleType`

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 
Can I set aspect ratio `AgoraRtcEngine` or others ?
I think `AgoraRenderWidget` has aspect ratio, but I couldn't find settings.
Does it means `VideoEncoderConfiguration()` ?

**Comment by LichKing-2234** [comment]
@yukitaka13-1110  yes

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 
https://github.com/AgoraIO/Flutter-SDK/issues/83#issue-574506750

I have already set `VideoEncoderConfiguration().dimensions = MediaQuery.of(context).size`.
So aspect ratio probably correct. Does this way not correct ?

**Comment by LichKing-2234** [comment]
different devices have a different aspect ratio, I suggest you choose one of the preset configurations and don't mind the video may be cut on some device.

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Interactive%20Broadcast/video_profile_android?platform=Android

**Comment by yukitaka13-1110** [comment]
@LichKing-2234 
Sure I know that.
In iPad rear camera displayed full screen.
But agora doesn’t display both case default setting and device full screen size setting.
What do you mean ´one of the preset’?

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Interactive%20Broadcast/video_profile_android?platform=Android

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
