### ISSUE TITLE
When will the sdk be upgraded to use the new flutter plugin engine?

### ISSUE THREAD

**Issue by AniketMalik** [AgoraIO/Flutter-SDK#87]
I am removing the `GeneratedPluginRegistrant.registerWith(flutterEngine);` line from the main activity but then other cloud_firestore plugins break. Most of the other plugin have implemented the new flutter plugin engine. When will this sdk upgrade?

**Comment by LichKing-2234** [comment]
could you share me the link of cloud_firestore plugins, I will take a look

**Comment by AniketMalik** [comment]
[Flutter Fire](https://github.com/FirebaseExtended/flutterfire) this is the link to the flutter firebase plugins.

The problem occurs when we run a `Transaction` on a firebase instance on Android.

Error:
Platform exception : transaction called on null reference.

Steps to reproduce:
1. Add the cloud_firestore plugin and run a transaction on the firestore. ( it works until the `GeneratedPluginRegistrant.registerWith(flutterEngine)` is not removed ).

2. Add the agora rtc plugin. Set up to remove the black screen issue on Android.

Once we remove the `GeneratedPluginRegistrant.registerWith(flutterEngine)` line, the run transaction breaks giving the  -- Platform exception : transaction called on null reference.

**Comment by LichKing-2234** [comment]
is your MainActivity extends `io.flutter.embedding.android.FlutterActivity`?

**Comment by AniketMalik** [comment]
Yes and i cannot remove that as other plugins break if i do

**Comment by LichKing-2234** [comment]
please show me the code of `io.flutter.plugins.GeneratedPluginRegistrant.java`

**Comment by LichKing-2234** [comment]
by the way, pls give me the version of cloud_firestore which you used

**Comment by AniketMalik** [comment]
Firebase Plugins is use:
cloud_firestore: ^0.13.1
 firebase_storage: ^3.1.3
 firebase_messaging: ^6.0.12
 firebase_auth: ^0.15.4

**Comment by AniketMalik** [comment]
Here is the code for `GeneratedPlugindRegistrant.java`

package io.flutter.plugins;

import androidx.annotation.Keep;
import androidx.annotation.NonNull;
import io.flutter.embedding.engine.FlutterEngine;
import io.flutter.embedding.engine.plugins.shim.ShimPluginRegistry;

/**
 * Generated file. Do not edit.
 * This file is generated by the Flutter tool based on the
 * plugins that support the Android platform.
 */
@Keep
public final class GeneratedPluginRegistrant {
  public static void registerWith(@NonNull FlutterEngine flutterEngine) {
    ShimPluginRegistry shimPluginRegistry = new ShimPluginRegistry(flutterEngine);
      io.agora.agorartcengine.AgoraRtcEnginePlugin.registerWith(shimPluginRegistry.registrarFor("io.agora.agorartcengine.AgoraRtcEnginePlugin"));
      io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.connectivity.ConnectivityPlugin());
      io.flutter.plugins.firebaseauth.FirebaseAuthPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.firebaseauth.FirebaseAuthPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.core.FirebaseCorePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.firebase.storage.FirebaseStoragePlugin());
      com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.registerWith(shimPluginRegistry.registrarFor("com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin"));
    flutterEngine.getPlugins().add(new com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin());
      io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.flutter_plugin_android_lifecycle.FlutterAndroidLifecyclePlugin"));
      com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin.registerWith(shimPluginRegistry.registrarFor("com.it_nomads.fluttersecurestorage.FlutterSecureStoragePlugin"));
      io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin.registerWith(shimPluginRegistry.registrarFor("io.github.ponnamkarthik.toast.fluttertoast.FluttertoastPlugin"));
      io.flutter.plugins.googlesignin.GoogleSignInPlugin.registerWith(shimPluginRegistry.registrarFor("io.flutter.plugins.googlesignin.GoogleSignInPlugin"));
    flutterEngine.getPlugins().add(new io.flutter.plugins.imagepicker.ImagePickerPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.pathprovider.PathProviderPlugin());
    flutterEngine.getPlugins().add(new com.baseflow.permissionhandler.PermissionHandlerPlugin());
    flutterEngine.getPlugins().add(new com.tekartik.sqflite.SqflitePlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.urllauncher.UrlLauncherPlugin());
    flutterEngine.getPlugins().add(new io.flutter.plugins.webviewflutter.WebViewFlutterPlugin());
  }
}

**Comment by LichKing-2234** [comment]
I see your flutterEmbedding is v2.
I think your MainActivity extends `io.flutter.app.FlutterActivity`.

**Comment by LichKing-2234** [comment]
I see your flutterEmbedding is v2, let me see your `MainActivity`

**Comment by AniketMalik** [comment]
Here is the main activity.

import androidx.annotation.NonNull;
import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugins.GeneratedPluginRegistrant

class MainActivity: FlutterActivity() {
    override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
        // Changed for Agora.io plugin
        // GeneratedPluginRegistrant.registerWith(flutterEngine);
    }
}

**Comment by LichKing-2234** [comment]
why you override `configureFlutterEngine` but do not run the super function?

**Comment by AniketMalik** [comment]
This change was automatic when i upgraded the flutter version and migrated to androidx

**Comment by LichKing-2234** [comment]
maybe the version of our flutter engine is different, pls debug `io.flutter.embedding.engine.FlutterEngine.java` and make sure the `register Plugins` function has been run

**Comment by LichKing-2234** [comment]
```
 package io.flutter.plugins.firebasecoreexample;

 import io.flutter.embedding.android.FlutterActivity;
 import io.flutter.embedding.engine.FlutterEngine;
 import io.flutter.plugins.firebase.core.FirebaseCorePlugin;

 public class MainActivity extends FlutterActivity {
   // You can keep this empty class or remove it. Plugins on the new embedding
   // now automatically registers plugins.
 }
```
I think it no an error.
[you can refer to the official doc](https://flutter.dev/docs/development/packages-and-plugins/plugin-api-migration)

**Comment by LichKing-2234** [comment]
maybe you can open an issue to firebase

**Comment by AniketMalik** [comment]
I will open an issue there.

Additionally please verify if the agora plugin will be changed to use the new `Flutter Plugin Engine` ?

**Comment by LichKing-2234** [comment]
not so fast, we will upgrade in Q2

**Comment by AniketMalik** [comment]
Thank you.

**Comment by mahmoudatef925** [comment]
i have same issue using cloud_firestore: ^0.13.4+2
get balck screen then remove GeneratedPluginRegistrant.registerWith(flutterEngine); 
after that i get another issue in transaction in cloud_firestore
please provide me with solution 
thanks in advance
