### ISSUE TITLE
View duplicate image

### ISSUE THREAD

**Issue by jlucas577** [AgoraIO/Flutter-SDK#89]
Guys, I would like to know how I can use the AgoraIO api on Flutter, but I would like to duplicate the image I get from the user id 1, basically I would like to show the image of the other user who is in the call in two squares on my application screen , but for some reason only one square shows the image and the other is black.

**Comment by LichKing-2234** [comment]
```
Iterable<Widget> get _renderWidget sync* {
    yield AgoraRenderWidget(0, local: true, preview: false);

    for (final uid in _remoteUsers) {
      yield AgoraRenderWidget(uid);
    }
  }

```
the `AgoraRenderWidget` with `local: true` will show local stream.
And the other `AgoraRenderWidget` will show a remote stream.

**Comment by jlucas577** [comment]
So, I would like to duplicate the remote stream.

**Comment by LichKing-2234** [comment]
you want to render two same stream from one user?

**Comment by jlucas577** [comment]
I want to show the same stream twice, sort of showing an image of the remote user on 50% of the screen, but duplicating an image.

Two 50% squares would be left showing the image of the remote stream.

**Comment by LichKing-2234** [comment]
our SDK can only render one video from one `uid` now

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
