### ISSUE TITLE
关于Android使用TextureWidget和PlatformView的性能对比

### ISSUE THREAD

**Issue by fyfcauc** [AgoraIO/Flutter-SDK#9]
作者您好:
      看了您的视频，里面提到了TextureWidget和PlatformView的性能差别对比(闲鱼的外接纹理那篇文章也有提到过)，我在阅读了Android端相关的代码后，有一个困惑，希望您能解答一下：
1. Flutter Android端的桥接代码中 Texture 和 AndroidView都是通过TextureRegistray建立连接关系的，都会申请一个SurfaceTexture(建立BufferQueue通道)，然后基于此SurfaceTexture构造一个Surface。

2. 不同之处只是外部将内容绘制到Surface的过程：Texture的话，用户负责将内容渲染到Surface上(比如OpenGL，将Surface作为ANativeWindow构造EGLSurface然后进行绘制)，而对于PlatformView来说，则是基于Surface构造一个VirtualDisplay，然后将用户的NativeView加入到该VirtualDisplay进行绘制，进而View的内容就绘制到该Surface。

3. 我的困惑是，两者都通过Surface进行了桥接内容到Flutter, 而非直接Share OpenGLContext的方式来共享纹理进行绘制。那么理论上两者的性能消耗应该是差不多的。为什么您的测试结果中在Android上两者还出现了比较大的性能差距(也有可能您说的只是iOS的性能结果)？

**Comment by plutoless** [comment]
@fyfcauc 感谢你的提问
这里的区别是当使用native的渲染时 声网是直接用硬解和硬件渲染到native view上的，中间没有数据到cpu再到gpu的拷贝过程，我理解这种情况虽然最后依然是通过virtualDisplay绘制，但在virtualdisplay中的绘制过程已经不再需要处理音视频数据了，因此在这块上减少了性能损耗；但用texture渲染时需要先通过声网的裸数据接口将数据回调出来后再交给gpu渲染，这块的cpu损耗是没法避免的，如果你看了闲鱼那篇文章，这个就是他讨论到过的问题

**Comment by fyfcauc** [comment]
@plutoless 感谢您的回答，不过我还有些疑问，
1. 首先，声网Android端SDK是否有接口直接设置要输出到的Surface(抱歉我没看过声网SDK的接口)? 就像ExoPlaye的setVideoSurface接口，直接设置到某个Surface。
2. 如果有这样的接口，那么您上面说的现将视频帧裸数据回调回来这一步是不需要的，因为Texture Widget本身也是基于Surface进行内容桥接的，我完全可以让声网SDK直接将数据输出到Flutter为我提供的Surface上。
3. 如果是类似于ffmpeg这种软解，先得到裸数据，然后再绘制到NativeView的Surface上(当然了，这一步，如果没有预处理的话，直接memcpy到Surface的NativeWindow上也行)。那么这一步，如果声网SDK是直接渲染到NativeView，可能还会比使用Texture要多一次数据的传输(前者: 裸数据->SurfaceView->VirtualDisplay画到Surface上, 后者: 裸数据->Surface)
4. 闲鱼那篇文章最终的解决方案个人感觉和PlatformView是两种不同方案，闲鱼是共享GLContext来直接共享纹理，而PlatformView则做不到这一点，还是Surface数据传输(只是基于Android端的实现)。

**Comment by plutoless** [comment]
@fyfcauc 
1. 声网目前提供裸数据接口的目的一般都是为了让用户可以自行修改数据，所以目前提供的接口都是将数据抛出来的，目前声网支持直接输出到native view但暂时没有接口可以直接设置输出到surface，这个我可以和同事提一下
2. (1)提了
3. 正常渲染到native view是不走裸数据接口的，所以前者应该是SurfaceView -> VirtualDisplay
4. 咸鱼那个没有用Platform View，是用了TextureView + gpu share，所以确实是两个不同的方案，原因应该是他写这篇文章的时候platform view还没出来。。

**Comment by fyfcauc** [comment]
@plutoless 感谢您的耐心解答，那我是否可以这么理解，如果声网也支持了直接输出到Surface(当然是直接硬解输出，而非SDK内部读取裸数据再输出到Surface)，那么使用Texture和PlatformView的性能代价对声网SDK来说其实就一样了？

**Comment by plutoless** [comment]
@fyfcauc 理论上是的，感谢你的建议，但这个行为可能会需要修改SDK，我会需要和SDK的同事讨论一下

**Comment by fyfcauc** [comment]
@plutoless 感谢您的耐心回复。

**Comment by shop987** [comment]
@plutoless  查阅了相关资料，flutter外接纹理 共享Native的纹理数据，性能会好些。 现在是嵌入的Native view，后续有计划支持flutter外接纹理实时渲染视频吗
