### ISSUE TITLE
How to adjust the resolution of video call based on the internet speed? 

### ISSUE THREAD

**Issue by suriyaKalidoss123** [AgoraIO/Flutter-SDK#90]
Hi,
Currently, bitrate and framerate of particular resolution are reduced If internet quality is bad. My question is. If the speed is suddenly reduced to lower bandwidth. How to adjust the resolution on run time based on internet speed so my video call runs smoothly on all network condition. Please provide a solution.
Note: If this future is available I would like to purchase this agora plugin.
Thanks.

**Comment by LichKing-2234** [comment]
you can refer to these API.
[enableDualStreamMode](https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a645cb7d0f3a59dda27b157cf130c8c9a)
[setRemoteSubscribeFallbackOption](https://docs.agora.io/en/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#af64301ea1788dad0561aa678f3fe6ad3)

**Comment by suriyaKalidoss123** [comment]
Enabled enableDualStreamMode API but still video call quality is not good.

**Comment by LichKing-2234** [comment]
have you set `RemoteSubscribeFallbackOption`?

**Comment by LichKing-2234** [comment]
by the way, could you pls provide your VideoEncoderConfiguration?

**Comment by suriyaKalidoss123** [comment]
I'm not using VideoEncoderConfig. I'm just using the default configuration
[call.zip](https://github.com/AgoraIO/Flutter-SDK/files/4347405/call.zip)
This is my code.

**Comment by LichKing-2234** [comment]
I cant see `setRemoteSubscribeFallbackOption` and `enableDualStreamMode` from your code

**Comment by suriyaKalidoss123** [comment]
No improvements in video quality after adding,That's why I removed the lines

**Comment by suriyaKalidoss123** [comment]
@LichKing-2234 May I know the recommended resolution for the video call?

**Comment by LichKing-2234** [comment]
https://docs.agora.io/en/Interactive%20Broadcast/video_profile_android?platform=Android
https://docs.agora.io/en/Interactive%20Broadcast/multi_user_video_android?platform=Android

**Comment by suriyaKalidoss123** [comment]
Okay thanks for info

**Comment by plutoless** [comment]
@suriyaKalidoss123 could you pls provide a recording? also dual stream is intended to choose a lower resolution/fps video to avoid network congestion, so if you use it and pick the small stream it will look slightly lagged.
if you can provide a recording for like 1 min, together with the channel name and time you tested. i can do a quick check from our backend to see what could go wrong

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.
