### ISSUE TITLE
Support background calls for Android

### ISSUE THREAD

**Issue by doljanins** [AgoraIO/Flutter-SDK#92]
As mentioned in the documentation, the plugin can still run voice calls when it's switched to the background on iOS devices. However, is this something you have a work around for when working with Android?

**Comment by LichKing-2234** [comment]
Android can do it by default

**Comment by doljanins** [comment]
[Android execution limits from api 26 ](https://developer.android.com/about/versions/oreo/background) stop all calls/broadcasting after a few minutes if the application is running in the background.

**Comment by LichKing-2234** [comment]
our SDK create a thread to capture and encode, you can use foreground service at Android, but Flutter SDK doesn't support now

**Comment by LichKing-2234** [comment]
I will close this issue because it is too old. if there are still problems, you can reopen this issue.

**Comment by LichKing-2234** [comment]
you can refer to this comment.
https://github.com/AgoraIO/Flutter-SDK/issues/28#issuecomment-717667342

**Comment by vedartm** [comment]
> our SDK create a thread to capture and encode, you can use foreground service at Android, but Flutter SDK doesn't support now

Hi, @LichKing-2234. Does it support now? If it does, can you provide some examples to use the foreground service method?

**Comment by LichKing-2234** [comment]
@vedartm pls follow #28
