### ISSUE TITLE
删除GeneratedPluginRegistrant.registerWith(flutterEngine)将使其他插件无法使用

### ISSUE THREAD

**Issue by yuerzi** [AgoraIO/Flutter-SDK#93]
只能获取到声音，图像黑屏

**Comment by plutoless** [comment]
这边有正确参考 https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart#android-black-screen 的建议吗？

**Comment by yuerzi** [comment]
@plutoless 是按照文档写的,这是我的环境，按照例子，只能听到声音
[✓] Flutter (Channel dev, v1.12.16, on Mac OS X 10.14.5 18F203, locale
    zh-Hans-CN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)

**Comment by plutoless** [comment]
删除前你要先确保自己是属于哪个API版本的，不要删错了，一般视频渲染不出都是因为这个引起的

**Comment by yuerzi** [comment]
> 删除前你要先确保自己是属于API版本的，不要删除错了，一般视频渲染不出都是因为这个引起的

我使用的是最新的agora_rtc_engine-1.0.8

**Comment by plutoless** [comment]
你是自己新创建了一个项目吗？

**Comment by yuerzi** [comment]
> 你是自己新创建了一个项目吗？

对的，是我自己的app，使用您的插件。代码和权限如下
Future<void> _initAgoraRtcEngine(rtcToken,rtmToken,memberId) async {
    AgoraRtcEngine.create(Config.AGORAID);
    AgoraRtcEngine.enableVideo();
    AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);
    _addAgoraEventHandlers(memberId);
    VideoEncoderConfiguration config = VideoEncoderConfiguration();
    config.dimensions = Size(ScreenUtil().setWidth(320),ScreenUtil().setHeight(202.5));
    config.orientationMode = VideoOutputOrientationMode.FixedPortrait;
    AgoraRtcEngine.setVideoEncoderConfiguration(config);
    await AgoraRtcEngine.joinChannel(rtcToken, widget.liveInfo["channelName"], null, memberId);
  }

  void _addAgoraEventHandlers(memberId) {
    AgoraRtcEngine.onVideoSizeChanged = (uid, width, height, rotation) {
      print('$uid $width $height $rotation');
    };


    AgoraRtcEngine.onError = (err) {
     print("err:"+err.toString());
    };
    AgoraRtcEngine.onWarning = (warning) {
      print("warning:"+warning.toString());
    };
    AgoraRtcEngine.onJoinChannelSuccess =
        (String channel, int uid, int elapsed) {
          print("onJoinChannel:"+uid.toString());
      setState(() {
        String info = 'onJoinChannel: ' + channel + ', uid: ' + uid.toString();
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onLeaveChannel = () {
      print("onLeaveChannel:");
      setState(() {
        _infoStrings.add('onLeaveChannel');
      });
    };

    AgoraRtcEngine.onUserJoined = (int uid, int elapsed) {
      print("userJoined:" + uid.toString());
      setState(() {
        String info = 'userJoined: ' + uid.toString();
        _infoStrings.add(info);
        videoWidget =  AgoraRenderWidget(0,local: true,preview: false,);
        videoFlag = true;
      });
    };

    AgoraRtcEngine.onUserOffline = (int uid, int reason) {
      print("userOffline:" + uid.toString());
      setState(() {
        String info = 'userOffline: ' + uid.toString();
        _infoStrings.add(info);
      });
    };

    AgoraRtcEngine.onFirstRemoteVideoFrame =
        (int uid, int width, int height, int elapsed) {
          print("userOffline:");
      setState(() {
        String info = 'firstRemoteVideo: ' +
            uid.toString() +
            ' ' +
            width.toString() +
            'x' +
            height.toString();
        _infoStrings.add(info);
      });
    };
  }

<uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />

**Comment by plutoless** [comment]
项目是什么时候创建的？

**Comment by plutoless** [comment]
要不你弄个最小复现demo发一下，你这个一般只可能是这个问题
![image](https://user-images.githubusercontent.com/471561/77250920-1dd2e780-6c86-11ea-8e25-2a23ffd9f1d4.png)

**Comment by yuerzi** [comment]
> 要不你弄个最小复现demo发一下，你这个一般只可能是这个问题
> ![image](https://user-images.githubusercontent.com/471561/77250920-1dd2e780-6c86-11ea-8e25-2a23ffd9f1d4.png)

<img width="1038" alt="WechatIMG57" src="https://user-images.githubusercontent.com/24539930/77252618-ea955600-6c8f-11ea-869e-485db76e6fe8.png">如果我去掉这个标注的代码，是显示图像的，是手机摄像头返回的图像，声音是客户端传过来的声音，但是这不是我想要的结果。我的业务需求是直播，客户端把流传过来，手机显示客户端的声音及图像，而不是手机摄像头返回的图像。就像web端一样设置live模式，但是一设置这个模式就黑屏，按照文档上说的移除项目中的代码，再次启动项目，项目中使用的好多依赖的插件就没法使用了
<img width="1139" alt="WechatIMG58" src="https://user-images.githubusercontent.com/24539930/77252822-6cd24a00-6c91-11ea-86a0-434808472404.png">感谢百忙之中帮助我！

**Comment by LichKing-2234** [comment]
@yuanzaiyu `flutter doctor -v` 跑下，看下你的flutter engine版本

**Comment by LichKing-2234** [comment]
还有你说的不能用的插件有哪些，我这边试下

**Comment by yuerzi** [comment]
> 还有你说的不能用的插件有哪些，我这边试下

 Flutter (Channel dev, v1.16.1, on Mac OS X 10.14.5 18F203, locale
    zh-Hans-CN)
    • Flutter version 1.16.1 at /Users/zhangzhe/software/fvm/versions/1.16.1-dev
    • Framework revision e6b0f5f238 (4 days ago), 2020-03-18 21:56:02 -0400
    • Engine revision 216c420a2c
    • Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)
删除之后会导致agorartcengine插件本身，ijkplayer，shared_preferences等，都无法使用

**Comment by LichKing-2234** [comment]
我这边新建的项目，MainActivity里都是空的，这是官方默认的行为了
![image](https://user-images.githubusercontent.com/9312526/77253368-9f317680-6c94-11ea-955d-4bf86ecbdebe.png)

**Comment by yuerzi** [comment]
> 我这边新建的项目，MainActivity里都是空的，这是官方默认的行为了
> ![image](https://user-images.githubusercontent.com/9312526/77253368-9f317680-6c94-11ea-955d-4bf86ecbdebe.png)

是新建的版本就项目就可以解决黑屏问题了吗？我明早新建一个把项目移植过去，我忘记带充电器了，还有5%的电，抱歉，您早点休息

**Comment by LichKing-2234** [comment]
我刚才看了下源码，你这边不要重写这个方法，如果重写但是不调用super就会导致插件无法注册

**Comment by yuerzi** [comment]
> 我刚才看了下源码，你这边不要重写这个方法，如果重写但是不调用super就会导致插件无法注册

我用最新的sdk重新生成了一个项目，MainActivity是空的，但是我想要的业务需求还是黑屏，AgoraRtcEngine.setChannelProfile(ChannelProfile.LiveBroadcasting);但是去掉这行代码能显示我自己。但不是我想要功能。麻烦帮忙看一下
![1584928116246](https://user-images.githubusercontent.com/24539930/77272492-586f6b00-6cec-11ea-8dfb-a75797fa3d17.jpg)
<img width="1038" alt="WechatIMG57" src="https://user-images.githubusercontent.com/24539930/77272500-5c9b8880-6cec-11ea-869c-2b1b87948c9f.png">

**Comment by yuerzi** [comment]
> 我刚才看了下源码，你这边不要重写这个方法，如果重写但是不调用super就会导致插件无法注册

[✓] Flutter (Channel dev, v1.16.1, on Mac OS X 10.14.5 18F203, locale
    zh-Hans-CN)
    • Flutter version 1.16.1 at /Users/zhangzhe/software/fvm/versions/1.16.1-dev
    • Framework revision e6b0f5f238 (4 days ago), 2020-03-18 21:56:02 -0400
    • Engine revision 216c420a2c
    • Dart version 2.8.0 (build 2.8.0-dev.15.0 96cf889e6b)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/zhangzhe/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling
      support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/zhangzhe/Library/Android/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build
      1.8.0_202-release-1483-b49-5587405)

[!] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (1 available)
    • STF AL10 • CSX0217A24000797 • android-arm64 • Android 9 (API 28)

**Comment by LichKing-2234** [comment]
你这个是未设置clientRole为主播吧

**Comment by yuerzi** [comment]
> 你这个是未设置clientRole为主播吧

主播在是在桌面客户端进行直播，我开着客户端那。app只是观众用，我应该不用在app中设置主播吧？

**Comment by LichKing-2234** [comment]
AgoraRenderWidget的代码看下

**Comment by LichKing-2234** [comment]
话说你是观众怎么显示自己

**Comment by yuerzi** [comment]
> 话说你是观众怎么显示自己

![1584930206397](https://user-images.githubusercontent.com/24539930/77274332-a9815e00-6cf0-11ea-9c56-626c42206b22.jpg)
![1584930332182](https://user-images.githubusercontent.com/24539930/77274335-abe3b800-6cf0-11ea-8666-5fc9f865f27f.jpg)
我现在收到的是桌面客户端传来的声音，把直播模式去掉，就显示我自己的图像

**Comment by LichKing-2234** [comment]
默认是通信模式，每个人都是主播

**Comment by LichKing-2234** [comment]
你可以看下这个文档
https://docs.agora.io/cn/Voice/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a1bfb76eb4365b8b97648c3d1b69f2bd6

**Comment by yuerzi** [comment]
> 你可以看下这个文档
> https://docs.agora.io/cn/Video/API%20Reference/java/classio_1_1agora_1_1rtc_1_1_rtc_engine.html#a1bfb76eb4365b8b97648c3d1b69f2bd6

我第一个截图里面，设置观众了。我在web端已经接入测试完毕，流程应该是差不多。基础设置直播模式，观众我都设置了还是图像黑屏

**Comment by LichKing-2234** [comment]
直播模式下，观众不会有本地视频，只有主播有

**Comment by yuerzi** [comment]
> 直播模式下，观众不会有本地视频，只有主播有
所以说我设置直播模式，当前用户设置为观众，只能听到客户端的声音，确无法获得客户端的图像。去掉主播模式，显示我自己的前置摄像头图像。很是惆怅！原理应该和web的差不多啊，非常苦恼，您看看我代码的设置有问题吗，我这是观众的，非常感谢

**Comment by LichKing-2234** [comment]
所以你是希望获取本地的视频，还是远端主播的视频

**Comment by yuerzi** [comment]
> 所以你是希望获取本地的视频，还是远端主播的视频

获取远端主播的

**Comment by LichKing-2234** [comment]
AgoraRenderWidget不要设置local: true，这样就表示加载本地预览

**Comment by yuerzi** [comment]
> AgoraRenderWidget不要设置local: true，这样就表示加载本地预览

非常感谢！加载了远端图像。nice！！
