### ISSUE TITLE
AgoraRtcEngine.onLeaveChannel is not invoked

### ISSUE THREAD

**Issue by rgb1380** [AgoraIO/Flutter-SDK#98]
To replicate run the sample code and join a channel. Put a breakpoint in 
    AgoraRtcEngine.onLeaveChannel = () {
      setState(() {
        _infoStrings.add('onLeaveChannel');
        _users.clear();
      });
    };
The method is never invoked.

**Comment by LichKing-2234** [comment]
any error log？

**Comment by rgb1380** [comment]
There is no error. The method does not get invoked and the message does not appear. It should be possible to replicate it by running the sample app unchanged.

**Comment by rgb1380** [comment]
I realised that I have posted in the issue in the SDK project. The issue is related to the flutter sample. I have solved the issue and explained here:
https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/89

**Comment by LichKing-2234** [comment]
same as https://github.com/AgoraIO-Community/Agora-Flutter-Quickstart/issues/89
