### ISSUE TITLE
Add support for setting video encoder configuration.

### ISSUE THREAD

**Issue by kadariyaujwal** [AgoraIO/Flutter-SDK#99]
Hello, can you please add an option to set video encoder configuration? If it's already, let me know how?

**Comment by ironynet** [comment]
See the api document.

https://pub.dev/documentation/agora_rtc_engine/latest/agora_rtc_engine/AgoraRtcEngine/setVideoEncoderConfiguration.html
https://pub.dev/documentation/agora_rtc_engine/latest/agora_rtc_engine/VideoEncoderConfiguration-class.html
